package com.sunyard.ars.system.dao.hx;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.sunyard.ars.system.bean.hx.ArmsFavorite;

public interface ArmsFavoriteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMS_FAVORITE_TB
     *
     * @mbggenerated
     */
    int insert(ArmsFavorite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMS_FAVORITE_TB
     *
     * @mbggenerated
     */
    int insertSelective(ArmsFavorite record);
    int deleteByKey(@Param(value="userNo")String userNo,@Param(value="id")String id,@Param(value="entryId2")String entryId2);

	List<Map<Object, String>> getAlarmInfoList(HashMap condMap);

	List<Map<Object, String>> getAlarmInfoDetailList(HashMap condMap);

	int deleteFavorite(HashMap condMap);

	int setCommon(HashMap condMap);

	List<Map<Object, String>> getAlarmBillData(Map paraMap);
}