package com.sunyard.ars.system.dao.hx;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.sunyard.ars.system.bean.hx.ArmsEntrySetting;

public interface ArmsEntrySettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMS_ENTRY_SETTING
     *
     * @mbggenerated
     */
    int insert(ArmsEntrySetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMS_ENTRY_SETTING
     *
     * @mbggenerated
     */
    int insertSelective(ArmsEntrySetting record);
    List<Map<Object,String>> selectBySelective(@Param(value="modelName") String modelName,@Param(value="startAddTime") String startAddTime,@Param(value="endAddTime") String endAddTime,@Param(value="organNo")String organNo);
    List<Map<Object,String>> selectByEntryId(@Param(value="entryId") String entryId);

//   List<Map> selectByFieldsAndOrganNo(@Param(value="fields") String fields,@Param(value="tableName") String tableName,@Param(value="favoriteType") String favoriteType,@Param(value="entryId") String entryId,@Param(value="organNo") String organNo);
//   List<Map> selectByFields(@Param(value="fields") String fields,@Param(value="tableName") String tableName,@Param(value="favoriteType") String favoriteType,@Param(value="entryId") String entryId);
//   List<Map> queryAlarmInfoFromHis(@Param(value="tableName") String tableName,@Param(value="entryId") String entryId,@Param(value="entryRowId") String entryRowId);

    /**
	 * @author:		 SUNYARD-NGQ
	 * @date:		 2018年9月21日 下午2:05:26
	 * @description: TODO(无条件查询所有数据 )
	 */
	List selectAllName();

	/**
	 * @author:		 SUNYARD-NGQ
	 * @date:		 2018年9月25日 上午11:29:28
	 * @description: TODO(获取entryid对应的模型的名字 )
	 */
	ArmsEntrySetting selectNameByEntryid(@Param(value="entryid") String entryid);
}