package com.sunyard.ars.system.dao.hx;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sunyard.ars.system.bean.hx.EntryRisk;

/**
 * @author:		 SUNYARD-NGQ
 * @date:		 2018年9月20日 下午7:41:24
 * @description: TODO(模型驱动因子的数据库接口类 )
 */
public interface EntryRiskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ET_ENTRY_RISK
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("id") Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ET_ENTRY_RISK
     *
     * @mbggenerated
     */
    int insert(EntryRisk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ET_ENTRY_RISK
     * 新增数据库数据，数据信息非空
     * @mbggenerated
     */
    int insertSelective(EntryRisk record);

	/**
	 * @author:		 SUNYARD-NGQ
	 * @date:		 2018年9月25日 下午3:19:55
	 * @description: TODO(多表关联查询 )
	 */
	List selectBySelectiveTables();

	/**
	 * @author:		 SUNYARD-NGQ
	 * @date:		 2018年9月27日 下午1:02:28
	 * @description: TODO(条件联合查询 )
	 */
	List selectByCondition(@Param("entryid") Integer entryid, @Param("sourceNo") Integer sourceNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ET_ENTRY_RISK
     *
     * @mbggenerated
     */
    EntryRisk selectByPrimaryKey(Integer id);
    
	/**
	 * @author:		 SUNYARD-NGQ
	 * @date:		 2018年9月20日 下午7:09:15
	 * @description: TODO(查询对象的所有信息)
	 */
	List<EntryRisk> selectBySelective(EntryRisk entryRiskBean);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ET_ENTRY_RISK
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EntryRisk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ET_ENTRY_RISK
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EntryRisk record);

	/**
	 * @author:		 SUNYARD-NGQ
	 * @date:		 2018年9月20日 下午7:40:06
	 * @description: TODO(修改数据 )
	 */
	void updateSelective(EntryRisk entryRiskOld, EntryRisk entryRiskNew);

	/**
	 * @author:		 SUNYARD-NGQ
	 * @date:		 2018年10月8日 下午6:35:41
	 * @description: TODO(获取最大的主键id )
	 */
	Integer getMaxId();


}