package com.sunyard.ars.system.dao.hx;

import com.sunyard.ars.system.bean.hx.EntryRisk;
import com.sunyard.ars.system.bean.hx.ModeEngineEle;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

/**
 * @author:		 SUNYARD-NGQ
 * @date:		 2018年9月20日 下午7:41:24
 * @description: TODO(模型驱动因子的数据库接口类 )
 */
public interface ModelEngineEleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ET_ENTRY_RISK
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ET_ENTRY_RISK
     *
     * @mbggenerated
     */
    int insert(EntryRisk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ET_ENTRY_RISK
     * 新增数据库数据，数据信息非空
     * @mbggenerated
     */
    int insertSelective(ModeEngineEle modeEngineEleBean);

	/**
	 * @author:		 SUNYARD-NGQ
	 * @date:		 2018年9月25日 下午3:19:55
	 * @description: TODO(多表关联查询 )
	 */
	List selectBySelectiveTables(@Param("organNo") String organNo);

	/**
	 * @author:		 SUNYARD-NGQ
	 * @date:		 2018年9月27日 下午2:04:55
	 * @description: TODO(条件联合查询 )
	 */
	List selectByCondition(@Param("entryid") String entryid, @Param("sourceType") String sourceType, @Param("sourceName") String sourceName,@Param("organNo") String organNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ET_ENTRY_RISK
     *
     * @mbggenerated
     */
    EntryRisk selectByPrimaryKey(BigDecimal id);
    
	/**
	 * @author:		 SUNYARD-NGQ
	 * @date:		 2018年9月20日 下午7:09:15
	 * @description: TODO(查询对象的所有信息)
	 */
	List<ModeEngineEle> selectBySelective(ModeEngineEle modeEngineEleBean);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ET_ENTRY_RISK
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EntryRisk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ET_ENTRY_RISK
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EntryRisk record);

	/**
	 * @author:		 SUNYARD-NGQ
	 * @date:		 2018年9月20日 下午7:40:06
	 * @description: TODO(修改数据 )
	 */
	void updateSelective(EntryRisk entryRiskOld, EntryRisk entryRiskNew);


}