package com.sunyard.ars.system.bean.sc;

import java.math.BigDecimal;

public class BusinessType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNARS.SM_BUSINESS_TB.BUSINESS_ID
     *
     * @mbggenerated
     */
    private BigDecimal businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNARS.SM_BUSINESS_TB.BUSINESS_NAME
     *
     * @mbggenerated
     */
    private String businessName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNARS.SM_BUSINESS_TB.BUSINESS_DESC
     *
     * @mbggenerated
     */
    private String businessDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNARS.SM_BUSINESS_TB.IS_NEED_PROCESS
     *
     * @mbggenerated
     */
    private String isNeedProcess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNARS.SM_BUSINESS_TB.WHERE_STRING
     *
     * @mbggenerated
     */
    private String whereString;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNARS.SM_BUSINESS_TB.NEED_PACKAGE
     *
     * @mbggenerated
     */
    private String needPackage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNARS.SM_BUSINESS_TB.PACKAGE_ORGAN
     *
     * @mbggenerated
     */
    private String packageOrgan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNARS.SM_BUSINESS_TB.PRIVNAME
     *
     * @mbggenerated
     */
    private String privname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNARS.SM_BUSINESS_TB.KEEP_YEARS
     *
     * @mbggenerated
     */
    private String keepYears;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNARS.SM_BUSINESS_TB.BUSINESS_ID
     *
     * @return the value of SUNARS.SM_BUSINESS_TB.BUSINESS_ID
     *
     * @mbggenerated
     */
    public BigDecimal getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNARS.SM_BUSINESS_TB.BUSINESS_ID
     *
     * @param businessId the value for SUNARS.SM_BUSINESS_TB.BUSINESS_ID
     *
     * @mbggenerated
     */
    public void setBusinessId(BigDecimal businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNARS.SM_BUSINESS_TB.BUSINESS_NAME
     *
     * @return the value of SUNARS.SM_BUSINESS_TB.BUSINESS_NAME
     *
     * @mbggenerated
     */
    public String getBusinessName() {
        return businessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNARS.SM_BUSINESS_TB.BUSINESS_NAME
     *
     * @param businessName the value for SUNARS.SM_BUSINESS_TB.BUSINESS_NAME
     *
     * @mbggenerated
     */
    public void setBusinessName(String businessName) {
        this.businessName = businessName == null ? null : businessName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNARS.SM_BUSINESS_TB.BUSINESS_DESC
     *
     * @return the value of SUNARS.SM_BUSINESS_TB.BUSINESS_DESC
     *
     * @mbggenerated
     */
    public String getBusinessDesc() {
        return businessDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNARS.SM_BUSINESS_TB.BUSINESS_DESC
     *
     * @param businessDesc the value for SUNARS.SM_BUSINESS_TB.BUSINESS_DESC
     *
     * @mbggenerated
     */
    public void setBusinessDesc(String businessDesc) {
        this.businessDesc = businessDesc == null ? null : businessDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNARS.SM_BUSINESS_TB.IS_NEED_PROCESS
     *
     * @return the value of SUNARS.SM_BUSINESS_TB.IS_NEED_PROCESS
     *
     * @mbggenerated
     */
    public String getIsNeedProcess() {
        return isNeedProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNARS.SM_BUSINESS_TB.IS_NEED_PROCESS
     *
     * @param isNeedProcess the value for SUNARS.SM_BUSINESS_TB.IS_NEED_PROCESS
     *
     * @mbggenerated
     */
    public void setIsNeedProcess(String isNeedProcess) {
        this.isNeedProcess = isNeedProcess == null ? null : isNeedProcess.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNARS.SM_BUSINESS_TB.WHERE_STRING
     *
     * @return the value of SUNARS.SM_BUSINESS_TB.WHERE_STRING
     *
     * @mbggenerated
     */
    public String getWhereString() {
        return whereString;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNARS.SM_BUSINESS_TB.WHERE_STRING
     *
     * @param whereString the value for SUNARS.SM_BUSINESS_TB.WHERE_STRING
     *
     * @mbggenerated
     */
    public void setWhereString(String whereString) {
        this.whereString = whereString == null ? null : whereString.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNARS.SM_BUSINESS_TB.NEED_PACKAGE
     *
     * @return the value of SUNARS.SM_BUSINESS_TB.NEED_PACKAGE
     *
     * @mbggenerated
     */
    public String getNeedPackage() {
        return needPackage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNARS.SM_BUSINESS_TB.NEED_PACKAGE
     *
     * @param needPackage the value for SUNARS.SM_BUSINESS_TB.NEED_PACKAGE
     *
     * @mbggenerated
     */
    public void setNeedPackage(String needPackage) {
        this.needPackage = needPackage == null ? null : needPackage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNARS.SM_BUSINESS_TB.PACKAGE_ORGAN
     *
     * @return the value of SUNARS.SM_BUSINESS_TB.PACKAGE_ORGAN
     *
     * @mbggenerated
     */
    public String getPackageOrgan() {
        return packageOrgan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNARS.SM_BUSINESS_TB.PACKAGE_ORGAN
     *
     * @param packageOrgan the value for SUNARS.SM_BUSINESS_TB.PACKAGE_ORGAN
     *
     * @mbggenerated
     */
    public void setPackageOrgan(String packageOrgan) {
        this.packageOrgan = packageOrgan == null ? null : packageOrgan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNARS.SM_BUSINESS_TB.PRIVNAME
     *
     * @return the value of SUNARS.SM_BUSINESS_TB.PRIVNAME
     *
     * @mbggenerated
     */
    public String getPrivname() {
        return privname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNARS.SM_BUSINESS_TB.PRIVNAME
     *
     * @param privname the value for SUNARS.SM_BUSINESS_TB.PRIVNAME
     *
     * @mbggenerated
     */
    public void setPrivname(String privname) {
        this.privname = privname == null ? null : privname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNARS.SM_BUSINESS_TB.KEEP_YEARS
     *
     * @return the value of SUNARS.SM_BUSINESS_TB.KEEP_YEARS
     *
     * @mbggenerated
     */
    public String getKeepYears() {
        return keepYears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNARS.SM_BUSINESS_TB.KEEP_YEARS
     *
     * @param keepYears the value for SUNARS.SM_BUSINESS_TB.KEEP_YEARS
     *
     * @mbggenerated
     */
    public void setKeepYears(String keepYears) {
        this.keepYears = keepYears == null ? null : keepYears.trim();
    }
}