package com.sunyard.ars.system.bean.sc;

public class FieldDef {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_FIELD_DEF_TB.FIELD_NAME
     *
     * @mbggenerated
     */
    private String fieldName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_FIELD_DEF_TB.ELSE_NAME
     *
     * @mbggenerated
     */
    private String elseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_FIELD_DEF_TB.FIELD_TYPE
     *
     * @mbggenerated
     */
    private String fieldType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_FIELD_DEF_TB.FIELD_LENGTH
     *
     * @mbggenerated
     */
    private String fieldLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_FIELD_DEF_TB.FIELD_FLOAT
     *
     * @mbggenerated
     */
    private String fieldFloat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_FIELD_DEF_TB.F_IS_NULL
     *
     * @mbggenerated
     */
    private String fIsNull;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_FIELD_DEF_TB.DEF_VALUE
     *
     * @mbggenerated
     */
    private String defValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_FIELD_DEF_TB.F_HAS_DIC
     *
     * @mbggenerated
     */
    private String fHasDic;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_FIELD_DEF_TB.FIELD_NAME
     *
     * @return the value of SM_FIELD_DEF_TB.FIELD_NAME
     *
     * @mbggenerated
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_FIELD_DEF_TB.FIELD_NAME
     *
     * @param fieldName the value for SM_FIELD_DEF_TB.FIELD_NAME
     *
     * @mbggenerated
     */
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName == null ? null : fieldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_FIELD_DEF_TB.ELSE_NAME
     *
     * @return the value of SM_FIELD_DEF_TB.ELSE_NAME
     *
     * @mbggenerated
     */
    public String getElseName() {
        return elseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_FIELD_DEF_TB.ELSE_NAME
     *
     * @param elseName the value for SM_FIELD_DEF_TB.ELSE_NAME
     *
     * @mbggenerated
     */
    public void setElseName(String elseName) {
        this.elseName = elseName == null ? null : elseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_FIELD_DEF_TB.FIELD_TYPE
     *
     * @return the value of SM_FIELD_DEF_TB.FIELD_TYPE
     *
     * @mbggenerated
     */
    public String getFieldType() {
        return fieldType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_FIELD_DEF_TB.FIELD_TYPE
     *
     * @param fieldType the value for SM_FIELD_DEF_TB.FIELD_TYPE
     *
     * @mbggenerated
     */
    public void setFieldType(String fieldType) {
        this.fieldType = fieldType == null ? null : fieldType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_FIELD_DEF_TB.FIELD_LENGTH
     *
     * @return the value of SM_FIELD_DEF_TB.FIELD_LENGTH
     *
     * @mbggenerated
     */
    public String getFieldLength() {
        return fieldLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_FIELD_DEF_TB.FIELD_LENGTH
     *
     * @param fieldLength the value for SM_FIELD_DEF_TB.FIELD_LENGTH
     *
     * @mbggenerated
     */
    public void setFieldLength(String fieldLength) {
        this.fieldLength = fieldLength == null ? null : fieldLength.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_FIELD_DEF_TB.FIELD_FLOAT
     *
     * @return the value of SM_FIELD_DEF_TB.FIELD_FLOAT
     *
     * @mbggenerated
     */
    public String getFieldFloat() {
        return fieldFloat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_FIELD_DEF_TB.FIELD_FLOAT
     *
     * @param fieldFloat the value for SM_FIELD_DEF_TB.FIELD_FLOAT
     *
     * @mbggenerated
     */
    public void setFieldFloat(String fieldFloat) {
        this.fieldFloat = fieldFloat == null ? null : fieldFloat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_FIELD_DEF_TB.F_IS_NULL
     *
     * @return the value of SM_FIELD_DEF_TB.F_IS_NULL
     *
     * @mbggenerated
     */
    public String getfIsNull() {
        return fIsNull;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_FIELD_DEF_TB.F_IS_NULL
     *
     * @param fIsNull the value for SM_FIELD_DEF_TB.F_IS_NULL
     *
     * @mbggenerated
     */
    public void setfIsNull(String fIsNull) {
        this.fIsNull = fIsNull == null ? null : fIsNull.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_FIELD_DEF_TB.DEF_VALUE
     *
     * @return the value of SM_FIELD_DEF_TB.DEF_VALUE
     *
     * @mbggenerated
     */
    public String getDefValue() {
        return defValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_FIELD_DEF_TB.DEF_VALUE
     *
     * @param defValue the value for SM_FIELD_DEF_TB.DEF_VALUE
     *
     * @mbggenerated
     */
    public void setDefValue(String defValue) {
        this.defValue = defValue == null ? null : defValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_FIELD_DEF_TB.F_HAS_DIC
     *
     * @return the value of SM_FIELD_DEF_TB.F_HAS_DIC
     *
     * @mbggenerated
     */
    public String getfHasDic() {
        return fHasDic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_FIELD_DEF_TB.F_HAS_DIC
     *
     * @param fHasDic the value for SM_FIELD_DEF_TB.F_HAS_DIC
     *
     * @mbggenerated
     */
    public void setfHasDic(String fHasDic) {
        this.fHasDic = fHasDic == null ? null : fHasDic.trim();
    }
}