package com.sunyard.ars.system.bean.sc;

import java.math.BigDecimal;

public class FormInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_FORM_INFO_TB.FORM_ID
     *
     * @mbggenerated
     */
    private BigDecimal formId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_FORM_INFO_TB.FORM_NAME
     *
     * @mbggenerated
     */
    private String formName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_FORM_INFO_TB.DESCRIPTION
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_FORM_INFO_TB.CREATE_TIME
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_FORM_INFO_TB.MODIFIED_TIME
     *
     * @mbggenerated
     */
    private String modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_FORM_INFO_TB.CREATOR
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_FORM_INFO_TB.MODIFIER
     *
     * @mbggenerated
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_FORM_INFO_TB.ALTER_PAGES
     *
     * @mbggenerated
     */
    private BigDecimal alterPages;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_FORM_INFO_TB.TOTAL_PAGES
     *
     * @mbggenerated
     */
    private BigDecimal totalPages;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_FORM_INFO_TB.REGULAR_EXP
     *
     * @mbggenerated
     */
    private String regularExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_FORM_INFO_TB.CONSTANT_PAGE
     *
     * @mbggenerated
     */
    private BigDecimal constantPage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_FORM_INFO_TB.TOTAL_RULE_COUNT
     *
     * @mbggenerated
     */
    private BigDecimal totalRuleCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_FORM_INFO_TB.FOLDER_ID
     *
     * @mbggenerated
     */
    private String folderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_FORM_INFO_TB.LOCK_KEY
     *
     * @mbggenerated
     */
    private BigDecimal lockKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_FORM_INFO_TB.SEARCH_INDEX
     *
     * @mbggenerated
     */
    private BigDecimal searchIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_FORM_INFO_TB.AREA_CODE
     *
     * @mbggenerated
     */
    private String areaCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_FORM_INFO_TB.FORM_ID
     *
     * @return the value of SM_FORM_INFO_TB.FORM_ID
     *
     * @mbggenerated
     */
    public BigDecimal getFormId() {
        return formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_FORM_INFO_TB.FORM_ID
     *
     * @param formId the value for SM_FORM_INFO_TB.FORM_ID
     *
     * @mbggenerated
     */
    public void setFormId(BigDecimal formId) {
        this.formId = formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_FORM_INFO_TB.FORM_NAME
     *
     * @return the value of SM_FORM_INFO_TB.FORM_NAME
     *
     * @mbggenerated
     */
    public String getFormName() {
        return formName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_FORM_INFO_TB.FORM_NAME
     *
     * @param formName the value for SM_FORM_INFO_TB.FORM_NAME
     *
     * @mbggenerated
     */
    public void setFormName(String formName) {
        this.formName = formName == null ? null : formName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_FORM_INFO_TB.DESCRIPTION
     *
     * @return the value of SM_FORM_INFO_TB.DESCRIPTION
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_FORM_INFO_TB.DESCRIPTION
     *
     * @param description the value for SM_FORM_INFO_TB.DESCRIPTION
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_FORM_INFO_TB.CREATE_TIME
     *
     * @return the value of SM_FORM_INFO_TB.CREATE_TIME
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_FORM_INFO_TB.CREATE_TIME
     *
     * @param createTime the value for SM_FORM_INFO_TB.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_FORM_INFO_TB.MODIFIED_TIME
     *
     * @return the value of SM_FORM_INFO_TB.MODIFIED_TIME
     *
     * @mbggenerated
     */
    public String getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_FORM_INFO_TB.MODIFIED_TIME
     *
     * @param modifiedTime the value for SM_FORM_INFO_TB.MODIFIED_TIME
     *
     * @mbggenerated
     */
    public void setModifiedTime(String modifiedTime) {
        this.modifiedTime = modifiedTime == null ? null : modifiedTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_FORM_INFO_TB.CREATOR
     *
     * @return the value of SM_FORM_INFO_TB.CREATOR
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_FORM_INFO_TB.CREATOR
     *
     * @param creator the value for SM_FORM_INFO_TB.CREATOR
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_FORM_INFO_TB.MODIFIER
     *
     * @return the value of SM_FORM_INFO_TB.MODIFIER
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_FORM_INFO_TB.MODIFIER
     *
     * @param modifier the value for SM_FORM_INFO_TB.MODIFIER
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_FORM_INFO_TB.ALTER_PAGES
     *
     * @return the value of SM_FORM_INFO_TB.ALTER_PAGES
     *
     * @mbggenerated
     */
    public BigDecimal getAlterPages() {
        return alterPages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_FORM_INFO_TB.ALTER_PAGES
     *
     * @param alterPages the value for SM_FORM_INFO_TB.ALTER_PAGES
     *
     * @mbggenerated
     */
    public void setAlterPages(BigDecimal alterPages) {
        this.alterPages = alterPages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_FORM_INFO_TB.TOTAL_PAGES
     *
     * @return the value of SM_FORM_INFO_TB.TOTAL_PAGES
     *
     * @mbggenerated
     */
    public BigDecimal getTotalPages() {
        return totalPages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_FORM_INFO_TB.TOTAL_PAGES
     *
     * @param totalPages the value for SM_FORM_INFO_TB.TOTAL_PAGES
     *
     * @mbggenerated
     */
    public void setTotalPages(BigDecimal totalPages) {
        this.totalPages = totalPages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_FORM_INFO_TB.REGULAR_EXP
     *
     * @return the value of SM_FORM_INFO_TB.REGULAR_EXP
     *
     * @mbggenerated
     */
    public String getRegularExp() {
        return regularExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_FORM_INFO_TB.REGULAR_EXP
     *
     * @param regularExp the value for SM_FORM_INFO_TB.REGULAR_EXP
     *
     * @mbggenerated
     */
    public void setRegularExp(String regularExp) {
        this.regularExp = regularExp == null ? null : regularExp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_FORM_INFO_TB.CONSTANT_PAGE
     *
     * @return the value of SM_FORM_INFO_TB.CONSTANT_PAGE
     *
     * @mbggenerated
     */
    public BigDecimal getConstantPage() {
        return constantPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_FORM_INFO_TB.CONSTANT_PAGE
     *
     * @param constantPage the value for SM_FORM_INFO_TB.CONSTANT_PAGE
     *
     * @mbggenerated
     */
    public void setConstantPage(BigDecimal constantPage) {
        this.constantPage = constantPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_FORM_INFO_TB.TOTAL_RULE_COUNT
     *
     * @return the value of SM_FORM_INFO_TB.TOTAL_RULE_COUNT
     *
     * @mbggenerated
     */
    public BigDecimal getTotalRuleCount() {
        return totalRuleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_FORM_INFO_TB.TOTAL_RULE_COUNT
     *
     * @param totalRuleCount the value for SM_FORM_INFO_TB.TOTAL_RULE_COUNT
     *
     * @mbggenerated
     */
    public void setTotalRuleCount(BigDecimal totalRuleCount) {
        this.totalRuleCount = totalRuleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_FORM_INFO_TB.FOLDER_ID
     *
     * @return the value of SM_FORM_INFO_TB.FOLDER_ID
     *
     * @mbggenerated
     */
    public String getFolderId() {
        return folderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_FORM_INFO_TB.FOLDER_ID
     *
     * @param folderId the value for SM_FORM_INFO_TB.FOLDER_ID
     *
     * @mbggenerated
     */
    public void setFolderId(String folderId) {
        this.folderId = folderId == null ? null : folderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_FORM_INFO_TB.LOCK_KEY
     *
     * @return the value of SM_FORM_INFO_TB.LOCK_KEY
     *
     * @mbggenerated
     */
    public BigDecimal getLockKey() {
        return lockKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_FORM_INFO_TB.LOCK_KEY
     *
     * @param lockKey the value for SM_FORM_INFO_TB.LOCK_KEY
     *
     * @mbggenerated
     */
    public void setLockKey(BigDecimal lockKey) {
        this.lockKey = lockKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_FORM_INFO_TB.SEARCH_INDEX
     *
     * @return the value of SM_FORM_INFO_TB.SEARCH_INDEX
     *
     * @mbggenerated
     */
    public BigDecimal getSearchIndex() {
        return searchIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_FORM_INFO_TB.SEARCH_INDEX
     *
     * @param searchIndex the value for SM_FORM_INFO_TB.SEARCH_INDEX
     *
     * @mbggenerated
     */
    public void setSearchIndex(BigDecimal searchIndex) {
        this.searchIndex = searchIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_FORM_INFO_TB.AREA_CODE
     *
     * @return the value of SM_FORM_INFO_TB.AREA_CODE
     *
     * @mbggenerated
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_FORM_INFO_TB.AREA_CODE
     *
     * @param areaCode the value for SM_FORM_INFO_TB.AREA_CODE
     *
     * @mbggenerated
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }
}