package com.sunyard.ars.system.bean.sc;

public class ModuleDef {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNARS.SM_MODULE_DEF_TB.MODULE_NAME
     *
     * @mbggenerated
     */
    private String moduleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNARS.SM_MODULE_DEF_TB.MODULE_ALIA
     *
     * @mbggenerated
     */
    private String moduleAlia;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNARS.SM_MODULE_DEF_TB.MODULE_DESC
     *
     * @mbggenerated
     */
    private String moduleDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNARS.SM_MODULE_DEF_TB.MODULE_URL
     *
     * @mbggenerated
     */
    private String moduleUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNARS.SM_MODULE_DEF_TB.MODULE_IMAGE
     *
     * @mbggenerated
     */
    private String moduleImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNARS.SM_MODULE_DEF_TB.MODULE_PRIV
     *
     * @mbggenerated
     */
    private String modulePriv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNARS.SM_MODULE_DEF_TB.IS_USE
     *
     * @mbggenerated
     */
    private String isUse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNARS.SM_MODULE_DEF_TB.JUMP_TYPE
     *
     * @mbggenerated
     */
    private String jumpType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNARS.SM_MODULE_DEF_TB.MODULE_NAME
     *
     * @return the value of SUNARS.SM_MODULE_DEF_TB.MODULE_NAME
     *
     * @mbggenerated
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNARS.SM_MODULE_DEF_TB.MODULE_NAME
     *
     * @param moduleName the value for SUNARS.SM_MODULE_DEF_TB.MODULE_NAME
     *
     * @mbggenerated
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName == null ? null : moduleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNARS.SM_MODULE_DEF_TB.MODULE_ALIA
     *
     * @return the value of SUNARS.SM_MODULE_DEF_TB.MODULE_ALIA
     *
     * @mbggenerated
     */
    public String getModuleAlia() {
        return moduleAlia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNARS.SM_MODULE_DEF_TB.MODULE_ALIA
     *
     * @param moduleAlia the value for SUNARS.SM_MODULE_DEF_TB.MODULE_ALIA
     *
     * @mbggenerated
     */
    public void setModuleAlia(String moduleAlia) {
        this.moduleAlia = moduleAlia == null ? null : moduleAlia.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNARS.SM_MODULE_DEF_TB.MODULE_DESC
     *
     * @return the value of SUNARS.SM_MODULE_DEF_TB.MODULE_DESC
     *
     * @mbggenerated
     */
    public String getModuleDesc() {
        return moduleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNARS.SM_MODULE_DEF_TB.MODULE_DESC
     *
     * @param moduleDesc the value for SUNARS.SM_MODULE_DEF_TB.MODULE_DESC
     *
     * @mbggenerated
     */
    public void setModuleDesc(String moduleDesc) {
        this.moduleDesc = moduleDesc == null ? null : moduleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNARS.SM_MODULE_DEF_TB.MODULE_URL
     *
     * @return the value of SUNARS.SM_MODULE_DEF_TB.MODULE_URL
     *
     * @mbggenerated
     */
    public String getModuleUrl() {
        return moduleUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNARS.SM_MODULE_DEF_TB.MODULE_URL
     *
     * @param moduleUrl the value for SUNARS.SM_MODULE_DEF_TB.MODULE_URL
     *
     * @mbggenerated
     */
    public void setModuleUrl(String moduleUrl) {
        this.moduleUrl = moduleUrl == null ? null : moduleUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNARS.SM_MODULE_DEF_TB.MODULE_IMAGE
     *
     * @return the value of SUNARS.SM_MODULE_DEF_TB.MODULE_IMAGE
     *
     * @mbggenerated
     */
    public String getModuleImage() {
        return moduleImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNARS.SM_MODULE_DEF_TB.MODULE_IMAGE
     *
     * @param moduleImage the value for SUNARS.SM_MODULE_DEF_TB.MODULE_IMAGE
     *
     * @mbggenerated
     */
    public void setModuleImage(String moduleImage) {
        this.moduleImage = moduleImage == null ? null : moduleImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNARS.SM_MODULE_DEF_TB.MODULE_PRIV
     *
     * @return the value of SUNARS.SM_MODULE_DEF_TB.MODULE_PRIV
     *
     * @mbggenerated
     */
    public String getModulePriv() {
        return modulePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNARS.SM_MODULE_DEF_TB.MODULE_PRIV
     *
     * @param modulePriv the value for SUNARS.SM_MODULE_DEF_TB.MODULE_PRIV
     *
     * @mbggenerated
     */
    public void setModulePriv(String modulePriv) {
        this.modulePriv = modulePriv == null ? null : modulePriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNARS.SM_MODULE_DEF_TB.IS_USE
     *
     * @return the value of SUNARS.SM_MODULE_DEF_TB.IS_USE
     *
     * @mbggenerated
     */
    public String getIsUse() {
        return isUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNARS.SM_MODULE_DEF_TB.IS_USE
     *
     * @param isUse the value for SUNARS.SM_MODULE_DEF_TB.IS_USE
     *
     * @mbggenerated
     */
    public void setIsUse(String isUse) {
        this.isUse = isUse == null ? null : isUse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNARS.SM_MODULE_DEF_TB.JUMP_TYPE
     *
     * @return the value of SUNARS.SM_MODULE_DEF_TB.JUMP_TYPE
     *
     * @mbggenerated
     */
    public String getJumpType() {
        return jumpType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNARS.SM_MODULE_DEF_TB.JUMP_TYPE
     *
     * @param jumpType the value for SUNARS.SM_MODULE_DEF_TB.JUMP_TYPE
     *
     * @mbggenerated
     */
    public void setJumpType(String jumpType) {
        this.jumpType = jumpType == null ? null : jumpType.trim();
    }
}