package com.sunyard.ars.system.bean.sc;

import java.math.BigDecimal;

public class OrganData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_ORGAN_DATA_TB.ORGAN_NO
     *
     * @mbggenerated
     */
    private String organNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_ORGAN_DATA_TB.SERVICE_ID
     *
     * @mbggenerated
     */
    private BigDecimal serviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_ORGAN_DATA_TB.TMPBATCH_TB_ID
     *
     * @mbggenerated
     */
    private BigDecimal tmpbatchTbId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_ORGAN_DATA_TB.TMPDATA_TB_ID
     *
     * @mbggenerated
     */
    private BigDecimal tmpdataTbId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_ORGAN_DATA_TB.FLOW_TB_ID
     *
     * @mbggenerated
     */
    private BigDecimal flowTbId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_ORGAN_DATA_TB.ECMSERVICE_ID
     *
     * @mbggenerated
     */
    private String ecmserviceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_ORGAN_DATA_TB.ORGAN_NO
     *
     * @return the value of SM_ORGAN_DATA_TB.ORGAN_NO
     *
     * @mbggenerated
     */
    public String getOrganNo() {
        return organNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_ORGAN_DATA_TB.ORGAN_NO
     *
     * @param organNo the value for SM_ORGAN_DATA_TB.ORGAN_NO
     *
     * @mbggenerated
     */
    public void setOrganNo(String organNo) {
        this.organNo = organNo == null ? null : organNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_ORGAN_DATA_TB.SERVICE_ID
     *
     * @return the value of SM_ORGAN_DATA_TB.SERVICE_ID
     *
     * @mbggenerated
     */
    public BigDecimal getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_ORGAN_DATA_TB.SERVICE_ID
     *
     * @param serviceId the value for SM_ORGAN_DATA_TB.SERVICE_ID
     *
     * @mbggenerated
     */
    public void setServiceId(BigDecimal serviceId) {
        this.serviceId = serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_ORGAN_DATA_TB.TMPBATCH_TB_ID
     *
     * @return the value of SM_ORGAN_DATA_TB.TMPBATCH_TB_ID
     *
     * @mbggenerated
     */
    public BigDecimal getTmpbatchTbId() {
        return tmpbatchTbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_ORGAN_DATA_TB.TMPBATCH_TB_ID
     *
     * @param tmpbatchTbId the value for SM_ORGAN_DATA_TB.TMPBATCH_TB_ID
     *
     * @mbggenerated
     */
    public void setTmpbatchTbId(BigDecimal tmpbatchTbId) {
        this.tmpbatchTbId = tmpbatchTbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_ORGAN_DATA_TB.TMPDATA_TB_ID
     *
     * @return the value of SM_ORGAN_DATA_TB.TMPDATA_TB_ID
     *
     * @mbggenerated
     */
    public BigDecimal getTmpdataTbId() {
        return tmpdataTbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_ORGAN_DATA_TB.TMPDATA_TB_ID
     *
     * @param tmpdataTbId the value for SM_ORGAN_DATA_TB.TMPDATA_TB_ID
     *
     * @mbggenerated
     */
    public void setTmpdataTbId(BigDecimal tmpdataTbId) {
        this.tmpdataTbId = tmpdataTbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_ORGAN_DATA_TB.FLOW_TB_ID
     *
     * @return the value of SM_ORGAN_DATA_TB.FLOW_TB_ID
     *
     * @mbggenerated
     */
    public BigDecimal getFlowTbId() {
        return flowTbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_ORGAN_DATA_TB.FLOW_TB_ID
     *
     * @param flowTbId the value for SM_ORGAN_DATA_TB.FLOW_TB_ID
     *
     * @mbggenerated
     */
    public void setFlowTbId(BigDecimal flowTbId) {
        this.flowTbId = flowTbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_ORGAN_DATA_TB.ECMSERVICE_ID
     *
     * @return the value of SM_ORGAN_DATA_TB.ECMSERVICE_ID
     *
     * @mbggenerated
     */
    public String getEcmserviceId() {
        return ecmserviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_ORGAN_DATA_TB.ECMSERVICE_ID
     *
     * @param ecmserviceId the value for SM_ORGAN_DATA_TB.ECMSERVICE_ID
     *
     * @mbggenerated
     */
    public void setEcmserviceId(String ecmserviceId) {
        this.ecmserviceId = ecmserviceId == null ? null : ecmserviceId.trim();
    }
}