package com.sunyard.ars.system.bean.sc;

public class SCDatasource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNARS.SM_DATASOURCE_SET_TB.DATA_SOURCE_ID
     *
     * @mbggenerated
     */
    private String dataSourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNARS.SM_DATASOURCE_SET_TB.GROUP_NAME
     *
     * @mbggenerated
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNARS.SM_DATASOURCE_SET_TB.MODE_CODE
     *
     * @mbggenerated
     */
    private String modeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNARS.SM_DATASOURCE_SET_TB.INDEX_NAME
     *
     * @mbggenerated
     */
    private String indexName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNARS.SM_DATASOURCE_SET_TB.FILE_PART_NAME
     *
     * @mbggenerated
     */
    private String filePartName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNARS.SM_DATASOURCE_SET_TB.UA_IP
     *
     * @mbggenerated
     */
    private String uaIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNARS.SM_DATASOURCE_SET_TB.UA_PORT
     *
     * @mbggenerated
     */
    private String uaPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNARS.SM_DATASOURCE_SET_TB.DATA_DESC
     *
     * @mbggenerated
     */
    private String dataDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNARS.SM_DATASOURCE_SET_TB.CUST_ID
     *
     * @mbggenerated
     */
    private String custId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNARS.SM_DATASOURCE_SET_TB.SERVICE_ID
     *
     * @mbggenerated
     */
    private String serviceId;

    private String dataSourceType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNARS.SM_DATASOURCE_SET_TB.DATA_SOURCE_ID
     *
     * @return the value of SUNARS.SM_DATASOURCE_SET_TB.DATA_SOURCE_ID
     *
     * @mbggenerated
     */
    public String getDataSourceId() {
        return dataSourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNARS.SM_DATASOURCE_SET_TB.DATA_SOURCE_ID
     *
     * @param dataSourceId the value for SUNARS.SM_DATASOURCE_SET_TB.DATA_SOURCE_ID
     *
     * @mbggenerated
     */
    public void setDataSourceId(String dataSourceId) {
        this.dataSourceId = dataSourceId == null ? null : dataSourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNARS.SM_DATASOURCE_SET_TB.GROUP_NAME
     *
     * @return the value of SUNARS.SM_DATASOURCE_SET_TB.GROUP_NAME
     *
     * @mbggenerated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNARS.SM_DATASOURCE_SET_TB.GROUP_NAME
     *
     * @param groupName the value for SUNARS.SM_DATASOURCE_SET_TB.GROUP_NAME
     *
     * @mbggenerated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNARS.SM_DATASOURCE_SET_TB.MODE_CODE
     *
     * @return the value of SUNARS.SM_DATASOURCE_SET_TB.MODE_CODE
     *
     * @mbggenerated
     */
    public String getModeCode() {
        return modeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNARS.SM_DATASOURCE_SET_TB.MODE_CODE
     *
     * @param modeCode the value for SUNARS.SM_DATASOURCE_SET_TB.MODE_CODE
     *
     * @mbggenerated
     */
    public void setModeCode(String modeCode) {
        this.modeCode = modeCode == null ? null : modeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNARS.SM_DATASOURCE_SET_TB.INDEX_NAME
     *
     * @return the value of SUNARS.SM_DATASOURCE_SET_TB.INDEX_NAME
     *
     * @mbggenerated
     */
    public String getIndexName() {
        return indexName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNARS.SM_DATASOURCE_SET_TB.INDEX_NAME
     *
     * @param indexName the value for SUNARS.SM_DATASOURCE_SET_TB.INDEX_NAME
     *
     * @mbggenerated
     */
    public void setIndexName(String indexName) {
        this.indexName = indexName == null ? null : indexName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNARS.SM_DATASOURCE_SET_TB.FILE_PART_NAME
     *
     * @return the value of SUNARS.SM_DATASOURCE_SET_TB.FILE_PART_NAME
     *
     * @mbggenerated
     */
    public String getFilePartName() {
        return filePartName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNARS.SM_DATASOURCE_SET_TB.FILE_PART_NAME
     *
     * @param filePartName the value for SUNARS.SM_DATASOURCE_SET_TB.FILE_PART_NAME
     *
     * @mbggenerated
     */
    public void setFilePartName(String filePartName) {
        this.filePartName = filePartName == null ? null : filePartName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNARS.SM_DATASOURCE_SET_TB.UA_IP
     *
     * @return the value of SUNARS.SM_DATASOURCE_SET_TB.UA_IP
     *
     * @mbggenerated
     */
    public String getUaIp() {
        return uaIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNARS.SM_DATASOURCE_SET_TB.UA_IP
     *
     * @param uaIp the value for SUNARS.SM_DATASOURCE_SET_TB.UA_IP
     *
     * @mbggenerated
     */
    public void setUaIp(String uaIp) {
        this.uaIp = uaIp == null ? null : uaIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNARS.SM_DATASOURCE_SET_TB.UA_PORT
     *
     * @return the value of SUNARS.SM_DATASOURCE_SET_TB.UA_PORT
     *
     * @mbggenerated
     */
    public String getUaPort() {
        return uaPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNARS.SM_DATASOURCE_SET_TB.UA_PORT
     *
     * @param uaPort the value for SUNARS.SM_DATASOURCE_SET_TB.UA_PORT
     *
     * @mbggenerated
     */
    public void setUaPort(String uaPort) {
        this.uaPort = uaPort == null ? null : uaPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNARS.SM_DATASOURCE_SET_TB.DATA_DESC
     *
     * @return the value of SUNARS.SM_DATASOURCE_SET_TB.DATA_DESC
     *
     * @mbggenerated
     */
    public String getDataDesc() {
        return dataDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNARS.SM_DATASOURCE_SET_TB.DATA_DESC
     *
     * @param dataDesc the value for SUNARS.SM_DATASOURCE_SET_TB.DATA_DESC
     *
     * @mbggenerated
     */
    public void setDataDesc(String dataDesc) {
        this.dataDesc = dataDesc == null ? null : dataDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNARS.SM_DATASOURCE_SET_TB.CUST_ID
     *
     * @return the value of SUNARS.SM_DATASOURCE_SET_TB.CUST_ID
     *
     * @mbggenerated
     */
    public String getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNARS.SM_DATASOURCE_SET_TB.CUST_ID
     *
     * @param custId the value for SUNARS.SM_DATASOURCE_SET_TB.CUST_ID
     *
     * @mbggenerated
     */
    public void setCustId(String custId) {
        this.custId = custId == null ? null : custId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNARS.SM_DATASOURCE_SET_TB.SERVICE_ID
     *
     * @return the value of SUNARS.SM_DATASOURCE_SET_TB.SERVICE_ID
     *
     * @mbggenerated
     */
    public String getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNARS.SM_DATASOURCE_SET_TB.SERVICE_ID
     *
     * @param serviceId the value for SUNARS.SM_DATASOURCE_SET_TB.SERVICE_ID
     *
     * @mbggenerated
     */
    public void setServiceId(String serviceId) {
        this.serviceId = serviceId == null ? null : serviceId.trim();
    }

    public String getDataSourceType() {
        return dataSourceType;
    }

    public void setDataSourceType(String dataSourceType) {
        this.dataSourceType = dataSourceType;
    }
}