package com.sunyard.ars.system.bean.sc;

import java.math.BigDecimal;

public class ServiceReg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_SERVICE_REG_TB.SERVICE_ID
     *
     * @mbggenerated
     */
    private BigDecimal serviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_SERVICE_REG_TB.SERVICE_NAME
     *
     * @mbggenerated
     */
    private String serviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_SERVICE_REG_TB.SERVICE_IP
     *
     * @mbggenerated
     */
    private String serviceIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_SERVICE_REG_TB.SERVICE_PORT
     *
     * @mbggenerated
     */
    private String servicePort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_SERVICE_REG_TB.SERVICE_TYPE
     *
     * @mbggenerated
     */
    private String serviceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_SERVICE_REG_TB.LOGIN_NAME
     *
     * @mbggenerated
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_SERVICE_REG_TB.LOGIN_PASS
     *
     * @mbggenerated
     */
    private String loginPass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_SERVICE_REG_TB.IS_MONITOR
     *
     * @mbggenerated
     */
    private String isMonitor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_SERVICE_REG_TB.LISTENER_POST
     *
     * @mbggenerated
     */
    private String listenerPost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_SERVICE_REG_TB.GROUP_ID
     *
     * @mbggenerated
     */
    private Long groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_SERVICE_REG_TB.WORK_TYPE
     *
     * @mbggenerated
     */
    private String workType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_SERVICE_REG_TB.SERVICE_ID
     *
     * @return the value of SM_SERVICE_REG_TB.SERVICE_ID
     *
     * @mbggenerated
     */
    public BigDecimal getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_SERVICE_REG_TB.SERVICE_ID
     *
     * @param serviceId the value for SM_SERVICE_REG_TB.SERVICE_ID
     *
     * @mbggenerated
     */
    public void setServiceId(BigDecimal serviceId) {
        this.serviceId = serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_SERVICE_REG_TB.SERVICE_NAME
     *
     * @return the value of SM_SERVICE_REG_TB.SERVICE_NAME
     *
     * @mbggenerated
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_SERVICE_REG_TB.SERVICE_NAME
     *
     * @param serviceName the value for SM_SERVICE_REG_TB.SERVICE_NAME
     *
     * @mbggenerated
     */
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName == null ? null : serviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_SERVICE_REG_TB.SERVICE_IP
     *
     * @return the value of SM_SERVICE_REG_TB.SERVICE_IP
     *
     * @mbggenerated
     */
    public String getServiceIp() {
        return serviceIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_SERVICE_REG_TB.SERVICE_IP
     *
     * @param serviceIp the value for SM_SERVICE_REG_TB.SERVICE_IP
     *
     * @mbggenerated
     */
    public void setServiceIp(String serviceIp) {
        this.serviceIp = serviceIp == null ? null : serviceIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_SERVICE_REG_TB.SERVICE_PORT
     *
     * @return the value of SM_SERVICE_REG_TB.SERVICE_PORT
     *
     * @mbggenerated
     */
    public String getServicePort() {
        return servicePort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_SERVICE_REG_TB.SERVICE_PORT
     *
     * @param servicePort the value for SM_SERVICE_REG_TB.SERVICE_PORT
     *
     * @mbggenerated
     */
    public void setServicePort(String servicePort) {
        this.servicePort = servicePort == null ? null : servicePort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_SERVICE_REG_TB.SERVICE_TYPE
     *
     * @return the value of SM_SERVICE_REG_TB.SERVICE_TYPE
     *
     * @mbggenerated
     */
    public String getServiceType() {
        return serviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_SERVICE_REG_TB.SERVICE_TYPE
     *
     * @param serviceType the value for SM_SERVICE_REG_TB.SERVICE_TYPE
     *
     * @mbggenerated
     */
    public void setServiceType(String serviceType) {
        this.serviceType = serviceType == null ? null : serviceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_SERVICE_REG_TB.LOGIN_NAME
     *
     * @return the value of SM_SERVICE_REG_TB.LOGIN_NAME
     *
     * @mbggenerated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_SERVICE_REG_TB.LOGIN_NAME
     *
     * @param loginName the value for SM_SERVICE_REG_TB.LOGIN_NAME
     *
     * @mbggenerated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_SERVICE_REG_TB.LOGIN_PASS
     *
     * @return the value of SM_SERVICE_REG_TB.LOGIN_PASS
     *
     * @mbggenerated
     */
    public String getLoginPass() {
        return loginPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_SERVICE_REG_TB.LOGIN_PASS
     *
     * @param loginPass the value for SM_SERVICE_REG_TB.LOGIN_PASS
     *
     * @mbggenerated
     */
    public void setLoginPass(String loginPass) {
        this.loginPass = loginPass == null ? null : loginPass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_SERVICE_REG_TB.IS_MONITOR
     *
     * @return the value of SM_SERVICE_REG_TB.IS_MONITOR
     *
     * @mbggenerated
     */
    public String getIsMonitor() {
        return isMonitor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_SERVICE_REG_TB.IS_MONITOR
     *
     * @param isMonitor the value for SM_SERVICE_REG_TB.IS_MONITOR
     *
     * @mbggenerated
     */
    public void setIsMonitor(String isMonitor) {
        this.isMonitor = isMonitor == null ? null : isMonitor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_SERVICE_REG_TB.LISTENER_POST
     *
     * @return the value of SM_SERVICE_REG_TB.LISTENER_POST
     *
     * @mbggenerated
     */
    public String getListenerPost() {
        return listenerPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_SERVICE_REG_TB.LISTENER_POST
     *
     * @param listenerPost the value for SM_SERVICE_REG_TB.LISTENER_POST
     *
     * @mbggenerated
     */
    public void setListenerPost(String listenerPost) {
        this.listenerPost = listenerPost == null ? null : listenerPost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_SERVICE_REG_TB.GROUP_ID
     *
     * @return the value of SM_SERVICE_REG_TB.GROUP_ID
     *
     * @mbggenerated
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_SERVICE_REG_TB.GROUP_ID
     *
     * @param groupId the value for SM_SERVICE_REG_TB.GROUP_ID
     *
     * @mbggenerated
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_SERVICE_REG_TB.WORK_TYPE
     *
     * @return the value of SM_SERVICE_REG_TB.WORK_TYPE
     *
     * @mbggenerated
     */
    public String getWorkType() {
        return workType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_SERVICE_REG_TB.WORK_TYPE
     *
     * @param workType the value for SM_SERVICE_REG_TB.WORK_TYPE
     *
     * @mbggenerated
     */
    public void setWorkType(String workType) {
        this.workType = workType == null ? null : workType.trim();
    }
}