package com.sunyard.ars.system.bean.sc;

import java.math.BigDecimal;

public class TableDef {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_TABLE_DEF_TB.TABLE_ID
     *
     * @mbggenerated
     */
    private BigDecimal tableId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_TABLE_DEF_TB.TABLE_NAME
     *
     * @mbggenerated
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_TABLE_DEF_TB.TABLE_TYPE
     *
     * @mbggenerated
     */
    private String tableType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_TABLE_DEF_TB.TABLE_DESC
     *
     * @mbggenerated
     */
    private String tableDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_TABLE_DEF_TB.TABLE_ID
     *
     * @return the value of SM_TABLE_DEF_TB.TABLE_ID
     *
     * @mbggenerated
     */
    public BigDecimal getTableId() {
        return tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_TABLE_DEF_TB.TABLE_ID
     *
     * @param tableId the value for SM_TABLE_DEF_TB.TABLE_ID
     *
     * @mbggenerated
     */
    public void setTableId(BigDecimal tableId) {
        this.tableId = tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_TABLE_DEF_TB.TABLE_NAME
     *
     * @return the value of SM_TABLE_DEF_TB.TABLE_NAME
     *
     * @mbggenerated
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_TABLE_DEF_TB.TABLE_NAME
     *
     * @param tableName the value for SM_TABLE_DEF_TB.TABLE_NAME
     *
     * @mbggenerated
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_TABLE_DEF_TB.TABLE_TYPE
     *
     * @return the value of SM_TABLE_DEF_TB.TABLE_TYPE
     *
     * @mbggenerated
     */
    public String getTableType() {
        return tableType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_TABLE_DEF_TB.TABLE_TYPE
     *
     * @param tableType the value for SM_TABLE_DEF_TB.TABLE_TYPE
     *
     * @mbggenerated
     */
    public void setTableType(String tableType) {
        this.tableType = tableType == null ? null : tableType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_TABLE_DEF_TB.TABLE_DESC
     *
     * @return the value of SM_TABLE_DEF_TB.TABLE_DESC
     *
     * @mbggenerated
     */
    public String getTableDesc() {
        return tableDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_TABLE_DEF_TB.TABLE_DESC
     *
     * @param tableDesc the value for SM_TABLE_DEF_TB.TABLE_DESC
     *
     * @mbggenerated
     */
    public void setTableDesc(String tableDesc) {
        this.tableDesc = tableDesc == null ? null : tableDesc.trim();
    }
}