package com.sunyard.ars.system.bean.sc;

import java.math.BigDecimal;

public class TableField {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_TABLE_FIELD_TB.TABLE_ID
     *
     * @mbggenerated
     */
    private BigDecimal tableId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_TABLE_FIELD_TB.FIELD_NAME
     *
     * @mbggenerated
     */
    private String fieldName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_TABLE_FIELD_TB.F_IS_PK
     *
     * @mbggenerated
     */
    private String fIsPk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_TABLE_FIELD_TB.F_IS_INDEX
     *
     * @mbggenerated
     */
    private String fIsIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_TABLE_FIELD_TB.INDEX_TYPE
     *
     * @mbggenerated
     */
    private String indexType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_TABLE_FIELD_TB.LOCATION
     *
     * @mbggenerated
     */
    private Short location;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_TABLE_FIELD_TB.TABLE_ID
     *
     * @return the value of SM_TABLE_FIELD_TB.TABLE_ID
     *
     * @mbggenerated
     */
    public BigDecimal getTableId() {
        return tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_TABLE_FIELD_TB.TABLE_ID
     *
     * @param tableId the value for SM_TABLE_FIELD_TB.TABLE_ID
     *
     * @mbggenerated
     */
    public void setTableId(BigDecimal tableId) {
        this.tableId = tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_TABLE_FIELD_TB.FIELD_NAME
     *
     * @return the value of SM_TABLE_FIELD_TB.FIELD_NAME
     *
     * @mbggenerated
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_TABLE_FIELD_TB.FIELD_NAME
     *
     * @param fieldName the value for SM_TABLE_FIELD_TB.FIELD_NAME
     *
     * @mbggenerated
     */
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName == null ? null : fieldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_TABLE_FIELD_TB.F_IS_PK
     *
     * @return the value of SM_TABLE_FIELD_TB.F_IS_PK
     *
     * @mbggenerated
     */
    public String getfIsPk() {
        return fIsPk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_TABLE_FIELD_TB.F_IS_PK
     *
     * @param fIsPk the value for SM_TABLE_FIELD_TB.F_IS_PK
     *
     * @mbggenerated
     */
    public void setfIsPk(String fIsPk) {
        this.fIsPk = fIsPk == null ? null : fIsPk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_TABLE_FIELD_TB.F_IS_INDEX
     *
     * @return the value of SM_TABLE_FIELD_TB.F_IS_INDEX
     *
     * @mbggenerated
     */
    public String getfIsIndex() {
        return fIsIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_TABLE_FIELD_TB.F_IS_INDEX
     *
     * @param fIsIndex the value for SM_TABLE_FIELD_TB.F_IS_INDEX
     *
     * @mbggenerated
     */
    public void setfIsIndex(String fIsIndex) {
        this.fIsIndex = fIsIndex == null ? null : fIsIndex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_TABLE_FIELD_TB.INDEX_TYPE
     *
     * @return the value of SM_TABLE_FIELD_TB.INDEX_TYPE
     *
     * @mbggenerated
     */
    public String getIndexType() {
        return indexType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_TABLE_FIELD_TB.INDEX_TYPE
     *
     * @param indexType the value for SM_TABLE_FIELD_TB.INDEX_TYPE
     *
     * @mbggenerated
     */
    public void setIndexType(String indexType) {
        this.indexType = indexType == null ? null : indexType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_TABLE_FIELD_TB.LOCATION
     *
     * @return the value of SM_TABLE_FIELD_TB.LOCATION
     *
     * @mbggenerated
     */
    public Short getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_TABLE_FIELD_TB.LOCATION
     *
     * @param location the value for SM_TABLE_FIELD_TB.LOCATION
     *
     * @mbggenerated
     */
    public void setLocation(Short location) {
        this.location = location;
    }
}