package com.sunyard.ars.system.bean.sc;

import java.math.BigDecimal;

public class VoucherInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_VOUCHER_INFO_TB.VOUCHER_ID
     *
     * @mbggenerated
     */
    private BigDecimal voucherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_VOUCHER_INFO_TB.VOUCHER_NUMBER
     *
     * @mbggenerated
     */
    private BigDecimal voucherNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_VOUCHER_INFO_TB.VOUCHER_NAME
     *
     * @mbggenerated
     */
    private String voucherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_VOUCHER_INFO_TB.P_FOLDER_ID
     *
     * @mbggenerated
     */
    private BigDecimal pFolderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_VOUCHER_INFO_TB.VOUCHER_ID
     *
     * @return the value of SM_VOUCHER_INFO_TB.VOUCHER_ID
     *
     * @mbggenerated
     */
    public BigDecimal getVoucherId() {
        return voucherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_VOUCHER_INFO_TB.VOUCHER_ID
     *
     * @param voucherId the value for SM_VOUCHER_INFO_TB.VOUCHER_ID
     *
     * @mbggenerated
     */
    public void setVoucherId(BigDecimal voucherId) {
        this.voucherId = voucherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_VOUCHER_INFO_TB.VOUCHER_NUMBER
     *
     * @return the value of SM_VOUCHER_INFO_TB.VOUCHER_NUMBER
     *
     * @mbggenerated
     */
    public BigDecimal getVoucherNumber() {
        return voucherNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_VOUCHER_INFO_TB.VOUCHER_NUMBER
     *
     * @param voucherNumber the value for SM_VOUCHER_INFO_TB.VOUCHER_NUMBER
     *
     * @mbggenerated
     */
    public void setVoucherNumber(BigDecimal voucherNumber) {
        this.voucherNumber = voucherNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_VOUCHER_INFO_TB.VOUCHER_NAME
     *
     * @return the value of SM_VOUCHER_INFO_TB.VOUCHER_NAME
     *
     * @mbggenerated
     */
    public String getVoucherName() {
        return voucherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_VOUCHER_INFO_TB.VOUCHER_NAME
     *
     * @param voucherName the value for SM_VOUCHER_INFO_TB.VOUCHER_NAME
     *
     * @mbggenerated
     */
    public void setVoucherName(String voucherName) {
        this.voucherName = voucherName == null ? null : voucherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_VOUCHER_INFO_TB.P_FOLDER_ID
     *
     * @return the value of SM_VOUCHER_INFO_TB.P_FOLDER_ID
     *
     * @mbggenerated
     */
    public BigDecimal getpFolderId() {
        return pFolderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_VOUCHER_INFO_TB.P_FOLDER_ID
     *
     * @param pFolderId the value for SM_VOUCHER_INFO_TB.P_FOLDER_ID
     *
     * @mbggenerated
     */
    public void setpFolderId(BigDecimal pFolderId) {
        this.pFolderId = pFolderId;
    }
}