package com.sunyard.ars.system.pojo.mc;

public class LabExhibitField {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_EXHIBIT_FIELD_TB.ID
     *
     * @mbg.generated
     */
    private int id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_EXHIBIT_FIELD_TB.ROWNO
     *
     * @mbg.generated
     */
    private int rowno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_EXHIBIT_FIELD_TB.MODEL_ID
     *
     * @mbg.generated
     */
    private int modelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_EXHIBIT_FIELD_TB.TABLE_FIELD_ID
     *
     * @mbg.generated
     */
    private int tableFieldId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_EXHIBIT_FIELD_TB.FORMAT
     *
     * @mbg.generated
     */
    private String format;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_EXHIBIT_FIELD_TB.ISFIND
     *
     * @mbg.generated
     */
    private String isfind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_EXHIBIT_FIELD_TB.ISDROPDOWN
     *
     * @mbg.generated
     */
    private String isdropdown;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_EXHIBIT_FIELD_TB.ISIMPORTANT
     *
     * @mbg.generated
     */
    private String isimportant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_EXHIBIT_FIELD_TB.RELATE_ID
     *
     * @mbg.generated
     */
    private int relateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_EXHIBIT_FIELD_TB.OPERATOR
     *
     * @mbg.generated
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_EXHIBIT_FIELD_TB.EXHIBIT_NAME
     *
     * @mbg.generated
     */
    private String exhibitName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_EXHIBIT_FIELD_TB.FILTER_TYPE
     *
     * @mbg.generated
     */
    private String filterType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_EXHIBIT_FIELD_TB.ISTUOMIN
     *
     * @mbg.generated
     */
    private String istuomin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_EXHIBIT_FIELD_TB.ISPICTUREFIELD
     *
     * @mbg.generated
     */
    private String ispicturefield;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_EXHIBIT_FIELD_TB.ID
     *
     * @return the value of LAB_EXHIBIT_FIELD_TB.ID
     *
     * @mbg.generated
     */
    public int getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_EXHIBIT_FIELD_TB.ID
     *
     * @param id the value for LAB_EXHIBIT_FIELD_TB.ID
     *
     * @mbg.generated
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_EXHIBIT_FIELD_TB.ROWNO
     *
     * @return the value of LAB_EXHIBIT_FIELD_TB.ROWNO
     *
     * @mbg.generated
     */
    public int getRowno() {
        return rowno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_EXHIBIT_FIELD_TB.ROWNO
     *
     * @param rowno the value for LAB_EXHIBIT_FIELD_TB.ROWNO
     *
     * @mbg.generated
     */
    public void setRowno(int rowno) {
        this.rowno = rowno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_EXHIBIT_FIELD_TB.MODEL_ID
     *
     * @return the value of LAB_EXHIBIT_FIELD_TB.MODEL_ID
     *
     * @mbg.generated
     */
    public int getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_EXHIBIT_FIELD_TB.MODEL_ID
     *
     * @param modelId the value for LAB_EXHIBIT_FIELD_TB.MODEL_ID
     *
     * @mbg.generated
     */
    public void setModelId(int modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_EXHIBIT_FIELD_TB.TABLE_FIELD_ID
     *
     * @return the value of LAB_EXHIBIT_FIELD_TB.TABLE_FIELD_ID
     *
     * @mbg.generated
     */
    public int getTableFieldId() {
        return tableFieldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_EXHIBIT_FIELD_TB.TABLE_FIELD_ID
     *
     * @param tableFieldId the value for LAB_EXHIBIT_FIELD_TB.TABLE_FIELD_ID
     *
     * @mbg.generated
     */
    public void setTableFieldId(int tableFieldId) {
        this.tableFieldId = tableFieldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_EXHIBIT_FIELD_TB.FORMAT
     *
     * @return the value of LAB_EXHIBIT_FIELD_TB.FORMAT
     *
     * @mbg.generated
     */
    public String getFormat() {
        return format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_EXHIBIT_FIELD_TB.FORMAT
     *
     * @param format the value for LAB_EXHIBIT_FIELD_TB.FORMAT
     *
     * @mbg.generated
     */
    public void setFormat(String format) {
        this.format = format == null ? null : format.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_EXHIBIT_FIELD_TB.ISFIND
     *
     * @return the value of LAB_EXHIBIT_FIELD_TB.ISFIND
     *
     * @mbg.generated
     */
    public String getIsfind() {
        return isfind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_EXHIBIT_FIELD_TB.ISFIND
     *
     * @param isfind the value for LAB_EXHIBIT_FIELD_TB.ISFIND
     *
     * @mbg.generated
     */
    public void setIsfind(String isfind) {
        this.isfind = isfind == null ? null : isfind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_EXHIBIT_FIELD_TB.ISDROPDOWN
     *
     * @return the value of LAB_EXHIBIT_FIELD_TB.ISDROPDOWN
     *
     * @mbg.generated
     */
    public String getIsdropdown() {
        return isdropdown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_EXHIBIT_FIELD_TB.ISDROPDOWN
     *
     * @param isdropdown the value for LAB_EXHIBIT_FIELD_TB.ISDROPDOWN
     *
     * @mbg.generated
     */
    public void setIsdropdown(String isdropdown) {
        this.isdropdown = isdropdown == null ? null : isdropdown.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_EXHIBIT_FIELD_TB.ISIMPORTANT
     *
     * @return the value of LAB_EXHIBIT_FIELD_TB.ISIMPORTANT
     *
     * @mbg.generated
     */
    public String getIsimportant() {
        return isimportant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_EXHIBIT_FIELD_TB.ISIMPORTANT
     *
     * @param isimportant the value for LAB_EXHIBIT_FIELD_TB.ISIMPORTANT
     *
     * @mbg.generated
     */
    public void setIsimportant(String isimportant) {
        this.isimportant = isimportant == null ? null : isimportant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_EXHIBIT_FIELD_TB.RELATE_ID
     *
     * @return the value of LAB_EXHIBIT_FIELD_TB.RELATE_ID
     *
     * @mbg.generated
     */
    public int getRelateId() {
        return relateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_EXHIBIT_FIELD_TB.RELATE_ID
     *
     * @param relateId the value for LAB_EXHIBIT_FIELD_TB.RELATE_ID
     *
     * @mbg.generated
     */
    public void setRelateId(int relateId) {
        this.relateId = relateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_EXHIBIT_FIELD_TB.OPERATOR
     *
     * @return the value of LAB_EXHIBIT_FIELD_TB.OPERATOR
     *
     * @mbg.generated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_EXHIBIT_FIELD_TB.OPERATOR
     *
     * @param operator the value for LAB_EXHIBIT_FIELD_TB.OPERATOR
     *
     * @mbg.generated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_EXHIBIT_FIELD_TB.EXHIBIT_NAME
     *
     * @return the value of LAB_EXHIBIT_FIELD_TB.EXHIBIT_NAME
     *
     * @mbg.generated
     */
    public String getExhibitName() {
        return exhibitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_EXHIBIT_FIELD_TB.EXHIBIT_NAME
     *
     * @param exhibitName the value for LAB_EXHIBIT_FIELD_TB.EXHIBIT_NAME
     *
     * @mbg.generated
     */
    public void setExhibitName(String exhibitName) {
        this.exhibitName = exhibitName == null ? null : exhibitName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_EXHIBIT_FIELD_TB.FILTER_TYPE
     *
     * @return the value of LAB_EXHIBIT_FIELD_TB.FILTER_TYPE
     *
     * @mbg.generated
     */
    public String getFilterType() {
        return filterType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_EXHIBIT_FIELD_TB.FILTER_TYPE
     *
     * @param filterType the value for LAB_EXHIBIT_FIELD_TB.FILTER_TYPE
     *
     * @mbg.generated
     */
    public void setFilterType(String filterType) {
        this.filterType = filterType == null ? null : filterType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_EXHIBIT_FIELD_TB.ISTUOMIN
     *
     * @return the value of LAB_EXHIBIT_FIELD_TB.ISTUOMIN
     *
     * @mbg.generated
     */
    public String getIstuomin() {
        return istuomin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_EXHIBIT_FIELD_TB.ISTUOMIN
     *
     * @param istuomin the value for LAB_EXHIBIT_FIELD_TB.ISTUOMIN
     *
     * @mbg.generated
     */
    public void setIstuomin(String istuomin) {
        this.istuomin = istuomin == null ? null : istuomin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_EXHIBIT_FIELD_TB.ISPICTUREFIELD
     *
     * @return the value of LAB_EXHIBIT_FIELD_TB.ISPICTUREFIELD
     *
     * @mbg.generated
     */
    public String getIspicturefield() {
        return ispicturefield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_EXHIBIT_FIELD_TB.ISPICTUREFIELD
     *
     * @param ispicturefield the value for LAB_EXHIBIT_FIELD_TB.ISPICTUREFIELD
     *
     * @mbg.generated
     */
    public void setIspicturefield(String ispicturefield) {
        this.ispicturefield = ispicturefield == null ? null : ispicturefield.trim();
    }
}