package com.sunyard.ars.system.pojo.mc;


public class LabRule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_RULE_TB.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_RULE_TB.ROWNO
     *
     * @mbg.generated
     */
    private Integer rowno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_RULE_TB.MODEL_ID
     *
     * @mbg.generated
     */
    private Integer modelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_RULE_TB.VERSION_ID
     *
     * @mbg.generated
     */
    private Integer versionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_RULE_TB.TABLE_ID
     *
     * @mbg.generated
     */
    private Integer tableId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_RULE_TB.FIELD_NAME
     *
     * @mbg.generated
     */
    private Integer fieldId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_RULE_TB.OPERATOR
     *
     * @mbg.generated
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_RULE_TB.VALUE
     *
     * @mbg.generated
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_RULE_TB.REL_TABLE
     *
     * @mbg.generated
     */
    private Integer relTable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_RULE_TB.REL_FIELD
     *
     * @mbg.generated
     */
    private Integer relField;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAB_RULE_TB.COMPOSITE_TYPE
     *
     * @mbg.generated
     */
    private String compositeType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_RULE_TB.ID
     *
     * @return the value of LAB_RULE_TB.ID
     *
     * @mbg.generated
     */
    
    private String bracketLeft;
    
    private String bracketRight;
    
    
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_RULE_TB.ID
     *
     * @param id the value for LAB_RULE_TB.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_RULE_TB.ROWNO
     *
     * @return the value of LAB_RULE_TB.ROWNO
     *
     * @mbg.generated
     */
    public Integer getRowno() {
        return rowno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_RULE_TB.ROWNO
     *
     * @param rowno the value for LAB_RULE_TB.ROWNO
     *
     * @mbg.generated
     */
    public void setRowno(Integer rowno) {
        this.rowno = rowno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_RULE_TB.MODEL_ID
     *
     * @return the value of LAB_RULE_TB.MODEL_ID
     *
     * @mbg.generated
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_RULE_TB.MODEL_ID
     *
     * @param modelId the value for LAB_RULE_TB.MODEL_ID
     *
     * @mbg.generated
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_RULE_TB.VERSION_ID
     *
     * @return the value of LAB_RULE_TB.VERSION_ID
     *
     * @mbg.generated
     */
    public Integer getVersionId() {
        return versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_RULE_TB.VERSION_ID
     *
     * @param versionId the value for LAB_RULE_TB.VERSION_ID
     *
     * @mbg.generated
     */
    public void setVersionId(Integer versionId) {
        this.versionId = versionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_RULE_TB.TABLE_ID
     *
     * @return the value of LAB_RULE_TB.TABLE_ID
     *
     * @mbg.generated
     */
    public Integer getTableId() {
        return tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_RULE_TB.TABLE_ID
     *
     * @param tableId the value for LAB_RULE_TB.TABLE_ID
     *
     * @mbg.generated
     */
    public void setTableId(Integer tableId) {
        this.tableId = tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_RULE_TB.FIELD_NAME
     *
     * @return the value of LAB_RULE_TB.FIELD_NAME
     *
     * @mbg.generated
     */
    public Integer getFieldId() {
        return fieldId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_RULE_TB.FIELD_NAME
     *
     * @param fieldId the value for LAB_RULE_TB.FIELD_NAME
     *
     * @mbg.generated
     */
    public void setFieldId(Integer fieldId) {
        this.fieldId = fieldId ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_RULE_TB.OPERATOR
     *
     * @return the value of LAB_RULE_TB.OPERATOR
     *
     * @mbg.generated
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_RULE_TB.OPERATOR
     *
     * @param operator the value for LAB_RULE_TB.OPERATOR
     *
     * @mbg.generated
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_RULE_TB.VALUE
     *
     * @return the value of LAB_RULE_TB.VALUE
     *
     * @mbg.generated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_RULE_TB.VALUE
     *
     * @param value the value for LAB_RULE_TB.VALUE
     *
     * @mbg.generated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_RULE_TB.REL_TABLE
     *
     * @return the value of LAB_RULE_TB.REL_TABLE
     *
     * @mbg.generated
     */
    public Integer getRelTable() {
        return relTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_RULE_TB.REL_TABLE
     *
     * @param relTable the value for LAB_RULE_TB.REL_TABLE
     *
     * @mbg.generated
     */
    public void setRelTable(Integer relTable) {
        this.relTable = relTable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_RULE_TB.REL_FIELD
     *
     * @return the value of LAB_RULE_TB.REL_FIELD
     *
     * @mbg.generated
     */
    public Integer getRelField() {
        return relField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_RULE_TB.REL_FIELD
     *
     * @param relField the value for LAB_RULE_TB.REL_FIELD
     *
     * @mbg.generated
     */
    public void setRelField(Integer relField) {
        this.relField = relField ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAB_RULE_TB.COMPOSITE_TYPE
     *
     * @return the value of LAB_RULE_TB.COMPOSITE_TYPE
     *
     * @mbg.generated
     */
    public String getCompositeType() {
        return compositeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAB_RULE_TB.COMPOSITE_TYPE
     *
     * @param compositeType the value for LAB_RULE_TB.COMPOSITE_TYPE
     *
     * @mbg.generated
     */
    public void setCompositeType(String compositeType) {
        this.compositeType = compositeType == null ? null : compositeType.trim();
    }

	public String getBracketLeft() {
		return bracketLeft;
	}

	public void setBracketLeft(String bracketLeft) {
		this.bracketLeft = bracketLeft;
	}

	public String getBracketRight() {
		return bracketRight;
	}

	public void setBracketRight(String bracketRight) {
		this.bracketRight = bracketRight;
	}
    
    
}