package com.sunyard.ars.system.pojo.mc;

public class McModelLine {
	
    private Integer id;//模型号

    private Integer lineid;//管理模型号

    private String modelfiled;//模型字段

    private String linefiled;//管理模型字段

    private String filednumber;
    
    private String modelName;//管理模型名称

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_MODEL_LINE_TB.ID
     *
     * @param id the value for MC_MODEL_LINE_TB.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_MODEL_LINE_TB.LINEID
     *
     * @return the value of MC_MODEL_LINE_TB.LINEID
     *
     * @mbggenerated
     */
    public Integer getLineid() {
        return lineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_MODEL_LINE_TB.LINEID
     *
     * @param lineid the value for MC_MODEL_LINE_TB.LINEID
     *
     * @mbggenerated
     */
    public void setLineid(Integer lineid) {
        this.lineid = lineid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_MODEL_LINE_TB.MODELFILED
     *
     * @return the value of MC_MODEL_LINE_TB.MODELFILED
     *
     * @mbggenerated
     */
    public String getModelfiled() {
        return modelfiled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_MODEL_LINE_TB.MODELFILED
     *
     * @param modelfiled the value for MC_MODEL_LINE_TB.MODELFILED
     *
     * @mbggenerated
     */
    public void setModelfiled(String modelfiled) {
        this.modelfiled = modelfiled == null ? null : modelfiled.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_MODEL_LINE_TB.LINEFILED
     *
     * @return the value of MC_MODEL_LINE_TB.LINEFILED
     *
     * @mbggenerated
     */
    public String getLinefiled() {
        return linefiled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_MODEL_LINE_TB.LINEFILED
     *
     * @param linefiled the value for MC_MODEL_LINE_TB.LINEFILED
     *
     * @mbggenerated
     */
    public void setLinefiled(String linefiled) {
        this.linefiled = linefiled == null ? null : linefiled.trim();
    }

    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_MODEL_LINE_TB.LINEFILED
     *
     * @return the value of MC_MODEL_LINE_TB.LINEFILED
     *
     * @mbggenerated
     */
	public String getFilednumber() {
		return filednumber;
	}

	
	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_MODEL_LINE_TB.LINEFILED
     *
     * @param linefiled the value for MC_MODEL_LINE_TB.LINEFILED
     *
     * @mbggenerated
     */
	public void setFilednumber(String filednumber) {
		this.filednumber = filednumber == null ? null : filednumber.trim();
	}

	public String getModelName() {
		return modelName;
	}

	public void setModelName(String modelName) {
		this.modelName = modelName;
	}
}