package com.sunyard.ars.system.pojo.mc;

import java.math.BigDecimal;

public class ModelLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_BUSM_OPERLOG_TB.ID
     *
     * @mbggenerated
     */
	private int rowNum;
   

	private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_BUSM_OPERLOG_TB.OPERATOR_NO
     *
     * @mbggenerated
     */
    private String operatorNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_BUSM_OPERLOG_TB.OPER_TYPE
     *
     * @mbggenerated
     */
    private String operType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_BUSM_OPERLOG_TB.OPER_CONTENT
     *
     * @mbggenerated
     */
    private String operContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_BUSM_OPERLOG_TB.OPER_MODULE
     *
     * @mbggenerated
     */
    private String operModule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_BUSM_OPERLOG_TB.OPER_DATE
     *
     * @mbggenerated
     */
    private String operDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_BUSM_OPERLOG_TB.OPER_TIME
     *
     * @mbggenerated
     */
    private String operTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MC_BUSM_OPERLOG_TB.ENTRY_ID
     *
     * @mbggenerated
     */
    private String entryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_BUSM_OPERLOG_TB.ID
     *
     * @return the value of MC_BUSM_OPERLOG_TB.ID
     *
     * @mbggenerated
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_BUSM_OPERLOG_TB.ID
     *
     * @param id the value for MC_BUSM_OPERLOG_TB.ID
     *
     * @mbggenerated
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_BUSM_OPERLOG_TB.OPERATOR_NO
     *
     * @return the value of MC_BUSM_OPERLOG_TB.OPERATOR_NO
     *
     * @mbggenerated
     */
    public String getOperatorNo() {
        return operatorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_BUSM_OPERLOG_TB.OPERATOR_NO
     *
     * @param operatorNo the value for MC_BUSM_OPERLOG_TB.OPERATOR_NO
     *
     * @mbggenerated
     */
    public void setOperatorNo(String operatorNo) {
        this.operatorNo = operatorNo == null ? null : operatorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_BUSM_OPERLOG_TB.OPER_TYPE
     *
     * @return the value of MC_BUSM_OPERLOG_TB.OPER_TYPE
     *
     * @mbggenerated
     */
    public String getOperType() {
        return operType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_BUSM_OPERLOG_TB.OPER_TYPE
     *
     * @param operType the value for MC_BUSM_OPERLOG_TB.OPER_TYPE
     *
     * @mbggenerated
     */
    public void setOperType(String operType) {
        this.operType = operType == null ? null : operType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_BUSM_OPERLOG_TB.OPER_CONTENT
     *
     * @return the value of MC_BUSM_OPERLOG_TB.OPER_CONTENT
     *
     * @mbggenerated
     */
    public String getOperContent() {
        return operContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_BUSM_OPERLOG_TB.OPER_CONTENT
     *
     * @param operContent the value for MC_BUSM_OPERLOG_TB.OPER_CONTENT
     *
     * @mbggenerated
     */
    public void setOperContent(String operContent) {
        this.operContent = operContent == null ? null : operContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_BUSM_OPERLOG_TB.OPER_MODULE
     *
     * @return the value of MC_BUSM_OPERLOG_TB.OPER_MODULE
     *
     * @mbggenerated
     */
    public String getOperModule() {
        return operModule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_BUSM_OPERLOG_TB.OPER_MODULE
     *
     * @param operModule the value for MC_BUSM_OPERLOG_TB.OPER_MODULE
     *
     * @mbggenerated
     */
    public void setOperModule(String operModule) {
        this.operModule = operModule == null ? null : operModule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_BUSM_OPERLOG_TB.OPER_DATE
     *
     * @return the value of MC_BUSM_OPERLOG_TB.OPER_DATE
     *
     * @mbggenerated
     */
    public String getOperDate() {
        return operDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_BUSM_OPERLOG_TB.OPER_DATE
     *
     * @param operDate the value for MC_BUSM_OPERLOG_TB.OPER_DATE
     *
     * @mbggenerated
     */
    public void setOperDate(String operDate) {
        this.operDate = operDate == null ? null : operDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_BUSM_OPERLOG_TB.OPER_TIME
     *
     * @return the value of MC_BUSM_OPERLOG_TB.OPER_TIME
     *
     * @mbggenerated
     */
    public String getOperTime() {
        return operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_BUSM_OPERLOG_TB.OPER_TIME
     *
     * @param operTime the value for MC_BUSM_OPERLOG_TB.OPER_TIME
     *
     * @mbggenerated
     */
    public void setOperTime(String operTime) {
        this.operTime = operTime == null ? null : operTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MC_BUSM_OPERLOG_TB.ENTRY_ID
     *
     * @return the value of MC_BUSM_OPERLOG_TB.ENTRY_ID
     *
     * @mbggenerated
     */
    public String getEntryId() {
        return entryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MC_BUSM_OPERLOG_TB.ENTRY_ID
     *
     * @param entryId the value for MC_BUSM_OPERLOG_TB.ENTRY_ID
     *
     * @mbggenerated
     */
    public void setEntryId(String entryId) {
        this.entryId = entryId == null ? null : entryId.trim();
    }

	public int getRowNum() {
		return rowNum;
	}

	public void setRowNum(int rowNum) {
		this.rowNum = rowNum;
	}
    
}