package com.sunyard.ars.system.dao.mc;

import java.util.HashMap;
import java.util.List;

import com.sunyard.ars.system.pojo.mc.LabExhibitField;

public interface LabExhibitFieldMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAB_EXHIBIT_FIELD_TB
     *
     * @mbg.generated
     */
    int insert(LabExhibitField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAB_EXHIBIT_FIELD_TB
     *
     * @mbg.generated
     */
    int insertSelective(LabExhibitField record);
    
    /**
     * 获取展现字段信息
     * @param modelId
     * @return
     */
    List<HashMap<String,Object>> showExhibitField(int modelId);
}