package com.sunyard.ars.system.dao.mc;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.sunyard.ars.system.pojo.mc.LabMcVersion;

public interface LabMcVersionMapper {
	
	LabMcVersion selectByPrimaryKey(int id);
    
	/**
	 * 新增版本
	 * @param record
	 * @return
	 */
    int insert(LabMcVersion version);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAB_MC_VERSION
     *
     * @mbggenerated
     */
    int insertSelective(LabMcVersion record);
    
	List selectBySelective(LabMcVersion labMcVersion);
    List selectByModelId(@Param("modelId")BigDecimal modelId);
    String selectByTableId(@Param("tableId")BigDecimal tableId);
    List queryDatas(@Param("tableName")String tableName,@Param("fieldNameList")List fieldNameList);
   // List getRules(@Param("modelId")int modelId,@Param("versionId")int versionId);
    void updateModelIdAndLabState(@Param("id")int id,@Param("modelId")int modelId,@Param("versionId")int versionId);

    

    /**
     * 根据modelName获取modelId
     * @param modelName
     * @return
     */
    Map<String,Object> selectByModelName(String modelName);
    
    /**
     * 新增版本，首次
     * @param version
     * @return
     */
    int insertNoModelId(LabMcVersion version);
    


    void insertExhibitField(@Param("modelId")int modelId,@Param("produceModelId")int id);
    

}