package com.sunyard.ars.system.dao.mc;

import com.sunyard.ars.system.pojo.mc.LabRule;
import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface LabRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAB_RULE_TB
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAB_RULE_TB
     *
     * @mbg.generated
     */
    int insert(LabRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAB_RULE_TB
     *
     * @mbg.generated
     */
    int insertSelective(LabRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAB_RULE_TB
     *
     * @mbg.generated
     */
    LabRule selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAB_RULE_TB
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LabRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAB_RULE_TB
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LabRule record);
    
    /**
     * 查询jobDate
     * @return
     */
    String queryJobDate();
    
    /**
     * 查询最大行号
     * @param tableName
     * @return
     */
    int queryMaxRowId(@Param("tableName")String tableName);
    
    List queryLabRule(LabRule labRule);
}