package com.sunyard.ars.system.dao.mc;

import com.sunyard.ars.system.pojo.mc.ModelLog;
import java.math.BigDecimal;
import java.util.List;

public interface ModelLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MC_BUSM_OPERLOG_TB
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MC_BUSM_OPERLOG_TB
     *
     * @mbggenerated
     */
    int insert(ModelLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MC_BUSM_OPERLOG_TB
     *
     * @mbggenerated
     */
    int insertSelective(ModelLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MC_BUSM_OPERLOG_TB
     *
     * @mbggenerated
     */
    ModelLog selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MC_BUSM_OPERLOG_TB
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ModelLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MC_BUSM_OPERLOG_TB
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ModelLog record);
    List<ModelLog> selectBySelective(ModelLog record);
}