package com.sunyard.ars.system.dao.et;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.sunyard.ars.system.bean.et.BusiForm;

public interface BusiFormMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ET_BUSIFORM_TB
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String formId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ET_BUSIFORM_TB
     *
     * @mbggenerated
     */
    int insertSelective(BusiForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ET_BUSIFORM_TB
     *
     * @mbggenerated
     */
    BusiForm selectByPrimaryKey(String formId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ET_BUSIFORM_TB
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BusiForm record);
    
    /**
     * 根据对象中非空条件查询
     * @param redord
     * @return
     */
    List<BusiForm> selectBySelective(@Param("busiForm")BusiForm redord, @Param("condition")Map<String, Object> condition);
    
    /**
     * 根据前缀获取当前最大处理单编号
     * @param formIdLike 前缀条件按
     * @return
     */
    String getMaxFormId(String formIdLike);

    /**
     * 获取菜单信息
     * @param menuId
     * @return
     */
	List<HashMap<String,Object>> getMenuList(@Param("menuClass") String menuId,@Param("userNo") String userNo,@Param("dbType")String dbType);

	/**
	 * 获取任务数量
	 * @param condMap
	 * @return
	 */
	int getTaskCount(HashMap<String,Object> condMap);
	
	/**
	 * 获取加锁信息
	 * @param condMap
	 * @return
	 */
	List<HashMap<String,Object>> selectLockInfo(HashMap<String,Object> condMap);

	/**
	 * 加锁方法
	 * @param condMap
	 * @return
	 */
	int lockTask(HashMap<String,Object> condMap);

	/**
	 * 获取参数日后的日期，跳过节假日
	 * @param day
	 * @return
	 */
	String selectWorkDate(@Param("day") int day,@Param("dbType")String dbType);
	/**
	 * 获取传统业务的信息
	 * @param busiNoCt
	 * @return
	 */
	List<HashMap<String,Object>> selectBusiInfo(String busiNoCt);

	/**
	 * 获取单据列表
	 * @param condMap
	 * @return
	 */
	List<BusiForm> getTaskList(HashMap<String,Object> condMap);

	/**
	 * 解锁
	 * @param formId
	 * @return
	 */
	int dropLock(String formId);

	/**
	 * 检查机构情况
	 * @param condMap
	 * @return
	 */
	int checkOrganNo(HashMap<String,Object> condMap);

	/**
	 * 更新逾期备注
	 * @param condMap
	 * @return
	 */
	int doOverdueRemark(HashMap<String,Object> condMap);

	/**
	 * 获取退回列表
	 * @param condMap
	 * @return
	 */
	List<BusiForm> getCorrBusiFormList(HashMap<String,Object> condMap);

	/**
	 * 检查是否转发
	 * @param condMap
	 * @return
	 */
	List<HashMap<String,Object>> checkToSlip(HashMap<String,Object> condMap);

	/**
	 * 查询逾期信息
	 * @param condMap
	 * @return
	 */
	List<BusiForm> getOverBusiFormList(HashMap<String,Object> condMap);

	/**
	 * 查询办结修改数据
	 * @param condMap
	 * @return
	 */
	List<BusiForm> getModifyBusiFormList(HashMap<String,Object> condMap);

	/**
	 * 获取办结修改节点
	 * @return
	 */
	List<HashMap<String,Object>> selectEndModify();
	
	/**
	 * 删除上传附件
	 * @param deleteBusiForm
	 * @return
	 */
	int deleteUploadFile(BusiForm deleteBusiForm);

	/**
	 * 获取逾期天数
	 * @param backDate
	 * @param endDate
	 * @return
	 */
	String getOverDurDays(@Param("backDate") String backDate,@Param("endDate") String endDate);

	String getOverDurDays1(@Param("backDate") String backDate);
	
	Map queryFlowNo(BusiForm busiformTb);
	
	
}