package com.sunyard.ars.system.dao.et;

import com.sunyard.ars.system.bean.et.EtEntryRisk;
import java.math.BigDecimal;

public interface EtEntryRiskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ET_ENTRY_RISK
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ET_ENTRY_RISK
     *
     * @mbg.generated
     */
    int insert(EtEntryRisk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ET_ENTRY_RISK
     *
     * @mbg.generated
     */
    int insertSelective(EtEntryRisk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ET_ENTRY_RISK
     *
     * @mbg.generated
     */
    EtEntryRisk selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ET_ENTRY_RISK
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EtEntryRisk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ET_ENTRY_RISK
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EtEntryRisk record);
}