package com.sunyard.ars.system.dao.et;

import com.sunyard.ars.system.bean.et.EtProcessTb;

import java.util.HashMap;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface EtProcessTbMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ET_PROCESS_TB
     *
     * @mbg.generated
     */
    int insertSelective(EtProcessTb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ET_PROCESS_TB
     *
     * @mbg.generated
     */
    List<EtProcessTb> selectByPrimaryKey(HashMap<String,Object> condMap);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ET_PROCESS_TB
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EtProcessTb record);

    /**
     * 获取处理节点信息
     * @param condMap
     * @return
     */
	List<EtProcessTb> getProcesses(HashMap<String,Object> condMap);

	/**
	 * 通过条件获取处理信息
	 * @param condMap
	 * @return
	 */
	List<EtProcessTb> getProcessByDealResult(HashMap<String,Object> condMap);

	/**
	 * 获取作业机构处理日期集合
	 * @param formId
	 * @return
	 */
	List<HashMap<String,Object>> getEtProcessTbForId(@Param("formId") String formId);
	
	/**
	 * 更新收回单据上一条记录的信息
	 * @param condMap
	 * @return
	 */
	int updateBackProcess(HashMap<String,Object> condMap);

	/**
	 * 获取节点的流程信息
	 * @param formId
	 * @param preNode
	 * @return
	 */
	List<EtProcessTb> getProcessByDoNode(@Param("formId")String formId, @Param("nodeNo")String preNode);

	/**
	 * 更新流程逾期信息
	 * @param formId
	 * @return
	 */
	int updateProcessOverInfo(@Param("formId")String formId);

	/**
	 * 流程逾期信息更新到单据表中
	 * @param formId
	 * @return
	 */
	int updateProcessOverToBusiform(@Param("formId")String formId);
}