package com.sunyard.ars.system.dao.et;

import java.util.HashMap;
import java.util.List;

import com.sunyard.ars.system.bean.et.EtRiskSourceDef;

public interface EtRiskSourceDefMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ET_RISK_SOURCE_DEF
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sourceNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ET_RISK_SOURCE_DEF
     *
     * @mbg.generated
     */
    int insert(EtRiskSourceDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ET_RISK_SOURCE_DEF
     *
     * @mbg.generated
     */
    int insertSelective(EtRiskSourceDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ET_RISK_SOURCE_DEF
     *
     * @mbg.generated
     */
    EtRiskSourceDef selectByPrimaryKey(String sourceNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ET_RISK_SOURCE_DEF
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EtRiskSourceDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ET_RISK_SOURCE_DEF
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EtRiskSourceDef record);

    /**
     * 
     * @param condMap
     * @return
     */
	List<EtRiskSourceDef> selectBySelective(HashMap<String, Object> condMap);

	/**
	 * 获取问题类型列表
	 * @return
	 */
	List<HashMap<String, Object>> selectSourceType();
	
	/**
	 * 获取风险驱动因素类型
	 * @param condMap
	 * @return
	 */
	List<HashMap<String, Object>> selectModelSourceType(HashMap<String, Object> condMap);
	
	/**
	 * 获取风险驱动因素
	 * @param condMap
	 * @return
	 */
	List<HashMap<String, Object>> selectModelSourceName(HashMap<String, Object> condMap);
}