package com.sunyard.ars.system.dao.busm;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sunyard.ars.system.bean.busm.SmUserModel;

public interface SmUserModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_USER_MODEL_TB
     *
     */
    int deleteByPrimaryKey(@Param("roleNo") String roleNo, @Param("modelId") String modelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_USER_MODEL_TB
     *
     */
    int insert(SmUserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_USER_MODEL_TB
     *
     */
    int insertSelective(SmUserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_USER_MODEL_TB
     *
     */
    SmUserModel selectByPrimaryKey(@Param("roleNo") String roleNo, @Param("modelId") String modelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_USER_MODEL_TB
     *
     */
    int updateByPrimaryKeySelective(SmUserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_USER_MODEL_TB
     *
     */
    int updateByPrimaryKey(SmUserModel record);

	List<SmUserModel> selectBySelective(SmUserModel qdUserLeave);

	void deleteByRoleNo(String roleNo);
}