package com.sunyard.ars.system.dao.busm;


import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.sunyard.ars.system.bean.busm.UserBean;

public interface UserDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUNAOS.SM_USERS_TB
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("userNo") String userNo, @Param("bankNo") String bankNo, @Param("systemNo") String systemNo, @Param("projectNo") String projectNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUNAOS.SM_USERS_TB
     *
     * @mbggenerated
     */
    int insert(UserBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUNAOS.SM_USERS_TB
     *
     * @mbggenerated
     */
    int insertSelective(UserBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUNAOS.SM_USERS_TB
     *
     * @mbggenerated
     */
    UserBean selectByPrimaryKey(@Param("userNo") String userNo, @Param("bankNo") String bankNo, @Param("systemNo") String systemNo, @Param("projectNo") String projectNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUNAOS.SM_USERS_TB
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUNAOS.SM_USERS_TB
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(UserBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUNAOS.SM_USERS_TB
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserBean record);
    
    /**
     * 根据User对象的非空属性查询。
     * @param redord
     * @return (不包含clob字段的User对象集合)
     */
    List<UserBean> selectWithoutClobBySelective(UserBean redord);
    
    /**
     * 根据用户号集合删除用户
     * @param userNoList
     * @return
     */
    int deleteByUserNoList(@Param("userNoList")List<String> userNoList);
    
    /**
     * 根据用户号集合重置用户密码
     * @param userNoList
     * @param password
     * @return
     */
    int resetPasswordByUserNoList(@Param("userNoList")List<String> userNoList, @Param("password")String password);

    /**
     * 通过用户编号获取用户信息
     * @param userNo
     * @return
     */
    UserBean selectUserInfo(@Param("userNo") String userNo);

	List<Map<String,Object>> selectUser(Map<String,Object> map);

	/**
	 * 检查用户密码是否正确
	 * @param userNo
	 * @param password
	 * @return
	 */
	int checkUser(@Param("userNo") String userNo,@Param("password") String password);

	/**
	 * 验证授权用户是否有权限
	 * @param userNo
	 * @return
	 */
	int checkGrantUser(@Param("userNo") String userNo,@Param("organNo") String organNo);
	
	/**
	 * 抄送时查询用户
	 * @param map
	 * @return
	 */
	List<UserBean> selectUserList(Map<String,Object> map);
	
	/**
	 * 
	 * @Description: 查询机构下角色为质检员的人员
	 * @param @param map
	 * @param @return   
	 * @return List<UserBean>  
	 * @throws
	 * @author zs
	 * @date 2018年11月5日
	 */
	List<UserBean> selectRoleByRoleNo(Map<String,Object> map);

	List<UserBean> selectBySelective(Map<String, Object> map);
	
	/**
	 * 系统监控查询用户树
	 * @param map
	 * @return
	 */
	List<HashMap> getUsersToApply(HashMap<String, Object> map);
}