package com.sunyard.ars.system.bean.et;

import java.math.BigDecimal;

public class SlipDef {

    private String slipNo; // 差错编号
    private String operationType; // 业务类别
    private String slipType;// 差错类型（归属）
    private String slipName;// 差错名称
    private String slipLevel; // 差错等级
    private String slipLevelText; // 差错级别(差错定义表中)中文描述，一般，较严重，严重
    private BigDecimal amerceMoney;// 处罚金额
    private BigDecimal amerceScore;// 处罚分数
    private String createDate;// 添加日期
    private String stopDate; // 停用日期
    private String activeFlag;// 是否启用
    private String belongFlag;// 适用范围（1差错；2提示；3通用）
    private String remark;// 修改备注记录
    private String businessAssociation;
    private String slipWorkType; //0-风险差错，1-质检差错
    

    public String getSlipWorkType() {
		return slipWorkType;
	}

	public void setSlipWorkType(String slipWorkType) {
		this.slipWorkType = slipWorkType;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_SLIP_DEF.SLIP_NO
     *
     * @return the value of ET_SLIP_DEF.SLIP_NO
     *
     * @mbggenerated
     */
    public String getSlipNo() {
        return slipNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_SLIP_DEF.SLIP_NO
     *
     * @param slipNo the value for ET_SLIP_DEF.SLIP_NO
     *
     * @mbggenerated
     */
    public void setSlipNo(String slipNo) {
        this.slipNo = slipNo == null ? null : slipNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_SLIP_DEF.SLIP_TYPE
     *
     * @return the value of ET_SLIP_DEF.SLIP_TYPE
     *
     * @mbggenerated
     */
    public String getSlipType() {
        return slipType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_SLIP_DEF.SLIP_TYPE
     *
     * @param slipType the value for ET_SLIP_DEF.SLIP_TYPE
     *
     * @mbggenerated
     */
    public void setSlipType(String slipType) {
        this.slipType = slipType == null ? null : slipType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_SLIP_DEF.SLIP_NAME
     *
     * @return the value of ET_SLIP_DEF.SLIP_NAME
     *
     * @mbggenerated
     */
    public String getSlipName() {
        return slipName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_SLIP_DEF.SLIP_NAME
     *
     * @param slipName the value for ET_SLIP_DEF.SLIP_NAME
     *
     * @mbggenerated
     */
    public void setSlipName(String slipName) {
        this.slipName = slipName == null ? null : slipName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_SLIP_DEF.SLIP_LEVEL
     *
     * @return the value of ET_SLIP_DEF.SLIP_LEVEL
     *
     * @mbggenerated
     */
    public String getSlipLevel() {
        return slipLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_SLIP_DEF.SLIP_LEVEL
     *
     * @param slipLevel the value for ET_SLIP_DEF.SLIP_LEVEL
     *
     * @mbggenerated
     */
    public void setSlipLevel(String slipLevel) {
        this.slipLevel = slipLevel == null ? null : slipLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_SLIP_DEF.AMERCE_MONEY
     *
     * @return the value of ET_SLIP_DEF.AMERCE_MONEY
     *
     * @mbggenerated
     */
    public BigDecimal getAmerceMoney() {
        return amerceMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_SLIP_DEF.AMERCE_MONEY
     *
     * @param amerceMoney the value for ET_SLIP_DEF.AMERCE_MONEY
     *
     * @mbggenerated
     */
    public void setAmerceMoney(BigDecimal amerceMoney) {
        this.amerceMoney = amerceMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_SLIP_DEF.AMERCE_SCORE
     *
     * @return the value of ET_SLIP_DEF.AMERCE_SCORE
     *
     * @mbggenerated
     */
    public BigDecimal getAmerceScore() {
        return amerceScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_SLIP_DEF.AMERCE_SCORE
     *
     * @param amerceScore the value for ET_SLIP_DEF.AMERCE_SCORE
     *
     * @mbggenerated
     */
    public void setAmerceScore(BigDecimal amerceScore) {
        this.amerceScore = amerceScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_SLIP_DEF.CREATE_DATE
     *
     * @return the value of ET_SLIP_DEF.CREATE_DATE
     *
     * @mbggenerated
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_SLIP_DEF.CREATE_DATE
     *
     * @param createDate the value for ET_SLIP_DEF.CREATE_DATE
     *
     * @mbggenerated
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate == null ? null : createDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_SLIP_DEF.STOP_DATE
     *
     * @return the value of ET_SLIP_DEF.STOP_DATE
     *
     * @mbggenerated
     */
    public String getStopDate() {
        return stopDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_SLIP_DEF.STOP_DATE
     *
     * @param stopDate the value for ET_SLIP_DEF.STOP_DATE
     *
     * @mbggenerated
     */
    public void setStopDate(String stopDate) {
        this.stopDate = stopDate == null ? null : stopDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_SLIP_DEF.ACTIVE_FLAG
     *
     * @return the value of ET_SLIP_DEF.ACTIVE_FLAG
     *
     * @mbggenerated
     */
    public String getActiveFlag() {
        return activeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_SLIP_DEF.ACTIVE_FLAG
     *
     * @param activeFlag the value for ET_SLIP_DEF.ACTIVE_FLAG
     *
     * @mbggenerated
     */
    public void setActiveFlag(String activeFlag) {
        this.activeFlag = activeFlag == null ? null : activeFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_SLIP_DEF.BELONG_FLAG
     *
     * @return the value of ET_SLIP_DEF.BELONG_FLAG
     *
     * @mbggenerated
     */
    public String getBelongFlag() {
        return belongFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_SLIP_DEF.BELONG_FLAG
     *
     * @param belongFlag the value for ET_SLIP_DEF.BELONG_FLAG
     *
     * @mbggenerated
     */
    public void setBelongFlag(String belongFlag) {
        this.belongFlag = belongFlag == null ? null : belongFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_SLIP_DEF.REMARK
     *
     * @return the value of ET_SLIP_DEF.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_SLIP_DEF.REMARK
     *
     * @param remark the value for ET_SLIP_DEF.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_SLIP_DEF.BUSINESS_ASSOCIATION
     *
     * @return the value of ET_SLIP_DEF.BUSINESS_ASSOCIATION
     *
     * @mbggenerated
     */
    public String getBusinessAssociation() {
        return businessAssociation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_SLIP_DEF.BUSINESS_ASSOCIATION
     *
     * @param businessAssociation the value for ET_SLIP_DEF.BUSINESS_ASSOCIATION
     *
     * @mbggenerated
     */
    public void setBusinessAssociation(String businessAssociation) {
        this.businessAssociation = businessAssociation == null ? null : businessAssociation.trim();
    }

	public String getOperationType() {
		return operationType;
	}

	public void setOperationType(String operationType) {
		this.operationType = operationType;
	}

	public String getSlipLevelText() {
		return slipLevelText;
	}

	public void setSlipLevelText(String slipLevelText) {
		this.slipLevelText = slipLevelText;
	}
    
    
}