package com.sunyard.ars.common.pojo;

public class Dictionary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_DICTIONARY_TB.FIELD_NAME
     *
     * @mbggenerated
     */
    private String fieldName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_DICTIONARY_TB.CODE
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_DICTIONARY_TB.CONTENT
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_DICTIONARY_TB.PARENT_FIELD_NAME
     *
     * @mbggenerated
     */
    private String parentFieldName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_DICTIONARY_TB.PARENT_FIELD_CODE
     *
     * @mbggenerated
     */
    private String parentFieldCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_DICTIONARY_TB.FIELD_NAME
     *
     * @return the value of SM_DICTIONARY_TB.FIELD_NAME
     *
     * @mbggenerated
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_DICTIONARY_TB.FIELD_NAME
     *
     * @param fieldName the value for SM_DICTIONARY_TB.FIELD_NAME
     *
     * @mbggenerated
     */
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName == null ? null : fieldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_DICTIONARY_TB.CODE
     *
     * @return the value of SM_DICTIONARY_TB.CODE
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_DICTIONARY_TB.CODE
     *
     * @param code the value for SM_DICTIONARY_TB.CODE
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_DICTIONARY_TB.CONTENT
     *
     * @return the value of SM_DICTIONARY_TB.CONTENT
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_DICTIONARY_TB.CONTENT
     *
     * @param content the value for SM_DICTIONARY_TB.CONTENT
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_DICTIONARY_TB.PARENT_FIELD_NAME
     *
     * @return the value of SM_DICTIONARY_TB.PARENT_FIELD_NAME
     *
     * @mbggenerated
     */
    public String getParentFieldName() {
        return parentFieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_DICTIONARY_TB.PARENT_FIELD_NAME
     *
     * @param parentFieldName the value for SM_DICTIONARY_TB.PARENT_FIELD_NAME
     *
     * @mbggenerated
     */
    public void setParentFieldName(String parentFieldName) {
        this.parentFieldName = parentFieldName == null ? null : parentFieldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_DICTIONARY_TB.PARENT_FIELD_CODE
     *
     * @return the value of SM_DICTIONARY_TB.PARENT_FIELD_CODE
     *
     * @mbggenerated
     */
    public String getParentFieldCode() {
        return parentFieldCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_DICTIONARY_TB.PARENT_FIELD_CODE
     *
     * @param parentFieldCode the value for SM_DICTIONARY_TB.PARENT_FIELD_CODE
     *
     * @mbggenerated
     */
    public void setParentFieldCode(String parentFieldCode) {
        this.parentFieldCode = parentFieldCode == null ? null : parentFieldCode.trim();
    }
}