package com.sunyard.ars.risk.dao.arms;

import com.sunyard.ars.risk.bean.arms.ArmsFavoriteTb;
import org.apache.ibatis.annotations.Param;

public interface ArmsFavoriteTbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMS_FAVORITE_TB
     *
     * @mbg.generated
     */
    int insert(ArmsFavoriteTb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ARMS_FAVORITE_TB
     *
     * @mbg.generated
     */
    int insertSelective(ArmsFavoriteTb record);

    /**
     * 查询是否入库
     * @param type
     * @param modelId
     * @param modelRowId
     * @param loginUserNo
     * @return
     */
    int checkFavorite(@Param("type") String type,
                      @Param("modelId")String modelId,
                      @Param("modelRowId")String modelRowId,
                      @Param("formId")String formId);
}