package com.sunyard.ars.system.bean.busm;

public class Teller {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_TELLER_TB.TELLER_NO
     *
     * @mbggenerated
     */
    private String tellerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_TELLER_TB.TELLER_NAME
     *
     * @mbggenerated
     */
    private String tellerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_TELLER_TB.TELLER_LEVEL
     *
     * @mbggenerated
     */
    private String tellerLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_TELLER_TB.TELLER_TYPE
     *
     * @mbggenerated
     */
    private String tellerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_TELLER_TB.PARENT_ORGAN
     *
     * @mbggenerated
     */
    private String parentOrgan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_TELLER_TB.TELLER_STATE
     *
     * @mbggenerated
     */
    private String tellerState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_TELLER_TB.TELLER_NO
     *
     * @return the value of SM_TELLER_TB.TELLER_NO
     *
     * @mbggenerated
     */
    public String getTellerNo() {
        return tellerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_TELLER_TB.TELLER_NO
     *
     * @param tellerNo the value for SM_TELLER_TB.TELLER_NO
     *
     * @mbggenerated
     */
    public void setTellerNo(String tellerNo) {
        this.tellerNo = tellerNo == null ? null : tellerNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_TELLER_TB.TELLER_NAME
     *
     * @return the value of SM_TELLER_TB.TELLER_NAME
     *
     * @mbggenerated
     */
    public String getTellerName() {
        return tellerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_TELLER_TB.TELLER_NAME
     *
     * @param tellerName the value for SM_TELLER_TB.TELLER_NAME
     *
     * @mbggenerated
     */
    public void setTellerName(String tellerName) {
        this.tellerName = tellerName == null ? null : tellerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_TELLER_TB.TELLER_LEVEL
     *
     * @return the value of SM_TELLER_TB.TELLER_LEVEL
     *
     * @mbggenerated
     */
    public String getTellerLevel() {
        return tellerLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_TELLER_TB.TELLER_LEVEL
     *
     * @param tellerLevel the value for SM_TELLER_TB.TELLER_LEVEL
     *
     * @mbggenerated
     */
    public void setTellerLevel(String tellerLevel) {
        this.tellerLevel = tellerLevel == null ? null : tellerLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_TELLER_TB.TELLER_TYPE
     *
     * @return the value of SM_TELLER_TB.TELLER_TYPE
     *
     * @mbggenerated
     */
    public String getTellerType() {
        return tellerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_TELLER_TB.TELLER_TYPE
     *
     * @param tellerType the value for SM_TELLER_TB.TELLER_TYPE
     *
     * @mbggenerated
     */
    public void setTellerType(String tellerType) {
        this.tellerType = tellerType == null ? null : tellerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_TELLER_TB.PARENT_ORGAN
     *
     * @return the value of SM_TELLER_TB.PARENT_ORGAN
     *
     * @mbggenerated
     */
    public String getParentOrgan() {
        return parentOrgan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_TELLER_TB.PARENT_ORGAN
     *
     * @param parentOrgan the value for SM_TELLER_TB.PARENT_ORGAN
     *
     * @mbggenerated
     */
    public void setParentOrgan(String parentOrgan) {
        this.parentOrgan = parentOrgan == null ? null : parentOrgan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_TELLER_TB.TELLER_STATE
     *
     * @return the value of SM_TELLER_TB.TELLER_STATE
     *
     * @mbggenerated
     */
    public String getTellerState() {
        return tellerState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_TELLER_TB.TELLER_STATE
     *
     * @param tellerState the value for SM_TELLER_TB.TELLER_STATE
     *
     * @mbggenerated
     */
    public void setTellerState(String tellerState) {
        this.tellerState = tellerState == null ? null : tellerState.trim();
    }
}