package com.sunyard.ars.system.bean.busm;

public class UserBean {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNAOS.SM_USERS_TB.USER_NO
     *
     * @mbggenerated
     */
    private String userNo;

    // 单一登录
    private String singleLogin;

    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNAOS.SM_USERS_TB.BANK_NO
     *
     * @mbggenerated
     */
    private String bankNo;
    
    private String mobile;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNAOS.SM_USERS_TB.SYSTEM_NO
     *
     * @mbggenerated
     */
    private String systemNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNAOS.SM_USERS_TB.PROJECT_NO
     *
     * @mbggenerated
     */
    private String projectNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNAOS.SM_USERS_TB.PASSWORD
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNAOS.SM_USERS_TB.ORGAN_NO
     *
     * @mbggenerated
     */
    private String organNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNAOS.SM_USERS_TB.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNAOS.SM_USERS_TB.USER_ENABLE
     *
     * @mbggenerated
     */
    private String userEnable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNAOS.SM_USERS_TB.TELLERLVL
     *
     * @mbggenerated
     */
    private String tellerlvl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNAOS.SM_USERS_TB.LOGIN_MODE
     *
     * @mbggenerated
     */
    private String loginMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNAOS.SM_USERS_TB.LOGIN_STATE
     *
     * @mbggenerated
     */
    private String loginState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNAOS.SM_USERS_TB.USER_STATUS
     *
     * @mbggenerated
     */
    private String userStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNAOS.SM_USERS_TB.LAST_LOGIN_TIME
     *
     * @mbggenerated
     */
    private String lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNAOS.SM_USERS_TB.LAST_LOGOUT_TIME
     *
     * @mbggenerated
     */
    private String lastLogoutTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNAOS.SM_USERS_TB.LAST_MODI_DATE
     *
     * @mbggenerated
     */
    private String lastModiDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNAOS.SM_USERS_TB.UNDERSIGNED
     *
     * @mbggenerated
     */
    private String undersigned;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNAOS.SM_USERS_TB.TERMINAL_IP
     *
     * @mbggenerated
     */
    private String terminalIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNAOS.SM_USERS_TB.TERMINAL_MAC
     *
     * @mbggenerated
     */
    private String terminalMac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNAOS.SM_USERS_TB.LOGIN_PC_SERVER
     *
     * @mbggenerated
     */
    private String loginPcServer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNAOS.SM_USERS_TB.LOGIN_MOBILE_SERVER
     *
     * @mbggenerated
     */
    private String loginMobileServer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SUNAOS.SM_USERS_TB.IMAGE
     *
     * @mbggenerated
     */
    private String image;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNAOS.SM_USERS_TB.USER_NO
     *
     * @return the value of SUNAOS.SM_USERS_TB.USER_NO
     *
     * @mbggenerated
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNAOS.SM_USERS_TB.USER_NO
     *
     * @param userNo the value for SUNAOS.SM_USERS_TB.USER_NO
     *
     * @mbggenerated
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo == null ? null : userNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNAOS.SM_USERS_TB.BANK_NO
     *
     * @return the value of SUNAOS.SM_USERS_TB.BANK_NO
     *
     * @mbggenerated
     */
    public String getBankNo() {
        return bankNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNAOS.SM_USERS_TB.BANK_NO
     *
     * @param bankNo the value for SUNAOS.SM_USERS_TB.BANK_NO
     *
     * @mbggenerated
     */
    public void setBankNo(String bankNo) {
        this.bankNo = bankNo == null ? null : bankNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNAOS.SM_USERS_TB.SYSTEM_NO
     *
     * @return the value of SUNAOS.SM_USERS_TB.SYSTEM_NO
     *
     * @mbggenerated
     */
    public String getSystemNo() {
        return systemNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNAOS.SM_USERS_TB.SYSTEM_NO
     *
     * @param systemNo the value for SUNAOS.SM_USERS_TB.SYSTEM_NO
     *
     * @mbggenerated
     */
    public void setSystemNo(String systemNo) {
        this.systemNo = systemNo == null ? null : systemNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNAOS.SM_USERS_TB.PROJECT_NO
     *
     * @return the value of SUNAOS.SM_USERS_TB.PROJECT_NO
     *
     * @mbggenerated
     */
    public String getProjectNo() {
        return projectNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNAOS.SM_USERS_TB.PROJECT_NO
     *
     * @param projectNo the value for SUNAOS.SM_USERS_TB.PROJECT_NO
     *
     * @mbggenerated
     */
    public void setProjectNo(String projectNo) {
        this.projectNo = projectNo == null ? null : projectNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNAOS.SM_USERS_TB.PASSWORD
     *
     * @return the value of SUNAOS.SM_USERS_TB.PASSWORD
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNAOS.SM_USERS_TB.PASSWORD
     *
     * @param password the value for SUNAOS.SM_USERS_TB.PASSWORD
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNAOS.SM_USERS_TB.ORGAN_NO
     *
     * @return the value of SUNAOS.SM_USERS_TB.ORGAN_NO
     *
     * @mbggenerated
     */
    public String getOrganNo() {
        return organNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNAOS.SM_USERS_TB.ORGAN_NO
     *
     * @param organNo the value for SUNAOS.SM_USERS_TB.ORGAN_NO
     *
     * @mbggenerated
     */
    public void setOrganNo(String organNo) {
        this.organNo = organNo == null ? null : organNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNAOS.SM_USERS_TB.USER_NAME
     *
     * @return the value of SUNAOS.SM_USERS_TB.USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNAOS.SM_USERS_TB.USER_NAME
     *
     * @param userName the value for SUNAOS.SM_USERS_TB.USER_NAME
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNAOS.SM_USERS_TB.USER_ENABLE
     *
     * @return the value of SUNAOS.SM_USERS_TB.USER_ENABLE
     *
     * @mbggenerated
     */
    public String getUserEnable() {
        return userEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNAOS.SM_USERS_TB.USER_ENABLE
     *
     * @param userEnable the value for SUNAOS.SM_USERS_TB.USER_ENABLE
     *
     * @mbggenerated
     */
    public void setUserEnable(String userEnable) {
        this.userEnable = userEnable == null ? null : userEnable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNAOS.SM_USERS_TB.TELLERLVL
     *
     * @return the value of SUNAOS.SM_USERS_TB.TELLERLVL
     *
     * @mbggenerated
     */
    public String getTellerlvl() {
        return tellerlvl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNAOS.SM_USERS_TB.TELLERLVL
     *
     * @param tellerlvl the value for SUNAOS.SM_USERS_TB.TELLERLVL
     *
     * @mbggenerated
     */
    public void setTellerlvl(String tellerlvl) {
        this.tellerlvl = tellerlvl == null ? null : tellerlvl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNAOS.SM_USERS_TB.LOGIN_MODE
     *
     * @return the value of SUNAOS.SM_USERS_TB.LOGIN_MODE
     *
     * @mbggenerated
     */
    public String getLoginMode() {
        return loginMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNAOS.SM_USERS_TB.LOGIN_MODE
     *
     * @param loginMode the value for SUNAOS.SM_USERS_TB.LOGIN_MODE
     *
     * @mbggenerated
     */
    public void setLoginMode(String loginMode) {
        this.loginMode = loginMode == null ? null : loginMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNAOS.SM_USERS_TB.LOGIN_STATE
     *
     * @return the value of SUNAOS.SM_USERS_TB.LOGIN_STATE
     *
     * @mbggenerated
     */
    public String getLoginState() {
        return loginState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNAOS.SM_USERS_TB.LOGIN_STATE
     *
     * @param loginState the value for SUNAOS.SM_USERS_TB.LOGIN_STATE
     *
     * @mbggenerated
     */
    public void setLoginState(String loginState) {
        this.loginState = loginState == null ? null : loginState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNAOS.SM_USERS_TB.USER_STATUS
     *
     * @return the value of SUNAOS.SM_USERS_TB.USER_STATUS
     *
     * @mbggenerated
     */
    public String getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNAOS.SM_USERS_TB.USER_STATUS
     *
     * @param userStatus the value for SUNAOS.SM_USERS_TB.USER_STATUS
     *
     * @mbggenerated
     */
    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus == null ? null : userStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNAOS.SM_USERS_TB.LAST_LOGIN_TIME
     *
     * @return the value of SUNAOS.SM_USERS_TB.LAST_LOGIN_TIME
     *
     * @mbggenerated
     */
    public String getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNAOS.SM_USERS_TB.LAST_LOGIN_TIME
     *
     * @param lastLoginTime the value for SUNAOS.SM_USERS_TB.LAST_LOGIN_TIME
     *
     * @mbggenerated
     */
    public void setLastLoginTime(String lastLoginTime) {
        this.lastLoginTime = lastLoginTime == null ? null : lastLoginTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNAOS.SM_USERS_TB.LAST_LOGOUT_TIME
     *
     * @return the value of SUNAOS.SM_USERS_TB.LAST_LOGOUT_TIME
     *
     * @mbggenerated
     */
    public String getLastLogoutTime() {
        return lastLogoutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNAOS.SM_USERS_TB.LAST_LOGOUT_TIME
     *
     * @param lastLogoutTime the value for SUNAOS.SM_USERS_TB.LAST_LOGOUT_TIME
     *
     * @mbggenerated
     */
    public void setLastLogoutTime(String lastLogoutTime) {
        this.lastLogoutTime = lastLogoutTime == null ? null : lastLogoutTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNAOS.SM_USERS_TB.LAST_MODI_DATE
     *
     * @return the value of SUNAOS.SM_USERS_TB.LAST_MODI_DATE
     *
     * @mbggenerated
     */
    public String getLastModiDate() {
        return lastModiDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNAOS.SM_USERS_TB.LAST_MODI_DATE
     *
     * @param lastModiDate the value for SUNAOS.SM_USERS_TB.LAST_MODI_DATE
     *
     * @mbggenerated
     */
    public void setLastModiDate(String lastModiDate) {
        this.lastModiDate = lastModiDate == null ? null : lastModiDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNAOS.SM_USERS_TB.UNDERSIGNED
     *
     * @return the value of SUNAOS.SM_USERS_TB.UNDERSIGNED
     *
     * @mbggenerated
     */
    public String getUndersigned() {
        return undersigned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNAOS.SM_USERS_TB.UNDERSIGNED
     *
     * @param undersigned the value for SUNAOS.SM_USERS_TB.UNDERSIGNED
     *
     * @mbggenerated
     */
    public void setUndersigned(String undersigned) {
        this.undersigned = undersigned == null ? null : undersigned.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNAOS.SM_USERS_TB.TERMINAL_IP
     *
     * @return the value of SUNAOS.SM_USERS_TB.TERMINAL_IP
     *
     * @mbggenerated
     */
    public String getTerminalIp() {
        return terminalIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNAOS.SM_USERS_TB.TERMINAL_IP
     *
     * @param terminalIp the value for SUNAOS.SM_USERS_TB.TERMINAL_IP
     *
     * @mbggenerated
     */
    public void setTerminalIp(String terminalIp) {
        this.terminalIp = terminalIp == null ? null : terminalIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNAOS.SM_USERS_TB.TERMINAL_MAC
     *
     * @return the value of SUNAOS.SM_USERS_TB.TERMINAL_MAC
     *
     * @mbggenerated
     */
    public String getTerminalMac() {
        return terminalMac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNAOS.SM_USERS_TB.TERMINAL_MAC
     *
     * @param terminalMac the value for SUNAOS.SM_USERS_TB.TERMINAL_MAC
     *
     * @mbggenerated
     */
    public void setTerminalMac(String terminalMac) {
        this.terminalMac = terminalMac == null ? null : terminalMac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNAOS.SM_USERS_TB.LOGIN_PC_SERVER
     *
     * @return the value of SUNAOS.SM_USERS_TB.LOGIN_PC_SERVER
     *
     * @mbggenerated
     */
    public String getLoginPcServer() {
        return loginPcServer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNAOS.SM_USERS_TB.LOGIN_PC_SERVER
     *
     * @param loginPcServer the value for SUNAOS.SM_USERS_TB.LOGIN_PC_SERVER
     *
     * @mbggenerated
     */
    public void setLoginPcServer(String loginPcServer) {
        this.loginPcServer = loginPcServer == null ? null : loginPcServer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNAOS.SM_USERS_TB.LOGIN_MOBILE_SERVER
     *
     * @return the value of SUNAOS.SM_USERS_TB.LOGIN_MOBILE_SERVER
     *
     * @mbggenerated
     */
    public String getLoginMobileServer() {
        return loginMobileServer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNAOS.SM_USERS_TB.LOGIN_MOBILE_SERVER
     *
     * @param loginMobileServer the value for SUNAOS.SM_USERS_TB.LOGIN_MOBILE_SERVER
     *
     * @mbggenerated
     */
    public void setLoginMobileServer(String loginMobileServer) {
        this.loginMobileServer = loginMobileServer == null ? null : loginMobileServer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SUNAOS.SM_USERS_TB.IMAGE
     *
     * @return the value of SUNAOS.SM_USERS_TB.IMAGE
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SUNAOS.SM_USERS_TB.IMAGE
     *
     * @param image the value for SUNAOS.SM_USERS_TB.IMAGE
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getRoleName() {
		return roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

    public String getSingleLogin() {
        return singleLogin;
    }
    public void setSingleLogin(String singleLogin) {
        this.singleLogin = singleLogin;
    }
}