package com.sunyard.ars.system.bean.hx;

import java.math.BigDecimal;

public class AdFavorite {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.FORM_ID
     *
     * @mbggenerated
     */
    private String formId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.RISK_TYPE_ID
     *
     * @mbggenerated
     */
    private String riskTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.RISK_TYPE_NAME
     *
     * @mbggenerated
     */
    private String riskTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.ORGAN_NO
     *
     * @mbggenerated
     */
    private String organNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.ORGAN_NAME
     *
     * @mbggenerated
     */
    private String organName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.TRANS_DATE
     *
     * @mbggenerated
     */
    private String transDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.TRANS_TIME
     *
     * @mbggenerated
     */
    private String transTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.CUST_NO
     *
     * @mbggenerated
     */
    private String custNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.CUST_NAME
     *
     * @mbggenerated
     */
    private String custName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.ACCT_NO
     *
     * @mbggenerated
     */
    private String acctNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.ACCT_NAME
     *
     * @mbggenerated
     */
    private String acctName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.PRIM_AO_NO
     *
     * @mbggenerated
     */
    private String primAoNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.PRIM_AO_NAME
     *
     * @mbggenerated
     */
    private String primAoName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.ADVS_CUST_NO
     *
     * @mbggenerated
     */
    private String advsCustNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.ADVS_CUST_NANME
     *
     * @mbggenerated
     */
    private String advsCustNanme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.ADVS_ACCT_NO
     *
     * @mbggenerated
     */
    private String advsAcctNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.ADVS_ACCT_NAME
     *
     * @mbggenerated
     */
    private String advsAcctName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.TELLER_NO
     *
     * @mbggenerated
     */
    private String tellerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.TELLER_NAME
     *
     * @mbggenerated
     */
    private String tellerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.TELLER_NO1
     *
     * @mbggenerated
     */
    private String tellerNo1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.TELLER_NAME1
     *
     * @mbggenerated
     */
    private String tellerName1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.TX_CODE
     *
     * @mbggenerated
     */
    private String txCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.TX_NAME
     *
     * @mbggenerated
     */
    private String txName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.FLOW_ID
     *
     * @mbggenerated
     */
    private String flowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.CD_FLAG
     *
     * @mbggenerated
     */
    private String cdFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.CURRENCY
     *
     * @mbggenerated
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.TRANS_AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal transAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.EVENT_AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal eventAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.LOST_AMOUNT
     *
     * @mbggenerated
     */
    private BigDecimal lostAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.EVENT_CONTEXT
     *
     * @mbggenerated
     */
    private String eventContext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.DEAL_DESCRIPTION
     *
     * @mbggenerated
     */
    private String dealDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.RISK_CONTEXT
     *
     * @mbggenerated
     */
    private String riskContext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.WARN_ID
     *
     * @mbggenerated
     */
    private String warnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.ADD_USER
     *
     * @mbggenerated
     */
    private String addUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.ADD_TIME
     *
     * @mbggenerated
     */
    private String addTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.ADD_REMARK
     *
     * @mbggenerated
     */
    private String addRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.STATUS
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.IS_SHARE
     *
     * @mbggenerated
     */
    private String isShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AD_FAVORITE_TB.BANK_CODE
     *
     * @mbggenerated
     */
    private String bankCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.FORM_ID
     *
     * @return the value of AD_FAVORITE_TB.FORM_ID
     *
     * @mbggenerated
     */
    public String getFormId() {
        return formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.FORM_ID
     *
     * @param formId the value for AD_FAVORITE_TB.FORM_ID
     *
     * @mbggenerated
     */
    public void setFormId(String formId) {
        this.formId = formId == null ? null : formId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.RISK_TYPE_ID
     *
     * @return the value of AD_FAVORITE_TB.RISK_TYPE_ID
     *
     * @mbggenerated
     */
    public String getRiskTypeId() {
        return riskTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.RISK_TYPE_ID
     *
     * @param riskTypeId the value for AD_FAVORITE_TB.RISK_TYPE_ID
     *
     * @mbggenerated
     */
    public void setRiskTypeId(String riskTypeId) {
        this.riskTypeId = riskTypeId == null ? null : riskTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.RISK_TYPE_NAME
     *
     * @return the value of AD_FAVORITE_TB.RISK_TYPE_NAME
     *
     * @mbggenerated
     */
    public String getRiskTypeName() {
        return riskTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.RISK_TYPE_NAME
     *
     * @param riskTypeName the value for AD_FAVORITE_TB.RISK_TYPE_NAME
     *
     * @mbggenerated
     */
    public void setRiskTypeName(String riskTypeName) {
        this.riskTypeName = riskTypeName == null ? null : riskTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.ORGAN_NO
     *
     * @return the value of AD_FAVORITE_TB.ORGAN_NO
     *
     * @mbggenerated
     */
    public String getOrganNo() {
        return organNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.ORGAN_NO
     *
     * @param organNo the value for AD_FAVORITE_TB.ORGAN_NO
     *
     * @mbggenerated
     */
    public void setOrganNo(String organNo) {
        this.organNo = organNo == null ? null : organNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.ORGAN_NAME
     *
     * @return the value of AD_FAVORITE_TB.ORGAN_NAME
     *
     * @mbggenerated
     */
    public String getOrganName() {
        return organName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.ORGAN_NAME
     *
     * @param organName the value for AD_FAVORITE_TB.ORGAN_NAME
     *
     * @mbggenerated
     */
    public void setOrganName(String organName) {
        this.organName = organName == null ? null : organName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.TRANS_DATE
     *
     * @return the value of AD_FAVORITE_TB.TRANS_DATE
     *
     * @mbggenerated
     */
    public String getTransDate() {
        return transDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.TRANS_DATE
     *
     * @param transDate the value for AD_FAVORITE_TB.TRANS_DATE
     *
     * @mbggenerated
     */
    public void setTransDate(String transDate) {
        this.transDate = transDate == null ? null : transDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.TRANS_TIME
     *
     * @return the value of AD_FAVORITE_TB.TRANS_TIME
     *
     * @mbggenerated
     */
    public String getTransTime() {
        return transTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.TRANS_TIME
     *
     * @param transTime the value for AD_FAVORITE_TB.TRANS_TIME
     *
     * @mbggenerated
     */
    public void setTransTime(String transTime) {
        this.transTime = transTime == null ? null : transTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.CUST_NO
     *
     * @return the value of AD_FAVORITE_TB.CUST_NO
     *
     * @mbggenerated
     */
    public String getCustNo() {
        return custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.CUST_NO
     *
     * @param custNo the value for AD_FAVORITE_TB.CUST_NO
     *
     * @mbggenerated
     */
    public void setCustNo(String custNo) {
        this.custNo = custNo == null ? null : custNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.CUST_NAME
     *
     * @return the value of AD_FAVORITE_TB.CUST_NAME
     *
     * @mbggenerated
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.CUST_NAME
     *
     * @param custName the value for AD_FAVORITE_TB.CUST_NAME
     *
     * @mbggenerated
     */
    public void setCustName(String custName) {
        this.custName = custName == null ? null : custName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.ACCT_NO
     *
     * @return the value of AD_FAVORITE_TB.ACCT_NO
     *
     * @mbggenerated
     */
    public String getAcctNo() {
        return acctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.ACCT_NO
     *
     * @param acctNo the value for AD_FAVORITE_TB.ACCT_NO
     *
     * @mbggenerated
     */
    public void setAcctNo(String acctNo) {
        this.acctNo = acctNo == null ? null : acctNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.ACCT_NAME
     *
     * @return the value of AD_FAVORITE_TB.ACCT_NAME
     *
     * @mbggenerated
     */
    public String getAcctName() {
        return acctName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.ACCT_NAME
     *
     * @param acctName the value for AD_FAVORITE_TB.ACCT_NAME
     *
     * @mbggenerated
     */
    public void setAcctName(String acctName) {
        this.acctName = acctName == null ? null : acctName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.PRIM_AO_NO
     *
     * @return the value of AD_FAVORITE_TB.PRIM_AO_NO
     *
     * @mbggenerated
     */
    public String getPrimAoNo() {
        return primAoNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.PRIM_AO_NO
     *
     * @param primAoNo the value for AD_FAVORITE_TB.PRIM_AO_NO
     *
     * @mbggenerated
     */
    public void setPrimAoNo(String primAoNo) {
        this.primAoNo = primAoNo == null ? null : primAoNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.PRIM_AO_NAME
     *
     * @return the value of AD_FAVORITE_TB.PRIM_AO_NAME
     *
     * @mbggenerated
     */
    public String getPrimAoName() {
        return primAoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.PRIM_AO_NAME
     *
     * @param primAoName the value for AD_FAVORITE_TB.PRIM_AO_NAME
     *
     * @mbggenerated
     */
    public void setPrimAoName(String primAoName) {
        this.primAoName = primAoName == null ? null : primAoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.ADVS_CUST_NO
     *
     * @return the value of AD_FAVORITE_TB.ADVS_CUST_NO
     *
     * @mbggenerated
     */
    public String getAdvsCustNo() {
        return advsCustNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.ADVS_CUST_NO
     *
     * @param advsCustNo the value for AD_FAVORITE_TB.ADVS_CUST_NO
     *
     * @mbggenerated
     */
    public void setAdvsCustNo(String advsCustNo) {
        this.advsCustNo = advsCustNo == null ? null : advsCustNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.ADVS_CUST_NANME
     *
     * @return the value of AD_FAVORITE_TB.ADVS_CUST_NANME
     *
     * @mbggenerated
     */
    public String getAdvsCustNanme() {
        return advsCustNanme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.ADVS_CUST_NANME
     *
     * @param advsCustNanme the value for AD_FAVORITE_TB.ADVS_CUST_NANME
     *
     * @mbggenerated
     */
    public void setAdvsCustNanme(String advsCustNanme) {
        this.advsCustNanme = advsCustNanme == null ? null : advsCustNanme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.ADVS_ACCT_NO
     *
     * @return the value of AD_FAVORITE_TB.ADVS_ACCT_NO
     *
     * @mbggenerated
     */
    public String getAdvsAcctNo() {
        return advsAcctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.ADVS_ACCT_NO
     *
     * @param advsAcctNo the value for AD_FAVORITE_TB.ADVS_ACCT_NO
     *
     * @mbggenerated
     */
    public void setAdvsAcctNo(String advsAcctNo) {
        this.advsAcctNo = advsAcctNo == null ? null : advsAcctNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.ADVS_ACCT_NAME
     *
     * @return the value of AD_FAVORITE_TB.ADVS_ACCT_NAME
     *
     * @mbggenerated
     */
    public String getAdvsAcctName() {
        return advsAcctName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.ADVS_ACCT_NAME
     *
     * @param advsAcctName the value for AD_FAVORITE_TB.ADVS_ACCT_NAME
     *
     * @mbggenerated
     */
    public void setAdvsAcctName(String advsAcctName) {
        this.advsAcctName = advsAcctName == null ? null : advsAcctName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.TELLER_NO
     *
     * @return the value of AD_FAVORITE_TB.TELLER_NO
     *
     * @mbggenerated
     */
    public String getTellerNo() {
        return tellerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.TELLER_NO
     *
     * @param tellerNo the value for AD_FAVORITE_TB.TELLER_NO
     *
     * @mbggenerated
     */
    public void setTellerNo(String tellerNo) {
        this.tellerNo = tellerNo == null ? null : tellerNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.TELLER_NAME
     *
     * @return the value of AD_FAVORITE_TB.TELLER_NAME
     *
     * @mbggenerated
     */
    public String getTellerName() {
        return tellerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.TELLER_NAME
     *
     * @param tellerName the value for AD_FAVORITE_TB.TELLER_NAME
     *
     * @mbggenerated
     */
    public void setTellerName(String tellerName) {
        this.tellerName = tellerName == null ? null : tellerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.TELLER_NO1
     *
     * @return the value of AD_FAVORITE_TB.TELLER_NO1
     *
     * @mbggenerated
     */
    public String getTellerNo1() {
        return tellerNo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.TELLER_NO1
     *
     * @param tellerNo1 the value for AD_FAVORITE_TB.TELLER_NO1
     *
     * @mbggenerated
     */
    public void setTellerNo1(String tellerNo1) {
        this.tellerNo1 = tellerNo1 == null ? null : tellerNo1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.TELLER_NAME1
     *
     * @return the value of AD_FAVORITE_TB.TELLER_NAME1
     *
     * @mbggenerated
     */
    public String getTellerName1() {
        return tellerName1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.TELLER_NAME1
     *
     * @param tellerName1 the value for AD_FAVORITE_TB.TELLER_NAME1
     *
     * @mbggenerated
     */
    public void setTellerName1(String tellerName1) {
        this.tellerName1 = tellerName1 == null ? null : tellerName1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.TX_CODE
     *
     * @return the value of AD_FAVORITE_TB.TX_CODE
     *
     * @mbggenerated
     */
    public String getTxCode() {
        return txCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.TX_CODE
     *
     * @param txCode the value for AD_FAVORITE_TB.TX_CODE
     *
     * @mbggenerated
     */
    public void setTxCode(String txCode) {
        this.txCode = txCode == null ? null : txCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.TX_NAME
     *
     * @return the value of AD_FAVORITE_TB.TX_NAME
     *
     * @mbggenerated
     */
    public String getTxName() {
        return txName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.TX_NAME
     *
     * @param txName the value for AD_FAVORITE_TB.TX_NAME
     *
     * @mbggenerated
     */
    public void setTxName(String txName) {
        this.txName = txName == null ? null : txName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.FLOW_ID
     *
     * @return the value of AD_FAVORITE_TB.FLOW_ID
     *
     * @mbggenerated
     */
    public String getFlowId() {
        return flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.FLOW_ID
     *
     * @param flowId the value for AD_FAVORITE_TB.FLOW_ID
     *
     * @mbggenerated
     */
    public void setFlowId(String flowId) {
        this.flowId = flowId == null ? null : flowId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.CD_FLAG
     *
     * @return the value of AD_FAVORITE_TB.CD_FLAG
     *
     * @mbggenerated
     */
    public String getCdFlag() {
        return cdFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.CD_FLAG
     *
     * @param cdFlag the value for AD_FAVORITE_TB.CD_FLAG
     *
     * @mbggenerated
     */
    public void setCdFlag(String cdFlag) {
        this.cdFlag = cdFlag == null ? null : cdFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.CURRENCY
     *
     * @return the value of AD_FAVORITE_TB.CURRENCY
     *
     * @mbggenerated
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.CURRENCY
     *
     * @param currency the value for AD_FAVORITE_TB.CURRENCY
     *
     * @mbggenerated
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.TRANS_AMOUNT
     *
     * @return the value of AD_FAVORITE_TB.TRANS_AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getTransAmount() {
        return transAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.TRANS_AMOUNT
     *
     * @param transAmount the value for AD_FAVORITE_TB.TRANS_AMOUNT
     *
     * @mbggenerated
     */
    public void setTransAmount(BigDecimal transAmount) {
        this.transAmount = transAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.EVENT_AMOUNT
     *
     * @return the value of AD_FAVORITE_TB.EVENT_AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getEventAmount() {
        return eventAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.EVENT_AMOUNT
     *
     * @param eventAmount the value for AD_FAVORITE_TB.EVENT_AMOUNT
     *
     * @mbggenerated
     */
    public void setEventAmount(BigDecimal eventAmount) {
        this.eventAmount = eventAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.LOST_AMOUNT
     *
     * @return the value of AD_FAVORITE_TB.LOST_AMOUNT
     *
     * @mbggenerated
     */
    public BigDecimal getLostAmount() {
        return lostAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.LOST_AMOUNT
     *
     * @param lostAmount the value for AD_FAVORITE_TB.LOST_AMOUNT
     *
     * @mbggenerated
     */
    public void setLostAmount(BigDecimal lostAmount) {
        this.lostAmount = lostAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.EVENT_CONTEXT
     *
     * @return the value of AD_FAVORITE_TB.EVENT_CONTEXT
     *
     * @mbggenerated
     */
    public String getEventContext() {
        return eventContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.EVENT_CONTEXT
     *
     * @param eventContext the value for AD_FAVORITE_TB.EVENT_CONTEXT
     *
     * @mbggenerated
     */
    public void setEventContext(String eventContext) {
        this.eventContext = eventContext == null ? null : eventContext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.DEAL_DESCRIPTION
     *
     * @return the value of AD_FAVORITE_TB.DEAL_DESCRIPTION
     *
     * @mbggenerated
     */
    public String getDealDescription() {
        return dealDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.DEAL_DESCRIPTION
     *
     * @param dealDescription the value for AD_FAVORITE_TB.DEAL_DESCRIPTION
     *
     * @mbggenerated
     */
    public void setDealDescription(String dealDescription) {
        this.dealDescription = dealDescription == null ? null : dealDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.RISK_CONTEXT
     *
     * @return the value of AD_FAVORITE_TB.RISK_CONTEXT
     *
     * @mbggenerated
     */
    public String getRiskContext() {
        return riskContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.RISK_CONTEXT
     *
     * @param riskContext the value for AD_FAVORITE_TB.RISK_CONTEXT
     *
     * @mbggenerated
     */
    public void setRiskContext(String riskContext) {
        this.riskContext = riskContext == null ? null : riskContext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.WARN_ID
     *
     * @return the value of AD_FAVORITE_TB.WARN_ID
     *
     * @mbggenerated
     */
    public String getWarnId() {
        return warnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.WARN_ID
     *
     * @param warnId the value for AD_FAVORITE_TB.WARN_ID
     *
     * @mbggenerated
     */
    public void setWarnId(String warnId) {
        this.warnId = warnId == null ? null : warnId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.ADD_USER
     *
     * @return the value of AD_FAVORITE_TB.ADD_USER
     *
     * @mbggenerated
     */
    public String getAddUser() {
        return addUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.ADD_USER
     *
     * @param addUser the value for AD_FAVORITE_TB.ADD_USER
     *
     * @mbggenerated
     */
    public void setAddUser(String addUser) {
        this.addUser = addUser == null ? null : addUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.ADD_TIME
     *
     * @return the value of AD_FAVORITE_TB.ADD_TIME
     *
     * @mbggenerated
     */
    public String getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.ADD_TIME
     *
     * @param addTime the value for AD_FAVORITE_TB.ADD_TIME
     *
     * @mbggenerated
     */
    public void setAddTime(String addTime) {
        this.addTime = addTime == null ? null : addTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.ADD_REMARK
     *
     * @return the value of AD_FAVORITE_TB.ADD_REMARK
     *
     * @mbggenerated
     */
    public String getAddRemark() {
        return addRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.ADD_REMARK
     *
     * @param addRemark the value for AD_FAVORITE_TB.ADD_REMARK
     *
     * @mbggenerated
     */
    public void setAddRemark(String addRemark) {
        this.addRemark = addRemark == null ? null : addRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.STATUS
     *
     * @return the value of AD_FAVORITE_TB.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.STATUS
     *
     * @param status the value for AD_FAVORITE_TB.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.IS_SHARE
     *
     * @return the value of AD_FAVORITE_TB.IS_SHARE
     *
     * @mbggenerated
     */
    public String getIsShare() {
        return isShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.IS_SHARE
     *
     * @param isShare the value for AD_FAVORITE_TB.IS_SHARE
     *
     * @mbggenerated
     */
    public void setIsShare(String isShare) {
        this.isShare = isShare == null ? null : isShare.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AD_FAVORITE_TB.BANK_CODE
     *
     * @return the value of AD_FAVORITE_TB.BANK_CODE
     *
     * @mbggenerated
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AD_FAVORITE_TB.BANK_CODE
     *
     * @param bankCode the value for AD_FAVORITE_TB.BANK_CODE
     *
     * @mbggenerated
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode == null ? null : bankCode.trim();
    }
}