package com.sunyard.ars.system.bean.hx;

import java.util.Date;
public class ArmsFavorite {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMS_FAVORITE_TB.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMS_FAVORITE_TB.TYPE
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMS_FAVORITE_TB.ENTRY_ID
     *
     * @mbggenerated
     */
    private String entryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMS_FAVORITE_TB.ENTRYROW_ID
     *
     * @mbggenerated
     */
    private String entryrowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMS_FAVORITE_TB.FORM_ID
     *
     * @mbggenerated
     */
    private String formId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMS_FAVORITE_TB.FAVORITE_TITLE
     *
     * @mbggenerated
     */
    private String favoriteTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMS_FAVORITE_TB.FAVORITE_TIME
     *
     * @mbggenerated
     */
    private Date favoriteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMS_FAVORITE_TB.FAVORITE_USER
     *
     * @mbggenerated
     */
    private String favoriteUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMS_FAVORITE_TB.FAVORITE_ORGAN
     *
     * @mbggenerated
     */
    private String favoriteOrgan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMS_FAVORITE_TB.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMS_FAVORITE_TB.REMARK_COMMON
     *
     * @mbggenerated
     */
    private String remarkCommon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARMS_FAVORITE_TB.ISCOMMON
     *
     * @mbggenerated
     */
    private String iscommon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMS_FAVORITE_TB.ID
     *
     * @return the value of ARMS_FAVORITE_TB.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMS_FAVORITE_TB.ID
     *
     * @param id the value for ARMS_FAVORITE_TB.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMS_FAVORITE_TB.TYPE
     *
     * @return the value of ARMS_FAVORITE_TB.TYPE
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMS_FAVORITE_TB.TYPE
     *
     * @param type the value for ARMS_FAVORITE_TB.TYPE
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMS_FAVORITE_TB.ENTRY_ID
     *
     * @return the value of ARMS_FAVORITE_TB.ENTRY_ID
     *
     * @mbggenerated
     */
    public String getEntryId() {
        return entryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMS_FAVORITE_TB.ENTRY_ID
     *
     * @param entryId the value for ARMS_FAVORITE_TB.ENTRY_ID
     *
     * @mbggenerated
     */
    public void setEntryId(String entryId) {
        this.entryId = entryId == null ? null : entryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMS_FAVORITE_TB.ENTRYROW_ID
     *
     * @return the value of ARMS_FAVORITE_TB.ENTRYROW_ID
     *
     * @mbggenerated
     */
    public String getEntryrowId() {
        return entryrowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMS_FAVORITE_TB.ENTRYROW_ID
     *
     * @param entryrowId the value for ARMS_FAVORITE_TB.ENTRYROW_ID
     *
     * @mbggenerated
     */
    public void setEntryrowId(String entryrowId) {
        this.entryrowId = entryrowId == null ? null : entryrowId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMS_FAVORITE_TB.FORM_ID
     *
     * @return the value of ARMS_FAVORITE_TB.FORM_ID
     *
     * @mbggenerated
     */
    public String getFormId() {
        return formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMS_FAVORITE_TB.FORM_ID
     *
     * @param formId the value for ARMS_FAVORITE_TB.FORM_ID
     *
     * @mbggenerated
     */
    public void setFormId(String formId) {
        this.formId = formId == null ? null : formId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMS_FAVORITE_TB.FAVORITE_TITLE
     *
     * @return the value of ARMS_FAVORITE_TB.FAVORITE_TITLE
     *
     * @mbggenerated
     */
    public String getFavoriteTitle() {
        return favoriteTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMS_FAVORITE_TB.FAVORITE_TITLE
     *
     * @param favoriteTitle the value for ARMS_FAVORITE_TB.FAVORITE_TITLE
     *
     * @mbggenerated
     */
    public void setFavoriteTitle(String favoriteTitle) {
        this.favoriteTitle = favoriteTitle == null ? null : favoriteTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMS_FAVORITE_TB.FAVORITE_TIME
     *
     * @return the value of ARMS_FAVORITE_TB.FAVORITE_TIME
     *
     * @mbggenerated
     */
    public Date getFavoriteTime() {
        return favoriteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMS_FAVORITE_TB.FAVORITE_TIME
     *
     * @param favoriteTime the value for ARMS_FAVORITE_TB.FAVORITE_TIME
     *
     * @mbggenerated
     */
    public void setFavoriteTime(Date favoriteTime) {
        this.favoriteTime = favoriteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMS_FAVORITE_TB.FAVORITE_USER
     *
     * @return the value of ARMS_FAVORITE_TB.FAVORITE_USER
     *
     * @mbggenerated
     */
    public String getFavoriteUser() {
        return favoriteUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMS_FAVORITE_TB.FAVORITE_USER
     *
     * @param favoriteUser the value for ARMS_FAVORITE_TB.FAVORITE_USER
     *
     * @mbggenerated
     */
    public void setFavoriteUser(String favoriteUser) {
        this.favoriteUser = favoriteUser == null ? null : favoriteUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMS_FAVORITE_TB.FAVORITE_ORGAN
     *
     * @return the value of ARMS_FAVORITE_TB.FAVORITE_ORGAN
     *
     * @mbggenerated
     */
    public String getFavoriteOrgan() {
        return favoriteOrgan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMS_FAVORITE_TB.FAVORITE_ORGAN
     *
     * @param favoriteOrgan the value for ARMS_FAVORITE_TB.FAVORITE_ORGAN
     *
     * @mbggenerated
     */
    public void setFavoriteOrgan(String favoriteOrgan) {
        this.favoriteOrgan = favoriteOrgan == null ? null : favoriteOrgan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMS_FAVORITE_TB.REMARK
     *
     * @return the value of ARMS_FAVORITE_TB.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMS_FAVORITE_TB.REMARK
     *
     * @param remark the value for ARMS_FAVORITE_TB.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMS_FAVORITE_TB.REMARK_COMMON
     *
     * @return the value of ARMS_FAVORITE_TB.REMARK_COMMON
     *
     * @mbggenerated
     */
    public String getRemarkCommon() {
        return remarkCommon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMS_FAVORITE_TB.REMARK_COMMON
     *
     * @param remarkCommon the value for ARMS_FAVORITE_TB.REMARK_COMMON
     *
     * @mbggenerated
     */
    public void setRemarkCommon(String remarkCommon) {
        this.remarkCommon = remarkCommon == null ? null : remarkCommon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARMS_FAVORITE_TB.ISCOMMON
     *
     * @return the value of ARMS_FAVORITE_TB.ISCOMMON
     *
     * @mbggenerated
     */
    public String getIscommon() {
        return iscommon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARMS_FAVORITE_TB.ISCOMMON
     *
     * @param iscommon the value for ARMS_FAVORITE_TB.ISCOMMON
     *
     * @mbggenerated
     */
    public void setIscommon(String iscommon) {
        this.iscommon = iscommon == null ? null : iscommon.trim();
    }
}