package com.sunyard.ars.system.bean.hx;

import java.io.Serializable;

/**
 * @author:		 SUNYARD-NGQ
 * @date:		 2018年9月20日 下午5:29:35
 * @description: TODO(模型驱动因子对应的实体类--模型驱动因素表 )
 */
public class EntryRisk implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_ENTRY_RISK.ID
     * 模型ID
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_ENTRY_RISK.ENTRYID
     * 模型驱动因素ID
     * @mbggenerated
     */
    private Integer entryid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_ENTRY_RISK.SOURCE_NO
     * 驱动因素子类号码
     * @mbggenerated
     */
    private Integer sourceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_ENTRY_RISK.OPTUSER
     * 维护人员
     * @mbggenerated
     */
    private String optuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_ENTRY_RISK.CREATETIME
     * 维护时间
     * @mbggenerated
     */
    private String createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_ENTRY_RISK.ID
     *
     * @return the value of ET_ENTRY_RISK.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_ENTRY_RISK.ID
     *
     * @param id the value for ET_ENTRY_RISK.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_ENTRY_RISK.ENTRYID
     *
     * @return the value of ET_ENTRY_RISK.ENTRYID
     *
     * @mbggenerated
     */
    public Integer getEntryid() {
        return entryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_ENTRY_RISK.ENTRYID
     *
     * @param entryid the value for ET_ENTRY_RISK.ENTRYID
     *
     * @mbggenerated
     */
    public void setEntryid(Integer entryid) {
        this.entryid = entryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_ENTRY_RISK.SOURCE_NO
     *
     * @return the value of ET_ENTRY_RISK.SOURCE_NO
     *
     * @mbggenerated
     */
    public Integer getSourceNo() {
        return sourceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_ENTRY_RISK.SOURCE_NO
     *
     * @param sourceNo the value for ET_ENTRY_RISK.SOURCE_NO
     *
     * @mbggenerated
     */
    public void setSourceNo(Integer sourceNo) {
        this.sourceNo = sourceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_ENTRY_RISK.OPTUSER
     *
     * @return the value of ET_ENTRY_RISK.OPTUSER
     *
     * @mbggenerated
     */
    public String getOptuser() {
        return optuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_ENTRY_RISK.OPTUSER
     *
     * @param optuser the value for ET_ENTRY_RISK.OPTUSER
     *
     * @mbggenerated
     */
    public void setOptuser(String optuser) {
        this.optuser = optuser == null ? null : optuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_ENTRY_RISK.CREATETIME
     *
     * @return the value of ET_ENTRY_RISK.CREATETIME
     *
     * @mbggenerated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_ENTRY_RISK.CREATETIME
     *
     * @param createtime the value for ET_ENTRY_RISK.CREATETIME
     *
     * @mbggenerated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }
}