package com.sunyard.ars.system.bean.hx;

import java.math.BigDecimal;

public class EtBusiForm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.FORM_ID
     *
     * @mbggenerated
     */
    private String formId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.FORM_TYPE
     *
     * @mbggenerated
     */
    private String formType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.OPERATION_CLASS
     *
     * @mbggenerated
     */
    private String operationClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.WORK_DATE
     *
     * @mbggenerated
     */
    private String workDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.WORK_TIME
     *
     * @mbggenerated
     */
    private String workTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.XF_DATE
     *
     * @mbggenerated
     */
    private String xfDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.XF_TIME
     *
     * @mbggenerated
     */
    private String xfTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.NET_NO
     *
     * @mbggenerated
     */
    private String netNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.TELLER_NO
     *
     * @mbggenerated
     */
    private String tellerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.TELLER_NO_2
     *
     * @mbggenerated
     */
    private String tellerNo2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.TELLER_NO_3
     *
     * @mbggenerated
     */
    private String tellerNo3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.OPERATION_DATE
     *
     * @mbggenerated
     */
    private String operationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.ACCOUNT_NO
     *
     * @mbggenerated
     */
    private String accountNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.ACCOUNT_NAME
     *
     * @mbggenerated
     */
    private String accountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.ACCOUNT_MONEY
     *
     * @mbggenerated
     */
    private BigDecimal accountMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.VOUCHER_NO
     *
     * @mbggenerated
     */
    private String voucherNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.VOUCHER_DATE
     *
     * @mbggenerated
     */
    private String voucherDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.SUBPENA_NO
     *
     * @mbggenerated
     */
    private String subpenaNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.FLOW_NO
     *
     * @mbggenerated
     */
    private String flowNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.BACK_DATE
     *
     * @mbggenerated
     */
    private String backDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.SLIP_NO
     *
     * @mbggenerated
     */
    private String slipNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.SLIP_TYPE
     *
     * @mbggenerated
     */
    private String slipType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.OPERATION_TYPE
     *
     * @mbggenerated
     */
    private String operationType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.SLIP_NAME
     *
     * @mbggenerated
     */
    private String slipName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.SLIP_LEVEL
     *
     * @mbggenerated
     */
    private String slipLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.AMERCE_MONEY
     *
     * @mbggenerated
     */
    private BigDecimal amerceMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.FORM_DESCRIPTION
     *
     * @mbggenerated
     */
    private String formDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.INTERIOR_ET_NO
     *
     * @mbggenerated
     */
    private String interiorEtNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.INTERIOR_ET_NAME
     *
     * @mbggenerated
     */
    private String interiorEtName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.CHECKER_NO
     *
     * @mbggenerated
     */
    private String checkerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.CHECKER_NAME
     *
     * @mbggenerated
     */
    private String checkerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.CHECKER_ORGAN_NO
     *
     * @mbggenerated
     */
    private String checkerOrganNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.IMAGE_INDEX
     *
     * @mbggenerated
     */
    private String imageIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.ANNEX_PATH
     *
     * @mbggenerated
     */
    private String annexPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.SOURCE_FLAG
     *
     * @mbggenerated
     */
    private String sourceFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.OVERDUE_FLAG_1
     *
     * @mbggenerated
     */
    private String overdueFlag1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.OVERDUE_FLAG_2
     *
     * @mbggenerated
     */
    private String overdueFlag2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.OVERDUE_FLAG_3
     *
     * @mbggenerated
     */
    private String overdueFlag3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.OVERDUE_REMARK
     *
     * @mbggenerated
     */
    private String overdueRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.PROCESS_NODES
     *
     * @mbggenerated
     */
    private String processNodes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.NODE_NO
     *
     * @mbggenerated
     */
    private String nodeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.ACTIVE_FLAG
     *
     * @mbggenerated
     */
    private String activeFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.CORRELATIVE_ID
     *
     * @mbggenerated
     */
    private String correlativeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.INTERIOR_FORM_ID
     *
     * @mbggenerated
     */
    private String interiorFormId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.ACTIVE_DATE
     *
     * @mbggenerated
     */
    private String activeDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.DEGRADE
     *
     * @mbggenerated
     */
    private String degrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.TABLE_NAME
     *
     * @mbggenerated
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.ENTRY_ID
     *
     * @mbggenerated
     */
    private String entryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.ENTRY_NAME
     *
     * @mbggenerated
     */
    private String entryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.ENTRYROW_ID
     *
     * @mbggenerated
     */
    private String entryrowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.CC_LEADER
     *
     * @mbggenerated
     */
    private String ccLeader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.SEAN_LEADER
     *
     * @mbggenerated
     */
    private String seanLeader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.VOUCHER_NAME
     *
     * @mbggenerated
     */
    private String voucherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.TELLER_NAME
     *
     * @mbggenerated
     */
    private String tellerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.NET_NAME
     *
     * @mbggenerated
     */
    private String netName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.SLIP_NO_BAK
     *
     * @mbggenerated
     */
    private String slipNoBak;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.LEADER_REMARK
     *
     * @mbggenerated
     */
    private String leaderRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.CURRENCY_TYPE
     *
     * @mbggenerated
     */
    private String currencyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.CHECKER_NO_2
     *
     * @mbggenerated
     */
    private String checkerNo2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.BRASRULECONTEXT
     *
     * @mbggenerated
     */
    private String brasrulecontext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.RULE_ID
     *
     * @mbggenerated
     */
    private String ruleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.ALARM_LEVEL
     *
     * @mbggenerated
     */
    private String alarmLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.END_DATE
     *
     * @mbggenerated
     */
    private String endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.NOTICE_ID
     *
     * @mbggenerated
     */
    private String noticeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.JYDM
     *
     * @mbggenerated
     */
    private String jydm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.QDZL
     *
     * @mbggenerated
     */
    private String qdzl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.DEAL_NO
     *
     * @mbggenerated
     */
    private String dealNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.APPROVE_NO
     *
     * @mbggenerated
     */
    private String approveNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.DEAL_RESULT_F
     *
     * @mbggenerated
     */
    private String dealResultF;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.DEAL_RESULT_L
     *
     * @mbggenerated
     */
    private String dealResultL;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.DEAL_ORGAN
     *
     * @mbggenerated
     */
    private String dealOrgan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.BUSI_NO_CT
     *
     * @mbggenerated
     */
    private String busiNoCt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.BUSI_NO_TX
     *
     * @mbggenerated
     */
    private String busiNoTx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.NODE_TIME
     *
     * @mbggenerated
     */
    private String nodeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.ALARM_CREATE_TIME
     *
     * @mbggenerated
     */
    private String alarmCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.FORM_STATE
     *
     * @mbggenerated
     */
    private String formState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.FX_FLAG
     *
     * @mbggenerated
     */
    private String fxFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.DETAILURL
     *
     * @mbggenerated
     */
    private String detailurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.RISK_ORGAN
     *
     * @mbggenerated
     */
    private String riskOrgan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.DEAL_ORGAN_LIST
     *
     * @mbggenerated
     */
    private String dealOrganList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.CORR_USER_NO
     *
     * @mbggenerated
     */
    private String corrUserNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.CORR_BACK_DATE
     *
     * @mbggenerated
     */
    private String corrBackDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.CORR_DEAL_DATE
     *
     * @mbggenerated
     */
    private String corrDealDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.RETURN_STATE
     *
     * @mbggenerated
     */
    private String returnState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.RETURN_DATE
     *
     * @mbggenerated
     */
    private String returnDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.FILE_NAME
     *
     * @mbggenerated
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.REAL_NAME
     *
     * @mbggenerated
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.FILE_PATH
     *
     * @mbggenerated
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.FILE_EXT
     *
     * @mbggenerated
     */
    private String fileExt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.BRASRULECONTEXT_JM
     *
     * @mbggenerated
     */
    private String brasrulecontextJm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.IS_BF
     *
     * @mbggenerated
     */
    private String isBf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.BAKE_USER_NO
     *
     * @mbggenerated
     */
    private String bakeUserNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.IS_SEE
     *
     * @mbggenerated
     */
    private String isSee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.SEE_DESC
     *
     * @mbggenerated
     */
    private String seeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.RISK_TYPE
     *
     * @mbggenerated
     */
    private String riskType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.RISK_SOURCE_NO
     *
     * @mbggenerated
     */
    private String riskSourceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.RISK_SOURCE_TYPE
     *
     * @mbggenerated
     */
    private String riskSourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.RISK_SOURCE_NAME
     *
     * @mbggenerated
     */
    private String riskSourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.RISK_SOURCE_REMAK
     *
     * @mbggenerated
     */
    private String riskSourceRemak;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.CREATE_TIME
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.PROC_DATE
     *
     * @mbggenerated
     */
    private String procDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.PAR_OVER_DAYS
     *
     * @mbggenerated
     */
    private BigDecimal parOverDays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.PAR_BACK_DATE
     *
     * @mbggenerated
     */
    private String parBackDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.PAR_DEAL_DATE
     *
     * @mbggenerated
     */
    private String parDealDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ET_BUSIFORM_TB.ORG_DEAL_DATE
     *
     * @mbggenerated
     */
    private String orgDealDate;
    private String qdSlipMoid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.FORM_ID
     *
     * @return the value of ET_BUSIFORM_TB.FORM_ID
     *
     * @mbggenerated
     */
    public String getFormId() {
        return formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.FORM_ID
     *
     * @param formId the value for ET_BUSIFORM_TB.FORM_ID
     *
     * @mbggenerated
     */
    public void setFormId(String formId) {
        this.formId = formId == null ? null : formId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.FORM_TYPE
     *
     * @return the value of ET_BUSIFORM_TB.FORM_TYPE
     *
     * @mbggenerated
     */
    public String getFormType() {
        return formType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.FORM_TYPE
     *
     * @param formType the value for ET_BUSIFORM_TB.FORM_TYPE
     *
     * @mbggenerated
     */
    public void setFormType(String formType) {
        this.formType = formType == null ? null : formType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.OPERATION_CLASS
     *
     * @return the value of ET_BUSIFORM_TB.OPERATION_CLASS
     *
     * @mbggenerated
     */
    public String getOperationClass() {
        return operationClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.OPERATION_CLASS
     *
     * @param operationClass the value for ET_BUSIFORM_TB.OPERATION_CLASS
     *
     * @mbggenerated
     */
    public void setOperationClass(String operationClass) {
        this.operationClass = operationClass == null ? null : operationClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.WORK_DATE
     *
     * @return the value of ET_BUSIFORM_TB.WORK_DATE
     *
     * @mbggenerated
     */
    public String getWorkDate() {
        return workDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.WORK_DATE
     *
     * @param workDate the value for ET_BUSIFORM_TB.WORK_DATE
     *
     * @mbggenerated
     */
    public void setWorkDate(String workDate) {
        this.workDate = workDate == null ? null : workDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.WORK_TIME
     *
     * @return the value of ET_BUSIFORM_TB.WORK_TIME
     *
     * @mbggenerated
     */
    public String getWorkTime() {
        return workTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.WORK_TIME
     *
     * @param workTime the value for ET_BUSIFORM_TB.WORK_TIME
     *
     * @mbggenerated
     */
    public void setWorkTime(String workTime) {
        this.workTime = workTime == null ? null : workTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.XF_DATE
     *
     * @return the value of ET_BUSIFORM_TB.XF_DATE
     *
     * @mbggenerated
     */
    public String getXfDate() {
        return xfDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.XF_DATE
     *
     * @param xfDate the value for ET_BUSIFORM_TB.XF_DATE
     *
     * @mbggenerated
     */
    public void setXfDate(String xfDate) {
        this.xfDate = xfDate == null ? null : xfDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.XF_TIME
     *
     * @return the value of ET_BUSIFORM_TB.XF_TIME
     *
     * @mbggenerated
     */
    public String getXfTime() {
        return xfTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.XF_TIME
     *
     * @param xfTime the value for ET_BUSIFORM_TB.XF_TIME
     *
     * @mbggenerated
     */
    public void setXfTime(String xfTime) {
        this.xfTime = xfTime == null ? null : xfTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.NET_NO
     *
     * @return the value of ET_BUSIFORM_TB.NET_NO
     *
     * @mbggenerated
     */
    public String getNetNo() {
        return netNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.NET_NO
     *
     * @param netNo the value for ET_BUSIFORM_TB.NET_NO
     *
     * @mbggenerated
     */
    public void setNetNo(String netNo) {
        this.netNo = netNo == null ? null : netNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.TELLER_NO
     *
     * @return the value of ET_BUSIFORM_TB.TELLER_NO
     *
     * @mbggenerated
     */
    public String getTellerNo() {
        return tellerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.TELLER_NO
     *
     * @param tellerNo the value for ET_BUSIFORM_TB.TELLER_NO
     *
     * @mbggenerated
     */
    public void setTellerNo(String tellerNo) {
        this.tellerNo = tellerNo == null ? null : tellerNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.TELLER_NO_2
     *
     * @return the value of ET_BUSIFORM_TB.TELLER_NO_2
     *
     * @mbggenerated
     */
    public String getTellerNo2() {
        return tellerNo2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.TELLER_NO_2
     *
     * @param tellerNo2 the value for ET_BUSIFORM_TB.TELLER_NO_2
     *
     * @mbggenerated
     */
    public void setTellerNo2(String tellerNo2) {
        this.tellerNo2 = tellerNo2 == null ? null : tellerNo2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.TELLER_NO_3
     *
     * @return the value of ET_BUSIFORM_TB.TELLER_NO_3
     *
     * @mbggenerated
     */
    public String getTellerNo3() {
        return tellerNo3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.TELLER_NO_3
     *
     * @param tellerNo3 the value for ET_BUSIFORM_TB.TELLER_NO_3
     *
     * @mbggenerated
     */
    public void setTellerNo3(String tellerNo3) {
        this.tellerNo3 = tellerNo3 == null ? null : tellerNo3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.OPERATION_DATE
     *
     * @return the value of ET_BUSIFORM_TB.OPERATION_DATE
     *
     * @mbggenerated
     */
    public String getOperationDate() {
        return operationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.OPERATION_DATE
     *
     * @param operationDate the value for ET_BUSIFORM_TB.OPERATION_DATE
     *
     * @mbggenerated
     */
    public void setOperationDate(String operationDate) {
        this.operationDate = operationDate == null ? null : operationDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.ACCOUNT_NO
     *
     * @return the value of ET_BUSIFORM_TB.ACCOUNT_NO
     *
     * @mbggenerated
     */
    public String getAccountNo() {
        return accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.ACCOUNT_NO
     *
     * @param accountNo the value for ET_BUSIFORM_TB.ACCOUNT_NO
     *
     * @mbggenerated
     */
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo == null ? null : accountNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.ACCOUNT_NAME
     *
     * @return the value of ET_BUSIFORM_TB.ACCOUNT_NAME
     *
     * @mbggenerated
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.ACCOUNT_NAME
     *
     * @param accountName the value for ET_BUSIFORM_TB.ACCOUNT_NAME
     *
     * @mbggenerated
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.ACCOUNT_MONEY
     *
     * @return the value of ET_BUSIFORM_TB.ACCOUNT_MONEY
     *
     * @mbggenerated
     */
    public BigDecimal getAccountMoney() {
        return accountMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.ACCOUNT_MONEY
     *
     * @param accountMoney the value for ET_BUSIFORM_TB.ACCOUNT_MONEY
     *
     * @mbggenerated
     */
    public void setAccountMoney(BigDecimal accountMoney) {
        this.accountMoney = accountMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.VOUCHER_NO
     *
     * @return the value of ET_BUSIFORM_TB.VOUCHER_NO
     *
     * @mbggenerated
     */
    public String getVoucherNo() {
        return voucherNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.VOUCHER_NO
     *
     * @param voucherNo the value for ET_BUSIFORM_TB.VOUCHER_NO
     *
     * @mbggenerated
     */
    public void setVoucherNo(String voucherNo) {
        this.voucherNo = voucherNo == null ? null : voucherNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.VOUCHER_DATE
     *
     * @return the value of ET_BUSIFORM_TB.VOUCHER_DATE
     *
     * @mbggenerated
     */
    public String getVoucherDate() {
        return voucherDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.VOUCHER_DATE
     *
     * @param voucherDate the value for ET_BUSIFORM_TB.VOUCHER_DATE
     *
     * @mbggenerated
     */
    public void setVoucherDate(String voucherDate) {
        this.voucherDate = voucherDate == null ? null : voucherDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.SUBPENA_NO
     *
     * @return the value of ET_BUSIFORM_TB.SUBPENA_NO
     *
     * @mbggenerated
     */
    public String getSubpenaNo() {
        return subpenaNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.SUBPENA_NO
     *
     * @param subpenaNo the value for ET_BUSIFORM_TB.SUBPENA_NO
     *
     * @mbggenerated
     */
    public void setSubpenaNo(String subpenaNo) {
        this.subpenaNo = subpenaNo == null ? null : subpenaNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.FLOW_NO
     *
     * @return the value of ET_BUSIFORM_TB.FLOW_NO
     *
     * @mbggenerated
     */
    public String getFlowNo() {
        return flowNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.FLOW_NO
     *
     * @param flowNo the value for ET_BUSIFORM_TB.FLOW_NO
     *
     * @mbggenerated
     */
    public void setFlowNo(String flowNo) {
        this.flowNo = flowNo == null ? null : flowNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.BACK_DATE
     *
     * @return the value of ET_BUSIFORM_TB.BACK_DATE
     *
     * @mbggenerated
     */
    public String getBackDate() {
        return backDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.BACK_DATE
     *
     * @param backDate the value for ET_BUSIFORM_TB.BACK_DATE
     *
     * @mbggenerated
     */
    public void setBackDate(String backDate) {
        this.backDate = backDate == null ? null : backDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.SLIP_NO
     *
     * @return the value of ET_BUSIFORM_TB.SLIP_NO
     *
     * @mbggenerated
     */
    public String getSlipNo() {
        return slipNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.SLIP_NO
     *
     * @param slipNo the value for ET_BUSIFORM_TB.SLIP_NO
     *
     * @mbggenerated
     */
    public void setSlipNo(String slipNo) {
        this.slipNo = slipNo == null ? null : slipNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.SLIP_TYPE
     *
     * @return the value of ET_BUSIFORM_TB.SLIP_TYPE
     *
     * @mbggenerated
     */
    public String getSlipType() {
        return slipType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.SLIP_TYPE
     *
     * @param slipType the value for ET_BUSIFORM_TB.SLIP_TYPE
     *
     * @mbggenerated
     */
    public void setSlipType(String slipType) {
        this.slipType = slipType == null ? null : slipType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.OPERATION_TYPE
     *
     * @return the value of ET_BUSIFORM_TB.OPERATION_TYPE
     *
     * @mbggenerated
     */
    public String getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.OPERATION_TYPE
     *
     * @param operationType the value for ET_BUSIFORM_TB.OPERATION_TYPE
     *
     * @mbggenerated
     */
    public void setOperationType(String operationType) {
        this.operationType = operationType == null ? null : operationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.SLIP_NAME
     *
     * @return the value of ET_BUSIFORM_TB.SLIP_NAME
     *
     * @mbggenerated
     */
    public String getSlipName() {
        return slipName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.SLIP_NAME
     *
     * @param slipName the value for ET_BUSIFORM_TB.SLIP_NAME
     *
     * @mbggenerated
     */
    public void setSlipName(String slipName) {
        this.slipName = slipName == null ? null : slipName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.SLIP_LEVEL
     *
     * @return the value of ET_BUSIFORM_TB.SLIP_LEVEL
     *
     * @mbggenerated
     */
    public String getSlipLevel() {
        return slipLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.SLIP_LEVEL
     *
     * @param slipLevel the value for ET_BUSIFORM_TB.SLIP_LEVEL
     *
     * @mbggenerated
     */
    public void setSlipLevel(String slipLevel) {
        this.slipLevel = slipLevel == null ? null : slipLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.AMERCE_MONEY
     *
     * @return the value of ET_BUSIFORM_TB.AMERCE_MONEY
     *
     * @mbggenerated
     */
    public BigDecimal getAmerceMoney() {
        return amerceMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.AMERCE_MONEY
     *
     * @param amerceMoney the value for ET_BUSIFORM_TB.AMERCE_MONEY
     *
     * @mbggenerated
     */
    public void setAmerceMoney(BigDecimal amerceMoney) {
        this.amerceMoney = amerceMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.FORM_DESCRIPTION
     *
     * @return the value of ET_BUSIFORM_TB.FORM_DESCRIPTION
     *
     * @mbggenerated
     */
    public String getFormDescription() {
        return formDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.FORM_DESCRIPTION
     *
     * @param formDescription the value for ET_BUSIFORM_TB.FORM_DESCRIPTION
     *
     * @mbggenerated
     */
    public void setFormDescription(String formDescription) {
        this.formDescription = formDescription == null ? null : formDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.INTERIOR_ET_NO
     *
     * @return the value of ET_BUSIFORM_TB.INTERIOR_ET_NO
     *
     * @mbggenerated
     */
    public String getInteriorEtNo() {
        return interiorEtNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.INTERIOR_ET_NO
     *
     * @param interiorEtNo the value for ET_BUSIFORM_TB.INTERIOR_ET_NO
     *
     * @mbggenerated
     */
    public void setInteriorEtNo(String interiorEtNo) {
        this.interiorEtNo = interiorEtNo == null ? null : interiorEtNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.INTERIOR_ET_NAME
     *
     * @return the value of ET_BUSIFORM_TB.INTERIOR_ET_NAME
     *
     * @mbggenerated
     */
    public String getInteriorEtName() {
        return interiorEtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.INTERIOR_ET_NAME
     *
     * @param interiorEtName the value for ET_BUSIFORM_TB.INTERIOR_ET_NAME
     *
     * @mbggenerated
     */
    public void setInteriorEtName(String interiorEtName) {
        this.interiorEtName = interiorEtName == null ? null : interiorEtName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.CHECKER_NO
     *
     * @return the value of ET_BUSIFORM_TB.CHECKER_NO
     *
     * @mbggenerated
     */
    public String getCheckerNo() {
        return checkerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.CHECKER_NO
     *
     * @param checkerNo the value for ET_BUSIFORM_TB.CHECKER_NO
     *
     * @mbggenerated
     */
    public void setCheckerNo(String checkerNo) {
        this.checkerNo = checkerNo == null ? null : checkerNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.CHECKER_NAME
     *
     * @return the value of ET_BUSIFORM_TB.CHECKER_NAME
     *
     * @mbggenerated
     */
    public String getCheckerName() {
        return checkerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.CHECKER_NAME
     *
     * @param checkerName the value for ET_BUSIFORM_TB.CHECKER_NAME
     *
     * @mbggenerated
     */
    public void setCheckerName(String checkerName) {
        this.checkerName = checkerName == null ? null : checkerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.CHECKER_ORGAN_NO
     *
     * @return the value of ET_BUSIFORM_TB.CHECKER_ORGAN_NO
     *
     * @mbggenerated
     */
    public String getCheckerOrganNo() {
        return checkerOrganNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.CHECKER_ORGAN_NO
     *
     * @param checkerOrganNo the value for ET_BUSIFORM_TB.CHECKER_ORGAN_NO
     *
     * @mbggenerated
     */
    public void setCheckerOrganNo(String checkerOrganNo) {
        this.checkerOrganNo = checkerOrganNo == null ? null : checkerOrganNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.IMAGE_INDEX
     *
     * @return the value of ET_BUSIFORM_TB.IMAGE_INDEX
     *
     * @mbggenerated
     */
    public String getImageIndex() {
        return imageIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.IMAGE_INDEX
     *
     * @param imageIndex the value for ET_BUSIFORM_TB.IMAGE_INDEX
     *
     * @mbggenerated
     */
    public void setImageIndex(String imageIndex) {
        this.imageIndex = imageIndex == null ? null : imageIndex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.ANNEX_PATH
     *
     * @return the value of ET_BUSIFORM_TB.ANNEX_PATH
     *
     * @mbggenerated
     */
    public String getAnnexPath() {
        return annexPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.ANNEX_PATH
     *
     * @param annexPath the value for ET_BUSIFORM_TB.ANNEX_PATH
     *
     * @mbggenerated
     */
    public void setAnnexPath(String annexPath) {
        this.annexPath = annexPath == null ? null : annexPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.SOURCE_FLAG
     *
     * @return the value of ET_BUSIFORM_TB.SOURCE_FLAG
     *
     * @mbggenerated
     */
    public String getSourceFlag() {
        return sourceFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.SOURCE_FLAG
     *
     * @param sourceFlag the value for ET_BUSIFORM_TB.SOURCE_FLAG
     *
     * @mbggenerated
     */
    public void setSourceFlag(String sourceFlag) {
        this.sourceFlag = sourceFlag == null ? null : sourceFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.OVERDUE_FLAG_1
     *
     * @return the value of ET_BUSIFORM_TB.OVERDUE_FLAG_1
     *
     * @mbggenerated
     */
    public String getOverdueFlag1() {
        return overdueFlag1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.OVERDUE_FLAG_1
     *
     * @param overdueFlag1 the value for ET_BUSIFORM_TB.OVERDUE_FLAG_1
     *
     * @mbggenerated
     */
    public void setOverdueFlag1(String overdueFlag1) {
        this.overdueFlag1 = overdueFlag1 == null ? null : overdueFlag1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.OVERDUE_FLAG_2
     *
     * @return the value of ET_BUSIFORM_TB.OVERDUE_FLAG_2
     *
     * @mbggenerated
     */
    public String getOverdueFlag2() {
        return overdueFlag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.OVERDUE_FLAG_2
     *
     * @param overdueFlag2 the value for ET_BUSIFORM_TB.OVERDUE_FLAG_2
     *
     * @mbggenerated
     */
    public void setOverdueFlag2(String overdueFlag2) {
        this.overdueFlag2 = overdueFlag2 == null ? null : overdueFlag2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.OVERDUE_FLAG_3
     *
     * @return the value of ET_BUSIFORM_TB.OVERDUE_FLAG_3
     *
     * @mbggenerated
     */
    public String getOverdueFlag3() {
        return overdueFlag3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.OVERDUE_FLAG_3
     *
     * @param overdueFlag3 the value for ET_BUSIFORM_TB.OVERDUE_FLAG_3
     *
     * @mbggenerated
     */
    public void setOverdueFlag3(String overdueFlag3) {
        this.overdueFlag3 = overdueFlag3 == null ? null : overdueFlag3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.OVERDUE_REMARK
     *
     * @return the value of ET_BUSIFORM_TB.OVERDUE_REMARK
     *
     * @mbggenerated
     */
    public String getOverdueRemark() {
        return overdueRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.OVERDUE_REMARK
     *
     * @param overdueRemark the value for ET_BUSIFORM_TB.OVERDUE_REMARK
     *
     * @mbggenerated
     */
    public void setOverdueRemark(String overdueRemark) {
        this.overdueRemark = overdueRemark == null ? null : overdueRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.PROCESS_NODES
     *
     * @return the value of ET_BUSIFORM_TB.PROCESS_NODES
     *
     * @mbggenerated
     */
    public String getProcessNodes() {
        return processNodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.PROCESS_NODES
     *
     * @param processNodes the value for ET_BUSIFORM_TB.PROCESS_NODES
     *
     * @mbggenerated
     */
    public void setProcessNodes(String processNodes) {
        this.processNodes = processNodes == null ? null : processNodes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.NODE_NO
     *
     * @return the value of ET_BUSIFORM_TB.NODE_NO
     *
     * @mbggenerated
     */
    public String getNodeNo() {
        return nodeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.NODE_NO
     *
     * @param nodeNo the value for ET_BUSIFORM_TB.NODE_NO
     *
     * @mbggenerated
     */
    public void setNodeNo(String nodeNo) {
        this.nodeNo = nodeNo == null ? null : nodeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.ACTIVE_FLAG
     *
     * @return the value of ET_BUSIFORM_TB.ACTIVE_FLAG
     *
     * @mbggenerated
     */
    public String getActiveFlag() {
        return activeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.ACTIVE_FLAG
     *
     * @param activeFlag the value for ET_BUSIFORM_TB.ACTIVE_FLAG
     *
     * @mbggenerated
     */
    public void setActiveFlag(String activeFlag) {
        this.activeFlag = activeFlag == null ? null : activeFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.CORRELATIVE_ID
     *
     * @return the value of ET_BUSIFORM_TB.CORRELATIVE_ID
     *
     * @mbggenerated
     */
    public String getCorrelativeId() {
        return correlativeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.CORRELATIVE_ID
     *
     * @param correlativeId the value for ET_BUSIFORM_TB.CORRELATIVE_ID
     *
     * @mbggenerated
     */
    public void setCorrelativeId(String correlativeId) {
        this.correlativeId = correlativeId == null ? null : correlativeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.INTERIOR_FORM_ID
     *
     * @return the value of ET_BUSIFORM_TB.INTERIOR_FORM_ID
     *
     * @mbggenerated
     */
    public String getInteriorFormId() {
        return interiorFormId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.INTERIOR_FORM_ID
     *
     * @param interiorFormId the value for ET_BUSIFORM_TB.INTERIOR_FORM_ID
     *
     * @mbggenerated
     */
    public void setInteriorFormId(String interiorFormId) {
        this.interiorFormId = interiorFormId == null ? null : interiorFormId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.ACTIVE_DATE
     *
     * @return the value of ET_BUSIFORM_TB.ACTIVE_DATE
     *
     * @mbggenerated
     */
    public String getActiveDate() {
        return activeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.ACTIVE_DATE
     *
     * @param activeDate the value for ET_BUSIFORM_TB.ACTIVE_DATE
     *
     * @mbggenerated
     */
    public void setActiveDate(String activeDate) {
        this.activeDate = activeDate == null ? null : activeDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.DEGRADE
     *
     * @return the value of ET_BUSIFORM_TB.DEGRADE
     *
     * @mbggenerated
     */
    public String getDegrade() {
        return degrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.DEGRADE
     *
     * @param degrade the value for ET_BUSIFORM_TB.DEGRADE
     *
     * @mbggenerated
     */
    public void setDegrade(String degrade) {
        this.degrade = degrade == null ? null : degrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.TABLE_NAME
     *
     * @return the value of ET_BUSIFORM_TB.TABLE_NAME
     *
     * @mbggenerated
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.TABLE_NAME
     *
     * @param tableName the value for ET_BUSIFORM_TB.TABLE_NAME
     *
     * @mbggenerated
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.ENTRY_ID
     *
     * @return the value of ET_BUSIFORM_TB.ENTRY_ID
     *
     * @mbggenerated
     */
    public String getEntryId() {
        return entryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.ENTRY_ID
     *
     * @param entryId the value for ET_BUSIFORM_TB.ENTRY_ID
     *
     * @mbggenerated
     */
    public void setEntryId(String entryId) {
        this.entryId = entryId == null ? null : entryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.ENTRY_NAME
     *
     * @return the value of ET_BUSIFORM_TB.ENTRY_NAME
     *
     * @mbggenerated
     */
    public String getEntryName() {
        return entryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.ENTRY_NAME
     *
     * @param entryName the value for ET_BUSIFORM_TB.ENTRY_NAME
     *
     * @mbggenerated
     */
    public void setEntryName(String entryName) {
        this.entryName = entryName == null ? null : entryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.ENTRYROW_ID
     *
     * @return the value of ET_BUSIFORM_TB.ENTRYROW_ID
     *
     * @mbggenerated
     */
    public String getEntryrowId() {
        return entryrowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.ENTRYROW_ID
     *
     * @param entryrowId the value for ET_BUSIFORM_TB.ENTRYROW_ID
     *
     * @mbggenerated
     */
    public void setEntryrowId(String entryrowId) {
        this.entryrowId = entryrowId == null ? null : entryrowId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.CC_LEADER
     *
     * @return the value of ET_BUSIFORM_TB.CC_LEADER
     *
     * @mbggenerated
     */
    public String getCcLeader() {
        return ccLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.CC_LEADER
     *
     * @param ccLeader the value for ET_BUSIFORM_TB.CC_LEADER
     *
     * @mbggenerated
     */
    public void setCcLeader(String ccLeader) {
        this.ccLeader = ccLeader == null ? null : ccLeader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.SEAN_LEADER
     *
     * @return the value of ET_BUSIFORM_TB.SEAN_LEADER
     *
     * @mbggenerated
     */
    public String getSeanLeader() {
        return seanLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.SEAN_LEADER
     *
     * @param seanLeader the value for ET_BUSIFORM_TB.SEAN_LEADER
     *
     * @mbggenerated
     */
    public void setSeanLeader(String seanLeader) {
        this.seanLeader = seanLeader == null ? null : seanLeader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.VOUCHER_NAME
     *
     * @return the value of ET_BUSIFORM_TB.VOUCHER_NAME
     *
     * @mbggenerated
     */
    public String getVoucherName() {
        return voucherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.VOUCHER_NAME
     *
     * @param voucherName the value for ET_BUSIFORM_TB.VOUCHER_NAME
     *
     * @mbggenerated
     */
    public void setVoucherName(String voucherName) {
        this.voucherName = voucherName == null ? null : voucherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.TELLER_NAME
     *
     * @return the value of ET_BUSIFORM_TB.TELLER_NAME
     *
     * @mbggenerated
     */
    public String getTellerName() {
        return tellerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.TELLER_NAME
     *
     * @param tellerName the value for ET_BUSIFORM_TB.TELLER_NAME
     *
     * @mbggenerated
     */
    public void setTellerName(String tellerName) {
        this.tellerName = tellerName == null ? null : tellerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.NET_NAME
     *
     * @return the value of ET_BUSIFORM_TB.NET_NAME
     *
     * @mbggenerated
     */
    public String getNetName() {
        return netName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.NET_NAME
     *
     * @param netName the value for ET_BUSIFORM_TB.NET_NAME
     *
     * @mbggenerated
     */
    public void setNetName(String netName) {
        this.netName = netName == null ? null : netName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.SLIP_NO_BAK
     *
     * @return the value of ET_BUSIFORM_TB.SLIP_NO_BAK
     *
     * @mbggenerated
     */
    public String getSlipNoBak() {
        return slipNoBak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.SLIP_NO_BAK
     *
     * @param slipNoBak the value for ET_BUSIFORM_TB.SLIP_NO_BAK
     *
     * @mbggenerated
     */
    public void setSlipNoBak(String slipNoBak) {
        this.slipNoBak = slipNoBak == null ? null : slipNoBak.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.LEADER_REMARK
     *
     * @return the value of ET_BUSIFORM_TB.LEADER_REMARK
     *
     * @mbggenerated
     */
    public String getLeaderRemark() {
        return leaderRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.LEADER_REMARK
     *
     * @param leaderRemark the value for ET_BUSIFORM_TB.LEADER_REMARK
     *
     * @mbggenerated
     */
    public void setLeaderRemark(String leaderRemark) {
        this.leaderRemark = leaderRemark == null ? null : leaderRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.CURRENCY_TYPE
     *
     * @return the value of ET_BUSIFORM_TB.CURRENCY_TYPE
     *
     * @mbggenerated
     */
    public String getCurrencyType() {
        return currencyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.CURRENCY_TYPE
     *
     * @param currencyType the value for ET_BUSIFORM_TB.CURRENCY_TYPE
     *
     * @mbggenerated
     */
    public void setCurrencyType(String currencyType) {
        this.currencyType = currencyType == null ? null : currencyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.CHECKER_NO_2
     *
     * @return the value of ET_BUSIFORM_TB.CHECKER_NO_2
     *
     * @mbggenerated
     */
    public String getCheckerNo2() {
        return checkerNo2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.CHECKER_NO_2
     *
     * @param checkerNo2 the value for ET_BUSIFORM_TB.CHECKER_NO_2
     *
     * @mbggenerated
     */
    public void setCheckerNo2(String checkerNo2) {
        this.checkerNo2 = checkerNo2 == null ? null : checkerNo2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.BRASRULECONTEXT
     *
     * @return the value of ET_BUSIFORM_TB.BRASRULECONTEXT
     *
     * @mbggenerated
     */
    public String getBrasrulecontext() {
        return brasrulecontext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.BRASRULECONTEXT
     *
     * @param brasrulecontext the value for ET_BUSIFORM_TB.BRASRULECONTEXT
     *
     * @mbggenerated
     */
    public void setBrasrulecontext(String brasrulecontext) {
        this.brasrulecontext = brasrulecontext == null ? null : brasrulecontext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.RULE_ID
     *
     * @return the value of ET_BUSIFORM_TB.RULE_ID
     *
     * @mbggenerated
     */
    public String getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.RULE_ID
     *
     * @param ruleId the value for ET_BUSIFORM_TB.RULE_ID
     *
     * @mbggenerated
     */
    public void setRuleId(String ruleId) {
        this.ruleId = ruleId == null ? null : ruleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.ALARM_LEVEL
     *
     * @return the value of ET_BUSIFORM_TB.ALARM_LEVEL
     *
     * @mbggenerated
     */
    public String getAlarmLevel() {
        return alarmLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.ALARM_LEVEL
     *
     * @param alarmLevel the value for ET_BUSIFORM_TB.ALARM_LEVEL
     *
     * @mbggenerated
     */
    public void setAlarmLevel(String alarmLevel) {
        this.alarmLevel = alarmLevel == null ? null : alarmLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.END_DATE
     *
     * @return the value of ET_BUSIFORM_TB.END_DATE
     *
     * @mbggenerated
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.END_DATE
     *
     * @param endDate the value for ET_BUSIFORM_TB.END_DATE
     *
     * @mbggenerated
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.NOTICE_ID
     *
     * @return the value of ET_BUSIFORM_TB.NOTICE_ID
     *
     * @mbggenerated
     */
    public String getNoticeId() {
        return noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.NOTICE_ID
     *
     * @param noticeId the value for ET_BUSIFORM_TB.NOTICE_ID
     *
     * @mbggenerated
     */
    public void setNoticeId(String noticeId) {
        this.noticeId = noticeId == null ? null : noticeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.JYDM
     *
     * @return the value of ET_BUSIFORM_TB.JYDM
     *
     * @mbggenerated
     */
    public String getJydm() {
        return jydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.JYDM
     *
     * @param jydm the value for ET_BUSIFORM_TB.JYDM
     *
     * @mbggenerated
     */
    public void setJydm(String jydm) {
        this.jydm = jydm == null ? null : jydm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.QDZL
     *
     * @return the value of ET_BUSIFORM_TB.QDZL
     *
     * @mbggenerated
     */
    public String getQdzl() {
        return qdzl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.QDZL
     *
     * @param qdzl the value for ET_BUSIFORM_TB.QDZL
     *
     * @mbggenerated
     */
    public void setQdzl(String qdzl) {
        this.qdzl = qdzl == null ? null : qdzl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.DEAL_NO
     *
     * @return the value of ET_BUSIFORM_TB.DEAL_NO
     *
     * @mbggenerated
     */
    public String getDealNo() {
        return dealNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.DEAL_NO
     *
     * @param dealNo the value for ET_BUSIFORM_TB.DEAL_NO
     *
     * @mbggenerated
     */
    public void setDealNo(String dealNo) {
        this.dealNo = dealNo == null ? null : dealNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.APPROVE_NO
     *
     * @return the value of ET_BUSIFORM_TB.APPROVE_NO
     *
     * @mbggenerated
     */
    public String getApproveNo() {
        return approveNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.APPROVE_NO
     *
     * @param approveNo the value for ET_BUSIFORM_TB.APPROVE_NO
     *
     * @mbggenerated
     */
    public void setApproveNo(String approveNo) {
        this.approveNo = approveNo == null ? null : approveNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.DEAL_RESULT_F
     *
     * @return the value of ET_BUSIFORM_TB.DEAL_RESULT_F
     *
     * @mbggenerated
     */
    public String getDealResultF() {
        return dealResultF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.DEAL_RESULT_F
     *
     * @param dealResultF the value for ET_BUSIFORM_TB.DEAL_RESULT_F
     *
     * @mbggenerated
     */
    public void setDealResultF(String dealResultF) {
        this.dealResultF = dealResultF == null ? null : dealResultF.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.DEAL_RESULT_L
     *
     * @return the value of ET_BUSIFORM_TB.DEAL_RESULT_L
     *
     * @mbggenerated
     */
    public String getDealResultL() {
        return dealResultL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.DEAL_RESULT_L
     *
     * @param dealResultL the value for ET_BUSIFORM_TB.DEAL_RESULT_L
     *
     * @mbggenerated
     */
    public void setDealResultL(String dealResultL) {
        this.dealResultL = dealResultL == null ? null : dealResultL.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.DEAL_ORGAN
     *
     * @return the value of ET_BUSIFORM_TB.DEAL_ORGAN
     *
     * @mbggenerated
     */
    public String getDealOrgan() {
        return dealOrgan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.DEAL_ORGAN
     *
     * @param dealOrgan the value for ET_BUSIFORM_TB.DEAL_ORGAN
     *
     * @mbggenerated
     */
    public void setDealOrgan(String dealOrgan) {
        this.dealOrgan = dealOrgan == null ? null : dealOrgan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.BUSI_NO_CT
     *
     * @return the value of ET_BUSIFORM_TB.BUSI_NO_CT
     *
     * @mbggenerated
     */
    public String getBusiNoCt() {
        return busiNoCt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.BUSI_NO_CT
     *
     * @param busiNoCt the value for ET_BUSIFORM_TB.BUSI_NO_CT
     *
     * @mbggenerated
     */
    public void setBusiNoCt(String busiNoCt) {
        this.busiNoCt = busiNoCt == null ? null : busiNoCt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.BUSI_NO_TX
     *
     * @return the value of ET_BUSIFORM_TB.BUSI_NO_TX
     *
     * @mbggenerated
     */
    public String getBusiNoTx() {
        return busiNoTx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.BUSI_NO_TX
     *
     * @param busiNoTx the value for ET_BUSIFORM_TB.BUSI_NO_TX
     *
     * @mbggenerated
     */
    public void setBusiNoTx(String busiNoTx) {
        this.busiNoTx = busiNoTx == null ? null : busiNoTx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.NODE_TIME
     *
     * @return the value of ET_BUSIFORM_TB.NODE_TIME
     *
     * @mbggenerated
     */
    public String getNodeTime() {
        return nodeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.NODE_TIME
     *
     * @param nodeTime the value for ET_BUSIFORM_TB.NODE_TIME
     *
     * @mbggenerated
     */
    public void setNodeTime(String nodeTime) {
        this.nodeTime = nodeTime == null ? null : nodeTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.ALARM_CREATE_TIME
     *
     * @return the value of ET_BUSIFORM_TB.ALARM_CREATE_TIME
     *
     * @mbggenerated
     */
    public String getAlarmCreateTime() {
        return alarmCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.ALARM_CREATE_TIME
     *
     * @param alarmCreateTime the value for ET_BUSIFORM_TB.ALARM_CREATE_TIME
     *
     * @mbggenerated
     */
    public void setAlarmCreateTime(String alarmCreateTime) {
        this.alarmCreateTime = alarmCreateTime == null ? null : alarmCreateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.FORM_STATE
     *
     * @return the value of ET_BUSIFORM_TB.FORM_STATE
     *
     * @mbggenerated
     */
    public String getFormState() {
        return formState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.FORM_STATE
     *
     * @param formState the value for ET_BUSIFORM_TB.FORM_STATE
     *
     * @mbggenerated
     */
    public void setFormState(String formState) {
        this.formState = formState == null ? null : formState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.FX_FLAG
     *
     * @return the value of ET_BUSIFORM_TB.FX_FLAG
     *
     * @mbggenerated
     */
    public String getFxFlag() {
        return fxFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.FX_FLAG
     *
     * @param fxFlag the value for ET_BUSIFORM_TB.FX_FLAG
     *
     * @mbggenerated
     */
    public void setFxFlag(String fxFlag) {
        this.fxFlag = fxFlag == null ? null : fxFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.DETAILURL
     *
     * @return the value of ET_BUSIFORM_TB.DETAILURL
     *
     * @mbggenerated
     */
    public String getDetailurl() {
        return detailurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.DETAILURL
     *
     * @param detailurl the value for ET_BUSIFORM_TB.DETAILURL
     *
     * @mbggenerated
     */
    public void setDetailurl(String detailurl) {
        this.detailurl = detailurl == null ? null : detailurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.RISK_ORGAN
     *
     * @return the value of ET_BUSIFORM_TB.RISK_ORGAN
     *
     * @mbggenerated
     */
    public String getRiskOrgan() {
        return riskOrgan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.RISK_ORGAN
     *
     * @param riskOrgan the value for ET_BUSIFORM_TB.RISK_ORGAN
     *
     * @mbggenerated
     */
    public void setRiskOrgan(String riskOrgan) {
        this.riskOrgan = riskOrgan == null ? null : riskOrgan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.DEAL_ORGAN_LIST
     *
     * @return the value of ET_BUSIFORM_TB.DEAL_ORGAN_LIST
     *
     * @mbggenerated
     */
    public String getDealOrganList() {
        return dealOrganList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.DEAL_ORGAN_LIST
     *
     * @param dealOrganList the value for ET_BUSIFORM_TB.DEAL_ORGAN_LIST
     *
     * @mbggenerated
     */
    public void setDealOrganList(String dealOrganList) {
        this.dealOrganList = dealOrganList == null ? null : dealOrganList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.CORR_USER_NO
     *
     * @return the value of ET_BUSIFORM_TB.CORR_USER_NO
     *
     * @mbggenerated
     */
    public String getCorrUserNo() {
        return corrUserNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.CORR_USER_NO
     *
     * @param corrUserNo the value for ET_BUSIFORM_TB.CORR_USER_NO
     *
     * @mbggenerated
     */
    public void setCorrUserNo(String corrUserNo) {
        this.corrUserNo = corrUserNo == null ? null : corrUserNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.CORR_BACK_DATE
     *
     * @return the value of ET_BUSIFORM_TB.CORR_BACK_DATE
     *
     * @mbggenerated
     */
    public String getCorrBackDate() {
        return corrBackDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.CORR_BACK_DATE
     *
     * @param corrBackDate the value for ET_BUSIFORM_TB.CORR_BACK_DATE
     *
     * @mbggenerated
     */
    public void setCorrBackDate(String corrBackDate) {
        this.corrBackDate = corrBackDate == null ? null : corrBackDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.CORR_DEAL_DATE
     *
     * @return the value of ET_BUSIFORM_TB.CORR_DEAL_DATE
     *
     * @mbggenerated
     */
    public String getCorrDealDate() {
        return corrDealDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.CORR_DEAL_DATE
     *
     * @param corrDealDate the value for ET_BUSIFORM_TB.CORR_DEAL_DATE
     *
     * @mbggenerated
     */
    public void setCorrDealDate(String corrDealDate) {
        this.corrDealDate = corrDealDate == null ? null : corrDealDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.RETURN_STATE
     *
     * @return the value of ET_BUSIFORM_TB.RETURN_STATE
     *
     * @mbggenerated
     */
    public String getReturnState() {
        return returnState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.RETURN_STATE
     *
     * @param returnState the value for ET_BUSIFORM_TB.RETURN_STATE
     *
     * @mbggenerated
     */
    public void setReturnState(String returnState) {
        this.returnState = returnState == null ? null : returnState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.RETURN_DATE
     *
     * @return the value of ET_BUSIFORM_TB.RETURN_DATE
     *
     * @mbggenerated
     */
    public String getReturnDate() {
        return returnDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.RETURN_DATE
     *
     * @param returnDate the value for ET_BUSIFORM_TB.RETURN_DATE
     *
     * @mbggenerated
     */
    public void setReturnDate(String returnDate) {
        this.returnDate = returnDate == null ? null : returnDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.FILE_NAME
     *
     * @return the value of ET_BUSIFORM_TB.FILE_NAME
     *
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.FILE_NAME
     *
     * @param fileName the value for ET_BUSIFORM_TB.FILE_NAME
     *
     * @mbggenerated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.REAL_NAME
     *
     * @return the value of ET_BUSIFORM_TB.REAL_NAME
     *
     * @mbggenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.REAL_NAME
     *
     * @param realName the value for ET_BUSIFORM_TB.REAL_NAME
     *
     * @mbggenerated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.FILE_PATH
     *
     * @return the value of ET_BUSIFORM_TB.FILE_PATH
     *
     * @mbggenerated
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.FILE_PATH
     *
     * @param filePath the value for ET_BUSIFORM_TB.FILE_PATH
     *
     * @mbggenerated
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.FILE_EXT
     *
     * @return the value of ET_BUSIFORM_TB.FILE_EXT
     *
     * @mbggenerated
     */
    public String getFileExt() {
        return fileExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.FILE_EXT
     *
     * @param fileExt the value for ET_BUSIFORM_TB.FILE_EXT
     *
     * @mbggenerated
     */
    public void setFileExt(String fileExt) {
        this.fileExt = fileExt == null ? null : fileExt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.BRASRULECONTEXT_JM
     *
     * @return the value of ET_BUSIFORM_TB.BRASRULECONTEXT_JM
     *
     * @mbggenerated
     */
    public String getBrasrulecontextJm() {
        return brasrulecontextJm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.BRASRULECONTEXT_JM
     *
     * @param brasrulecontextJm the value for ET_BUSIFORM_TB.BRASRULECONTEXT_JM
     *
     * @mbggenerated
     */
    public void setBrasrulecontextJm(String brasrulecontextJm) {
        this.brasrulecontextJm = brasrulecontextJm == null ? null : brasrulecontextJm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.IS_BF
     *
     * @return the value of ET_BUSIFORM_TB.IS_BF
     *
     * @mbggenerated
     */
    public String getIsBf() {
        return isBf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.IS_BF
     *
     * @param isBf the value for ET_BUSIFORM_TB.IS_BF
     *
     * @mbggenerated
     */
    public void setIsBf(String isBf) {
        this.isBf = isBf == null ? null : isBf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.BAKE_USER_NO
     *
     * @return the value of ET_BUSIFORM_TB.BAKE_USER_NO
     *
     * @mbggenerated
     */
    public String getBakeUserNo() {
        return bakeUserNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.BAKE_USER_NO
     *
     * @param bakeUserNo the value for ET_BUSIFORM_TB.BAKE_USER_NO
     *
     * @mbggenerated
     */
    public void setBakeUserNo(String bakeUserNo) {
        this.bakeUserNo = bakeUserNo == null ? null : bakeUserNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.IS_SEE
     *
     * @return the value of ET_BUSIFORM_TB.IS_SEE
     *
     * @mbggenerated
     */
    public String getIsSee() {
        return isSee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.IS_SEE
     *
     * @param isSee the value for ET_BUSIFORM_TB.IS_SEE
     *
     * @mbggenerated
     */
    public void setIsSee(String isSee) {
        this.isSee = isSee == null ? null : isSee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.SEE_DESC
     *
     * @return the value of ET_BUSIFORM_TB.SEE_DESC
     *
     * @mbggenerated
     */
    public String getSeeDesc() {
        return seeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.SEE_DESC
     *
     * @param seeDesc the value for ET_BUSIFORM_TB.SEE_DESC
     *
     * @mbggenerated
     */
    public void setSeeDesc(String seeDesc) {
        this.seeDesc = seeDesc == null ? null : seeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.RISK_TYPE
     *
     * @return the value of ET_BUSIFORM_TB.RISK_TYPE
     *
     * @mbggenerated
     */
    public String getRiskType() {
        return riskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.RISK_TYPE
     *
     * @param riskType the value for ET_BUSIFORM_TB.RISK_TYPE
     *
     * @mbggenerated
     */
    public void setRiskType(String riskType) {
        this.riskType = riskType == null ? null : riskType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.RISK_SOURCE_NO
     *
     * @return the value of ET_BUSIFORM_TB.RISK_SOURCE_NO
     *
     * @mbggenerated
     */
    public String getRiskSourceNo() {
        return riskSourceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.RISK_SOURCE_NO
     *
     * @param riskSourceNo the value for ET_BUSIFORM_TB.RISK_SOURCE_NO
     *
     * @mbggenerated
     */
    public void setRiskSourceNo(String riskSourceNo) {
        this.riskSourceNo = riskSourceNo == null ? null : riskSourceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.RISK_SOURCE_TYPE
     *
     * @return the value of ET_BUSIFORM_TB.RISK_SOURCE_TYPE
     *
     * @mbggenerated
     */
    public String getRiskSourceType() {
        return riskSourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.RISK_SOURCE_TYPE
     *
     * @param riskSourceType the value for ET_BUSIFORM_TB.RISK_SOURCE_TYPE
     *
     * @mbggenerated
     */
    public void setRiskSourceType(String riskSourceType) {
        this.riskSourceType = riskSourceType == null ? null : riskSourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.RISK_SOURCE_NAME
     *
     * @return the value of ET_BUSIFORM_TB.RISK_SOURCE_NAME
     *
     * @mbggenerated
     */
    public String getRiskSourceName() {
        return riskSourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.RISK_SOURCE_NAME
     *
     * @param riskSourceName the value for ET_BUSIFORM_TB.RISK_SOURCE_NAME
     *
     * @mbggenerated
     */
    public void setRiskSourceName(String riskSourceName) {
        this.riskSourceName = riskSourceName == null ? null : riskSourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.RISK_SOURCE_REMAK
     *
     * @return the value of ET_BUSIFORM_TB.RISK_SOURCE_REMAK
     *
     * @mbggenerated
     */
    public String getRiskSourceRemak() {
        return riskSourceRemak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.RISK_SOURCE_REMAK
     *
     * @param riskSourceRemak the value for ET_BUSIFORM_TB.RISK_SOURCE_REMAK
     *
     * @mbggenerated
     */
    public void setRiskSourceRemak(String riskSourceRemak) {
        this.riskSourceRemak = riskSourceRemak == null ? null : riskSourceRemak.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.CREATE_TIME
     *
     * @return the value of ET_BUSIFORM_TB.CREATE_TIME
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.CREATE_TIME
     *
     * @param createTime the value for ET_BUSIFORM_TB.CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.PROC_DATE
     *
     * @return the value of ET_BUSIFORM_TB.PROC_DATE
     *
     * @mbggenerated
     */
    public String getProcDate() {
        return procDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.PROC_DATE
     *
     * @param procDate the value for ET_BUSIFORM_TB.PROC_DATE
     *
     * @mbggenerated
     */
    public void setProcDate(String procDate) {
        this.procDate = procDate == null ? null : procDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.PAR_OVER_DAYS
     *
     * @return the value of ET_BUSIFORM_TB.PAR_OVER_DAYS
     *
     * @mbggenerated
     */
    public BigDecimal getParOverDays() {
        return parOverDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.PAR_OVER_DAYS
     *
     * @param parOverDays the value for ET_BUSIFORM_TB.PAR_OVER_DAYS
     *
     * @mbggenerated
     */
    public void setParOverDays(BigDecimal parOverDays) {
        this.parOverDays = parOverDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.PAR_BACK_DATE
     *
     * @return the value of ET_BUSIFORM_TB.PAR_BACK_DATE
     *
     * @mbggenerated
     */
    public String getParBackDate() {
        return parBackDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.PAR_BACK_DATE
     *
     * @param parBackDate the value for ET_BUSIFORM_TB.PAR_BACK_DATE
     *
     * @mbggenerated
     */
    public void setParBackDate(String parBackDate) {
        this.parBackDate = parBackDate == null ? null : parBackDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.PAR_DEAL_DATE
     *
     * @return the value of ET_BUSIFORM_TB.PAR_DEAL_DATE
     *
     * @mbggenerated
     */
    public String getParDealDate() {
        return parDealDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.PAR_DEAL_DATE
     *
     * @param parDealDate the value for ET_BUSIFORM_TB.PAR_DEAL_DATE
     *
     * @mbggenerated
     */
    public void setParDealDate(String parDealDate) {
        this.parDealDate = parDealDate == null ? null : parDealDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ET_BUSIFORM_TB.ORG_DEAL_DATE
     *
     * @return the value of ET_BUSIFORM_TB.ORG_DEAL_DATE
     *
     * @mbggenerated
     */
    public String getOrgDealDate() {
        return orgDealDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ET_BUSIFORM_TB.ORG_DEAL_DATE
     *
     * @param orgDealDate the value for ET_BUSIFORM_TB.ORG_DEAL_DATE
     *
     * @mbggenerated
     */
    public void setOrgDealDate(String orgDealDate) {
        this.orgDealDate = orgDealDate == null ? null : orgDealDate.trim();
    }

	public String getQdSlipMoid() {
		return qdSlipMoid;
	}

	public void setQdSlipMoid(String qdSlipMoid) {
		 this.qdSlipMoid = qdSlipMoid == null ? null : qdSlipMoid.trim();
	}
}