package com.sunyard.ars.system.dao.othersys;

import java.util.List;

import com.sunyard.ars.system.bean.othersys.ArmsColumn;
import com.sunyard.ars.system.bean.othersys.SmRealarmsSet;

public interface SmRealarmsSetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_REALARMS_SET_TB
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String codeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_REALARMS_SET_TB
     *
     * @mbggenerated
     */
    int insert(SmRealarmsSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_REALARMS_SET_TB
     *
     * @mbggenerated
     */
    int insertSelective(SmRealarmsSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_REALARMS_SET_TB
     *
     * @mbggenerated
     */
    SmRealarmsSet selectByPrimaryKey(String codeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_REALARMS_SET_TB
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SmRealarmsSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_REALARMS_SET_TB
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmRealarmsSet record);
    
    List<ArmsColumn> selectTableColumns(String tableName);
    
    List<SmRealarmsSet> selectSmRealarmsSetList (SmRealarmsSet record);
    
    SmRealarmsSet selectModelList (String codeId);
}