package com.sunyard.ars.file.pojo.ma;


public class HotKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_HOTKEY_TB.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_HOTKEY_TB.MODULE_LIST
     *
     * @mbg.generated
     */
    private String moduleList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_HOTKEY_TB.USER_NO
     *
     * @mbg.generated
     */
    private String userNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_HOTKEY_TB.FUNCTION_ID
     *
     * @mbg.generated
     */
    private String functionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_HOTKEY_TB.KEY_CODE1
     *
     * @mbg.generated
     */
    private String keyCode1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_HOTKEY_TB.KEY_CODE2
     *
     * @mbg.generated
     */
    private String keyCode2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_HOTKEY_TB.ID
     *
     * @return the value of SM_HOTKEY_TB.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_HOTKEY_TB.ID
     *
     * @param id the value for SM_HOTKEY_TB.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_HOTKEY_TB.MODULE_LIST
     *
     * @return the value of SM_HOTKEY_TB.MODULE_LIST
     *
     * @mbg.generated
     */
    public String getModuleList() {
        return moduleList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_HOTKEY_TB.MODULE_LIST
     *
     * @param moduleList the value for SM_HOTKEY_TB.MODULE_LIST
     *
     * @mbg.generated
     */
    public void setModuleList(String moduleList) {
        this.moduleList = moduleList == null ? null : moduleList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_HOTKEY_TB.USER_NO
     *
     * @return the value of SM_HOTKEY_TB.USER_NO
     *
     * @mbg.generated
     */
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_HOTKEY_TB.USER_NO
     *
     * @param userNo the value for SM_HOTKEY_TB.USER_NO
     *
     * @mbg.generated
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo == null ? null : userNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_HOTKEY_TB.FUNCTION_ID
     *
     * @return the value of SM_HOTKEY_TB.FUNCTION_ID
     *
     * @mbg.generated
     */
    public String getFunctionId() {
        return functionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_HOTKEY_TB.FUNCTION_ID
     *
     * @param functionId the value for SM_HOTKEY_TB.FUNCTION_ID
     *
     * @mbg.generated
     */
    public void setFunctionId(String functionId) {
        this.functionId = functionId == null ? null : functionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_HOTKEY_TB.KEY_CODE1
     *
     * @return the value of SM_HOTKEY_TB.KEY_CODE1
     *
     * @mbg.generated
     */
    public String getKeyCode1() {
        return keyCode1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_HOTKEY_TB.KEY_CODE1
     *
     * @param keyCode1 the value for SM_HOTKEY_TB.KEY_CODE1
     *
     * @mbg.generated
     */
    public void setKeyCode1(String keyCode1) {
        this.keyCode1 = keyCode1 == null ? null : keyCode1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_HOTKEY_TB.KEY_CODE2
     *
     * @return the value of SM_HOTKEY_TB.KEY_CODE2
     *
     * @mbg.generated
     */
    public String getKeyCode2() {
        return keyCode2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_HOTKEY_TB.KEY_CODE2
     *
     * @param keyCode2 the value for SM_HOTKEY_TB.KEY_CODE2
     *
     * @mbg.generated
     */
    public void setKeyCode2(String keyCode2) {
        this.keyCode2 = keyCode2 == null ? null : keyCode2.trim();
    }
}