package com.sunyard.ars.system.bean.othersys;

public class SmRealarmsSet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_REALARMS_SET_TB.CODE_ID
     *
     * @mbggenerated
     */
    private String codeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_REALARMS_SET_TB.TABLE_NAME
     *
     * @mbggenerated
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_REALARMS_SET_TB.SEPARATOR
     *
     * @mbggenerated
     */
    private String separator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_REALARMS_SET_TB.MODE_IDS
     *
     * @mbggenerated
     */
    private String modeIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_REALARMS_SET_TB.REAL_DESC
     *
     * @mbggenerated
     */
    private String realDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SM_REALARMS_SET_TB.ARMS_FLAG
     *
     * @mbggenerated
     */
    private String armsFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_REALARMS_SET_TB.CODE_ID
     *
     * @return the value of SM_REALARMS_SET_TB.CODE_ID
     *
     * @mbggenerated
     */
    public String getCodeId() {
        return codeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_REALARMS_SET_TB.CODE_ID
     *
     * @param codeId the value for SM_REALARMS_SET_TB.CODE_ID
     *
     * @mbggenerated
     */
    public void setCodeId(String codeId) {
        this.codeId = codeId == null ? null : codeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_REALARMS_SET_TB.TABLE_NAME
     *
     * @return the value of SM_REALARMS_SET_TB.TABLE_NAME
     *
     * @mbggenerated
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_REALARMS_SET_TB.TABLE_NAME
     *
     * @param tableName the value for SM_REALARMS_SET_TB.TABLE_NAME
     *
     * @mbggenerated
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_REALARMS_SET_TB.SEPARATOR
     *
     * @return the value of SM_REALARMS_SET_TB.SEPARATOR
     *
     * @mbggenerated
     */
    public String getSeparator() {
        return separator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_REALARMS_SET_TB.SEPARATOR
     *
     * @param separator the value for SM_REALARMS_SET_TB.SEPARATOR
     *
     * @mbggenerated
     */
    public void setSeparator(String separator) {
        this.separator = separator == null ? null : separator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_REALARMS_SET_TB.MODE_IDS
     *
     * @return the value of SM_REALARMS_SET_TB.MODE_IDS
     *
     * @mbggenerated
     */
    public String getModeIds() {
        return modeIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_REALARMS_SET_TB.MODE_IDS
     *
     * @param modeIds the value for SM_REALARMS_SET_TB.MODE_IDS
     *
     * @mbggenerated
     */
    public void setModeIds(String modeIds) {
        this.modeIds = modeIds == null ? null : modeIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_REALARMS_SET_TB.REAL_DESC
     *
     * @return the value of SM_REALARMS_SET_TB.REAL_DESC
     *
     * @mbggenerated
     */
    public String getRealDesc() {
        return realDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_REALARMS_SET_TB.REAL_DESC
     *
     * @param realDesc the value for SM_REALARMS_SET_TB.REAL_DESC
     *
     * @mbggenerated
     */
    public void setRealDesc(String realDesc) {
        this.realDesc = realDesc == null ? null : realDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SM_REALARMS_SET_TB.ARMS_FLAG
     *
     * @return the value of SM_REALARMS_SET_TB.ARMS_FLAG
     *
     * @mbggenerated
     */
    public String getArmsFlag() {
        return armsFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SM_REALARMS_SET_TB.ARMS_FLAG
     *
     * @param armsFlag the value for SM_REALARMS_SET_TB.ARMS_FLAG
     *
     * @mbggenerated
     */
    public void setArmsFlag(String armsFlag) {
        this.armsFlag = armsFlag == null ? null : armsFlag.trim();
    }
}