package com.sunyard.ars.file.pojo.oa;

import java.math.BigDecimal;

public class FlowAll {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.SEQ_ID
     *
     * @mbg.generated
     */
	private String updFlag;
	private String customerType;
	private String transType;
	private String transAccount;
	private String jnrstRate;
	private String jnrstChqDays;
	private String jnrstAccType;
	private String glClassCode;
	private String glassCode;
	private String oldSiteNo;
	private String oldOperatorNo;
	private String recordType;
	private String recordTime;
	private String archiveDate;
	
	
    public String getUpdFlag() {
		return updFlag;
	}

	public void setUpdFlag(String updFlag) {
		this.updFlag = updFlag;
	}

	public String getCustomerType() {
		return customerType;
	}

	public void setCustomerType(String customerType) {
		this.customerType = customerType;
	}

	public String getTransType() {
		return transType;
	}

	public void setTransType(String transType) {
		this.transType = transType;
	}

	public String getTransAccount() {
		return transAccount;
	}

	public void setTransAccount(String transAccount) {
		this.transAccount = transAccount;
	}

	public String getJnrstRate() {
		return jnrstRate;
	}

	public void setJnrstRate(String jnrstRate) {
		this.jnrstRate = jnrstRate;
	}

	public String getJnrstChqDays() {
		return jnrstChqDays;
	}

	public void setJnrstChqDays(String jnrstChqDays) {
		this.jnrstChqDays = jnrstChqDays;
	}

	public String getJnrstAccType() {
		return jnrstAccType;
	}

	public void setJnrstAccType(String jnrstAccType) {
		this.jnrstAccType = jnrstAccType;
	}

	public String getGlClassCode() {
		return glClassCode;
	}

	public void setGlClassCode(String glClassCode) {
		this.glClassCode = glClassCode;
	}

	public String getGlassCode() {
		return glassCode;
	}

	public void setGlassCode(String glassCode) {
		this.glassCode = glassCode;
	}

	public String getOldSiteNo() {
		return oldSiteNo;
	}

	public void setOldSiteNo(String oldSiteNo) {
		this.oldSiteNo = oldSiteNo;
	}

	public String getOldOperatorNo() {
		return oldOperatorNo;
	}

	public void setOldOperatorNo(String oldOperatorNo) {
		this.oldOperatorNo = oldOperatorNo;
	}

	public String getRecordType() {
		return recordType;
	}

	public void setRecordType(String recordType) {
		this.recordType = recordType;
	}

	public String getRecordTime() {
		return recordTime;
	}

	public void setRecordTime(String recordTime) {
		this.recordTime = recordTime;
	}


	public String getArchiveDate() {
		return archiveDate;
	}

	public void setArchiveDate(String archiveDate) {
		this.archiveDate = archiveDate;
	}

	private BigDecimal seqId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.OCCUR_DATE
     *
     * @mbg.generated
     */
    private String occurDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.OCCUR_TIME
     *
     * @mbg.generated
     */
    private String occurTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.FLOW_ID
     *
     * @mbg.generated
     */
    private String flowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.SITE_NO
     *
     * @mbg.generated
     */
    private String siteNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.OPERATOR_NO
     *
     * @mbg.generated
     */
    private String operatorNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.GRANT_NO
     *
     * @mbg.generated
     */
    private String grantNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.ACCOUNT
     *
     * @mbg.generated
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.VOUH_NO
     *
     * @mbg.generated
     */
    private String vouhNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.OPP_ACCT
     *
     * @mbg.generated
     */
    private String oppAcct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.AMOUNT
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.BALANCE
     *
     * @mbg.generated
     */
    private BigDecimal balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.TX_CODE
     *
     * @mbg.generated
     */
    private String txCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.SUBJECT_NO
     *
     * @mbg.generated
     */
    private String subjectNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.CD_FLAG
     *
     * @mbg.generated
     */
    private String cdFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.CURRENCY_TYPE
     *
     * @mbg.generated
     */
    private String currencyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.CUSTOMER_ID
     *
     * @mbg.generated
     */
    private String customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.CLIENT_NAME
     *
     * @mbg.generated
     */
    private String clientName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.DATA_FLAG
     *
     * @mbg.generated
     */
    private String dataFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.CHECK_FLAG
     *
     * @mbg.generated
     */
    private String checkFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.LSERIAL_NO
     *
     * @mbg.generated
     */
    private String lserialNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.CITY_NO
     *
     * @mbg.generated
     */
    private String cityNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.MEMO
     *
     * @mbg.generated
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.ACCT_NAME
     *
     * @mbg.generated
     */
    private String acctName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.TABLEFROM
     *
     * @mbg.generated
     */
    private String tablefrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.EX_SERIAL
     *
     * @mbg.generated
     */
    private String exSerial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.OPP_CLIENT_NAME
     *
     * @mbg.generated
     */
    private String oppClientName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.WORKCODE
     *
     * @mbg.generated
     */
    private String workcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.NEW_ACCOUNT
     *
     * @mbg.generated
     */
    private String newAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.PRODCODE
     *
     * @mbg.generated
     */
    private String prodcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.PRODNBR
     *
     * @mbg.generated
     */
    private String prodnbr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.SERVCODE
     *
     * @mbg.generated
     */
    private String servcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.TX_NAME
     *
     * @mbg.generated
     */
    private String txName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.PAYINTAMT
     *
     * @mbg.generated
     */
    private BigDecimal payintamt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.GETINTAMT
     *
     * @mbg.generated
     */
    private BigDecimal getintamt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.T_CHKNO
     *
     * @mbg.generated
     */
    private String tChkno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.CODE
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.EXECUTE_RATE
     *
     * @mbg.generated
     */
    private String executeRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.LOAN_NO
     *
     * @mbg.generated
     */
    private String loanNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.VCHR_NO
     *
     * @mbg.generated
     */
    private String vchrNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.VCHR_TYPE
     *
     * @mbg.generated
     */
    private String vchrType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.AUTH_OPER
     *
     * @mbg.generated
     */
    private String authOper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.ASSO_SERIAL
     *
     * @mbg.generated
     */
    private String assoSerial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.ASSO_DATE
     *
     * @mbg.generated
     */
    private BigDecimal assoDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.CARD_NO
     *
     * @mbg.generated
     */
    private String cardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.CLIENT_RISK
     *
     * @mbg.generated
     */
    private BigDecimal clientRisk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.TARG_BANK_ACC
     *
     * @mbg.generated
     */
    private String targBankAcc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.DIV_MODE
     *
     * @mbg.generated
     */
    private String divMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.LARG_RED_FLAG
     *
     * @mbg.generated
     */
    private String largRedFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.VOL
     *
     * @mbg.generated
     */
    private BigDecimal vol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.UNIT_NO
     *
     * @mbg.generated
     */
    private String unitNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FL_FLOW_TB.REM_SRL_NUM
     *
     * @mbg.generated
     */
    private String remSrlNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.SEQ_ID
     *
     * @return the value of FL_FLOW_TB.SEQ_ID
     *
     * @mbg.generated
     */
    public BigDecimal getSeqId() {
        return seqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.SEQ_ID
     *
     * @param seqId the value for FL_FLOW_TB.SEQ_ID
     *
     * @mbg.generated
     */
    public void setSeqId(BigDecimal seqId) {
        this.seqId = seqId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.OCCUR_DATE
     *
     * @return the value of FL_FLOW_TB.OCCUR_DATE
     *
     * @mbg.generated
     */
    public String getOccurDate() {
        return occurDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.OCCUR_DATE
     *
     * @param occurDate the value for FL_FLOW_TB.OCCUR_DATE
     *
     * @mbg.generated
     */
    public void setOccurDate(String occurDate) {
        this.occurDate = occurDate == null ? null : occurDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.OCCUR_TIME
     *
     * @return the value of FL_FLOW_TB.OCCUR_TIME
     *
     * @mbg.generated
     */
    public String getOccurTime() {
        return occurTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.OCCUR_TIME
     *
     * @param occurTime the value for FL_FLOW_TB.OCCUR_TIME
     *
     * @mbg.generated
     */
    public void setOccurTime(String occurTime) {
        this.occurTime = occurTime == null ? null : occurTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.FLOW_ID
     *
     * @return the value of FL_FLOW_TB.FLOW_ID
     *
     * @mbg.generated
     */
    public String getFlowId() {
        return flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.FLOW_ID
     *
     * @param flowId the value for FL_FLOW_TB.FLOW_ID
     *
     * @mbg.generated
     */
    public void setFlowId(String flowId) {
        this.flowId = flowId == null ? null : flowId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.SITE_NO
     *
     * @return the value of FL_FLOW_TB.SITE_NO
     *
     * @mbg.generated
     */
    public String getSiteNo() {
        return siteNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.SITE_NO
     *
     * @param siteNo the value for FL_FLOW_TB.SITE_NO
     *
     * @mbg.generated
     */
    public void setSiteNo(String siteNo) {
        this.siteNo = siteNo == null ? null : siteNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.OPERATOR_NO
     *
     * @return the value of FL_FLOW_TB.OPERATOR_NO
     *
     * @mbg.generated
     */
    public String getOperatorNo() {
        return operatorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.OPERATOR_NO
     *
     * @param operatorNo the value for FL_FLOW_TB.OPERATOR_NO
     *
     * @mbg.generated
     */
    public void setOperatorNo(String operatorNo) {
        this.operatorNo = operatorNo == null ? null : operatorNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.GRANT_NO
     *
     * @return the value of FL_FLOW_TB.GRANT_NO
     *
     * @mbg.generated
     */
    public String getGrantNo() {
        return grantNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.GRANT_NO
     *
     * @param grantNo the value for FL_FLOW_TB.GRANT_NO
     *
     * @mbg.generated
     */
    public void setGrantNo(String grantNo) {
        this.grantNo = grantNo == null ? null : grantNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.ACCOUNT
     *
     * @return the value of FL_FLOW_TB.ACCOUNT
     *
     * @mbg.generated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.ACCOUNT
     *
     * @param account the value for FL_FLOW_TB.ACCOUNT
     *
     * @mbg.generated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.VOUH_NO
     *
     * @return the value of FL_FLOW_TB.VOUH_NO
     *
     * @mbg.generated
     */
    public String getVouhNo() {
        return vouhNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.VOUH_NO
     *
     * @param vouhNo the value for FL_FLOW_TB.VOUH_NO
     *
     * @mbg.generated
     */
    public void setVouhNo(String vouhNo) {
        this.vouhNo = vouhNo == null ? null : vouhNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.OPP_ACCT
     *
     * @return the value of FL_FLOW_TB.OPP_ACCT
     *
     * @mbg.generated
     */
    public String getOppAcct() {
        return oppAcct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.OPP_ACCT
     *
     * @param oppAcct the value for FL_FLOW_TB.OPP_ACCT
     *
     * @mbg.generated
     */
    public void setOppAcct(String oppAcct) {
        this.oppAcct = oppAcct == null ? null : oppAcct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.AMOUNT
     *
     * @return the value of FL_FLOW_TB.AMOUNT
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.AMOUNT
     *
     * @param amount the value for FL_FLOW_TB.AMOUNT
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.BALANCE
     *
     * @return the value of FL_FLOW_TB.BALANCE
     *
     * @mbg.generated
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.BALANCE
     *
     * @param balance the value for FL_FLOW_TB.BALANCE
     *
     * @mbg.generated
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.TX_CODE
     *
     * @return the value of FL_FLOW_TB.TX_CODE
     *
     * @mbg.generated
     */
    public String getTxCode() {
        return txCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.TX_CODE
     *
     * @param txCode the value for FL_FLOW_TB.TX_CODE
     *
     * @mbg.generated
     */
    public void setTxCode(String txCode) {
        this.txCode = txCode == null ? null : txCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.SUBJECT_NO
     *
     * @return the value of FL_FLOW_TB.SUBJECT_NO
     *
     * @mbg.generated
     */
    public String getSubjectNo() {
        return subjectNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.SUBJECT_NO
     *
     * @param subjectNo the value for FL_FLOW_TB.SUBJECT_NO
     *
     * @mbg.generated
     */
    public void setSubjectNo(String subjectNo) {
        this.subjectNo = subjectNo == null ? null : subjectNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.CD_FLAG
     *
     * @return the value of FL_FLOW_TB.CD_FLAG
     *
     * @mbg.generated
     */
    public String getCdFlag() {
        return cdFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.CD_FLAG
     *
     * @param cdFlag the value for FL_FLOW_TB.CD_FLAG
     *
     * @mbg.generated
     */
    public void setCdFlag(String cdFlag) {
        this.cdFlag = cdFlag == null ? null : cdFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.CURRENCY_TYPE
     *
     * @return the value of FL_FLOW_TB.CURRENCY_TYPE
     *
     * @mbg.generated
     */
    public String getCurrencyType() {
        return currencyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.CURRENCY_TYPE
     *
     * @param currencyType the value for FL_FLOW_TB.CURRENCY_TYPE
     *
     * @mbg.generated
     */
    public void setCurrencyType(String currencyType) {
        this.currencyType = currencyType == null ? null : currencyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.CUSTOMER_ID
     *
     * @return the value of FL_FLOW_TB.CUSTOMER_ID
     *
     * @mbg.generated
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.CUSTOMER_ID
     *
     * @param customerId the value for FL_FLOW_TB.CUSTOMER_ID
     *
     * @mbg.generated
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.CLIENT_NAME
     *
     * @return the value of FL_FLOW_TB.CLIENT_NAME
     *
     * @mbg.generated
     */
    public String getClientName() {
        return clientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.CLIENT_NAME
     *
     * @param clientName the value for FL_FLOW_TB.CLIENT_NAME
     *
     * @mbg.generated
     */
    public void setClientName(String clientName) {
        this.clientName = clientName == null ? null : clientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.DATA_FLAG
     *
     * @return the value of FL_FLOW_TB.DATA_FLAG
     *
     * @mbg.generated
     */
    public String getDataFlag() {
        return dataFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.DATA_FLAG
     *
     * @param dataFlag the value for FL_FLOW_TB.DATA_FLAG
     *
     * @mbg.generated
     */
    public void setDataFlag(String dataFlag) {
        this.dataFlag = dataFlag == null ? null : dataFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.CHECK_FLAG
     *
     * @return the value of FL_FLOW_TB.CHECK_FLAG
     *
     * @mbg.generated
     */
    public String getCheckFlag() {
        return checkFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.CHECK_FLAG
     *
     * @param checkFlag the value for FL_FLOW_TB.CHECK_FLAG
     *
     * @mbg.generated
     */
    public void setCheckFlag(String checkFlag) {
        this.checkFlag = checkFlag == null ? null : checkFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.LSERIAL_NO
     *
     * @return the value of FL_FLOW_TB.LSERIAL_NO
     *
     * @mbg.generated
     */
    public String getLserialNo() {
        return lserialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.LSERIAL_NO
     *
     * @param lserialNo the value for FL_FLOW_TB.LSERIAL_NO
     *
     * @mbg.generated
     */
    public void setLserialNo(String lserialNo) {
        this.lserialNo = lserialNo == null ? null : lserialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.CITY_NO
     *
     * @return the value of FL_FLOW_TB.CITY_NO
     *
     * @mbg.generated
     */
    public String getCityNo() {
        return cityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.CITY_NO
     *
     * @param cityNo the value for FL_FLOW_TB.CITY_NO
     *
     * @mbg.generated
     */
    public void setCityNo(String cityNo) {
        this.cityNo = cityNo == null ? null : cityNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.MEMO
     *
     * @return the value of FL_FLOW_TB.MEMO
     *
     * @mbg.generated
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.MEMO
     *
     * @param memo the value for FL_FLOW_TB.MEMO
     *
     * @mbg.generated
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.ACCT_NAME
     *
     * @return the value of FL_FLOW_TB.ACCT_NAME
     *
     * @mbg.generated
     */
    public String getAcctName() {
        return acctName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.ACCT_NAME
     *
     * @param acctName the value for FL_FLOW_TB.ACCT_NAME
     *
     * @mbg.generated
     */
    public void setAcctName(String acctName) {
        this.acctName = acctName == null ? null : acctName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.TABLEFROM
     *
     * @return the value of FL_FLOW_TB.TABLEFROM
     *
     * @mbg.generated
     */
    public String getTablefrom() {
        return tablefrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.TABLEFROM
     *
     * @param tablefrom the value for FL_FLOW_TB.TABLEFROM
     *
     * @mbg.generated
     */
    public void setTablefrom(String tablefrom) {
        this.tablefrom = tablefrom == null ? null : tablefrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.EX_SERIAL
     *
     * @return the value of FL_FLOW_TB.EX_SERIAL
     *
     * @mbg.generated
     */
    public String getExSerial() {
        return exSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.EX_SERIAL
     *
     * @param exSerial the value for FL_FLOW_TB.EX_SERIAL
     *
     * @mbg.generated
     */
    public void setExSerial(String exSerial) {
        this.exSerial = exSerial == null ? null : exSerial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.OPP_CLIENT_NAME
     *
     * @return the value of FL_FLOW_TB.OPP_CLIENT_NAME
     *
     * @mbg.generated
     */
    public String getOppClientName() {
        return oppClientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.OPP_CLIENT_NAME
     *
     * @param oppClientName the value for FL_FLOW_TB.OPP_CLIENT_NAME
     *
     * @mbg.generated
     */
    public void setOppClientName(String oppClientName) {
        this.oppClientName = oppClientName == null ? null : oppClientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.WORKCODE
     *
     * @return the value of FL_FLOW_TB.WORKCODE
     *
     * @mbg.generated
     */
    public String getWorkcode() {
        return workcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.WORKCODE
     *
     * @param workcode the value for FL_FLOW_TB.WORKCODE
     *
     * @mbg.generated
     */
    public void setWorkcode(String workcode) {
        this.workcode = workcode == null ? null : workcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.NEW_ACCOUNT
     *
     * @return the value of FL_FLOW_TB.NEW_ACCOUNT
     *
     * @mbg.generated
     */
    public String getNewAccount() {
        return newAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.NEW_ACCOUNT
     *
     * @param newAccount the value for FL_FLOW_TB.NEW_ACCOUNT
     *
     * @mbg.generated
     */
    public void setNewAccount(String newAccount) {
        this.newAccount = newAccount == null ? null : newAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.PRODCODE
     *
     * @return the value of FL_FLOW_TB.PRODCODE
     *
     * @mbg.generated
     */
    public String getProdcode() {
        return prodcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.PRODCODE
     *
     * @param prodcode the value for FL_FLOW_TB.PRODCODE
     *
     * @mbg.generated
     */
    public void setProdcode(String prodcode) {
        this.prodcode = prodcode == null ? null : prodcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.PRODNBR
     *
     * @return the value of FL_FLOW_TB.PRODNBR
     *
     * @mbg.generated
     */
    public String getProdnbr() {
        return prodnbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.PRODNBR
     *
     * @param prodnbr the value for FL_FLOW_TB.PRODNBR
     *
     * @mbg.generated
     */
    public void setProdnbr(String prodnbr) {
        this.prodnbr = prodnbr == null ? null : prodnbr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.SERVCODE
     *
     * @return the value of FL_FLOW_TB.SERVCODE
     *
     * @mbg.generated
     */
    public String getServcode() {
        return servcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.SERVCODE
     *
     * @param servcode the value for FL_FLOW_TB.SERVCODE
     *
     * @mbg.generated
     */
    public void setServcode(String servcode) {
        this.servcode = servcode == null ? null : servcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.TX_NAME
     *
     * @return the value of FL_FLOW_TB.TX_NAME
     *
     * @mbg.generated
     */
    public String getTxName() {
        return txName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.TX_NAME
     *
     * @param txName the value for FL_FLOW_TB.TX_NAME
     *
     * @mbg.generated
     */
    public void setTxName(String txName) {
        this.txName = txName == null ? null : txName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.PAYINTAMT
     *
     * @return the value of FL_FLOW_TB.PAYINTAMT
     *
     * @mbg.generated
     */
    public BigDecimal getPayintamt() {
        return payintamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.PAYINTAMT
     *
     * @param payintamt the value for FL_FLOW_TB.PAYINTAMT
     *
     * @mbg.generated
     */
    public void setPayintamt(BigDecimal payintamt) {
        this.payintamt = payintamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.GETINTAMT
     *
     * @return the value of FL_FLOW_TB.GETINTAMT
     *
     * @mbg.generated
     */
    public BigDecimal getGetintamt() {
        return getintamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.GETINTAMT
     *
     * @param getintamt the value for FL_FLOW_TB.GETINTAMT
     *
     * @mbg.generated
     */
    public void setGetintamt(BigDecimal getintamt) {
        this.getintamt = getintamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.T_CHKNO
     *
     * @return the value of FL_FLOW_TB.T_CHKNO
     *
     * @mbg.generated
     */
    public String gettChkno() {
        return tChkno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.T_CHKNO
     *
     * @param tChkno the value for FL_FLOW_TB.T_CHKNO
     *
     * @mbg.generated
     */
    public void settChkno(String tChkno) {
        this.tChkno = tChkno == null ? null : tChkno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.CODE
     *
     * @return the value of FL_FLOW_TB.CODE
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.CODE
     *
     * @param code the value for FL_FLOW_TB.CODE
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.EXECUTE_RATE
     *
     * @return the value of FL_FLOW_TB.EXECUTE_RATE
     *
     * @mbg.generated
     */
    public String getExecuteRate() {
        return executeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.EXECUTE_RATE
     *
     * @param executeRate the value for FL_FLOW_TB.EXECUTE_RATE
     *
     * @mbg.generated
     */
    public void setExecuteRate(String executeRate) {
        this.executeRate = executeRate == null ? null : executeRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.LOAN_NO
     *
     * @return the value of FL_FLOW_TB.LOAN_NO
     *
     * @mbg.generated
     */
    public String getLoanNo() {
        return loanNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.LOAN_NO
     *
     * @param loanNo the value for FL_FLOW_TB.LOAN_NO
     *
     * @mbg.generated
     */
    public void setLoanNo(String loanNo) {
        this.loanNo = loanNo == null ? null : loanNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.VCHR_NO
     *
     * @return the value of FL_FLOW_TB.VCHR_NO
     *
     * @mbg.generated
     */
    public String getVchrNo() {
        return vchrNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.VCHR_NO
     *
     * @param vchrNo the value for FL_FLOW_TB.VCHR_NO
     *
     * @mbg.generated
     */
    public void setVchrNo(String vchrNo) {
        this.vchrNo = vchrNo == null ? null : vchrNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.VCHR_TYPE
     *
     * @return the value of FL_FLOW_TB.VCHR_TYPE
     *
     * @mbg.generated
     */
    public String getVchrType() {
        return vchrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.VCHR_TYPE
     *
     * @param vchrType the value for FL_FLOW_TB.VCHR_TYPE
     *
     * @mbg.generated
     */
    public void setVchrType(String vchrType) {
        this.vchrType = vchrType == null ? null : vchrType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.AUTH_OPER
     *
     * @return the value of FL_FLOW_TB.AUTH_OPER
     *
     * @mbg.generated
     */
    public String getAuthOper() {
        return authOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.AUTH_OPER
     *
     * @param authOper the value for FL_FLOW_TB.AUTH_OPER
     *
     * @mbg.generated
     */
    public void setAuthOper(String authOper) {
        this.authOper = authOper == null ? null : authOper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.ASSO_SERIAL
     *
     * @return the value of FL_FLOW_TB.ASSO_SERIAL
     *
     * @mbg.generated
     */
    public String getAssoSerial() {
        return assoSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.ASSO_SERIAL
     *
     * @param assoSerial the value for FL_FLOW_TB.ASSO_SERIAL
     *
     * @mbg.generated
     */
    public void setAssoSerial(String assoSerial) {
        this.assoSerial = assoSerial == null ? null : assoSerial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.ASSO_DATE
     *
     * @return the value of FL_FLOW_TB.ASSO_DATE
     *
     * @mbg.generated
     */
    public BigDecimal getAssoDate() {
        return assoDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.ASSO_DATE
     *
     * @param assoDate the value for FL_FLOW_TB.ASSO_DATE
     *
     * @mbg.generated
     */
    public void setAssoDate(BigDecimal assoDate) {
        this.assoDate = assoDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.CARD_NO
     *
     * @return the value of FL_FLOW_TB.CARD_NO
     *
     * @mbg.generated
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.CARD_NO
     *
     * @param cardNo the value for FL_FLOW_TB.CARD_NO
     *
     * @mbg.generated
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.CLIENT_RISK
     *
     * @return the value of FL_FLOW_TB.CLIENT_RISK
     *
     * @mbg.generated
     */
    public BigDecimal getClientRisk() {
        return clientRisk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.CLIENT_RISK
     *
     * @param clientRisk the value for FL_FLOW_TB.CLIENT_RISK
     *
     * @mbg.generated
     */
    public void setClientRisk(BigDecimal clientRisk) {
        this.clientRisk = clientRisk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.TARG_BANK_ACC
     *
     * @return the value of FL_FLOW_TB.TARG_BANK_ACC
     *
     * @mbg.generated
     */
    public String getTargBankAcc() {
        return targBankAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.TARG_BANK_ACC
     *
     * @param targBankAcc the value for FL_FLOW_TB.TARG_BANK_ACC
     *
     * @mbg.generated
     */
    public void setTargBankAcc(String targBankAcc) {
        this.targBankAcc = targBankAcc == null ? null : targBankAcc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.DIV_MODE
     *
     * @return the value of FL_FLOW_TB.DIV_MODE
     *
     * @mbg.generated
     */
    public String getDivMode() {
        return divMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.DIV_MODE
     *
     * @param divMode the value for FL_FLOW_TB.DIV_MODE
     *
     * @mbg.generated
     */
    public void setDivMode(String divMode) {
        this.divMode = divMode == null ? null : divMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.LARG_RED_FLAG
     *
     * @return the value of FL_FLOW_TB.LARG_RED_FLAG
     *
     * @mbg.generated
     */
    public String getLargRedFlag() {
        return largRedFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.LARG_RED_FLAG
     *
     * @param largRedFlag the value for FL_FLOW_TB.LARG_RED_FLAG
     *
     * @mbg.generated
     */
    public void setLargRedFlag(String largRedFlag) {
        this.largRedFlag = largRedFlag == null ? null : largRedFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.VOL
     *
     * @return the value of FL_FLOW_TB.VOL
     *
     * @mbg.generated
     */
    public BigDecimal getVol() {
        return vol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.VOL
     *
     * @param vol the value for FL_FLOW_TB.VOL
     *
     * @mbg.generated
     */
    public void setVol(BigDecimal vol) {
        this.vol = vol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.UNIT_NO
     *
     * @return the value of FL_FLOW_TB.UNIT_NO
     *
     * @mbg.generated
     */
    public String getUnitNo() {
        return unitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.UNIT_NO
     *
     * @param unitNo the value for FL_FLOW_TB.UNIT_NO
     *
     * @mbg.generated
     */
    public void setUnitNo(String unitNo) {
        this.unitNo = unitNo == null ? null : unitNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FL_FLOW_TB.REM_SRL_NUM
     *
     * @return the value of FL_FLOW_TB.REM_SRL_NUM
     *
     * @mbg.generated
     */
    public String getRemSrlNum() {
        return remSrlNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FL_FLOW_TB.REM_SRL_NUM
     *
     * @param remSrlNum the value for FL_FLOW_TB.REM_SRL_NUM
     *
     * @mbg.generated
     */
    public void setRemSrlNum(String remSrlNum) {
        this.remSrlNum = remSrlNum == null ? null : remSrlNum.trim();
    }
}