package com.sunyard.ars.system.dao.sc;

import com.sunyard.ars.system.bean.sc.BusinessType;
import java.math.BigDecimal;
import java.util.List;

public interface BusinessTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUNARS.SM_BUSINESS_TB
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal businessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUNARS.SM_BUSINESS_TB
     *
     * @mbggenerated
     */
    int insert(BusinessType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUNARS.SM_BUSINESS_TB
     *
     * @mbggenerated
     */
    int insertSelective(BusinessType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUNARS.SM_BUSINESS_TB
     *
     * @mbggenerated
     */
    BusinessType selectByPrimaryKey(BigDecimal businessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUNARS.SM_BUSINESS_TB
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BusinessType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUNARS.SM_BUSINESS_TB
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BusinessType record);
    
    /**
     * 根据对象中的非空属性作为查询条件
     * @return
     */
    List<BusinessType> selectBySelective(BusinessType record);
    
    /**
     * 获取最大业务ID号码。
     * @return
     */
    BigDecimal getMaxBusinessId();
}