package com.sunyard.ars.system.dao.sc;


import java.util.List;
import java.util.Map;

import com.sunyard.ars.common.pojo.Dictionary;
import org.apache.ibatis.annotations.Param;

public interface DictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_DICTIONARY_TB
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("fieldName") String fieldName, @Param("code") String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_DICTIONARY_TB
     *
     * @mbggenerated
     */
    int insert(Dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_DICTIONARY_TB
     *
     * @mbggenerated
     */
    int insertSelective(Dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_DICTIONARY_TB
     *
     * @mbggenerated
     */
    Dictionary selectByPrimaryKey(@Param("fieldName") String fieldName, @Param("code") String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_DICTIONARY_TB
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_DICTIONARY_TB
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Dictionary record);
    
    /**
     * 根据对象的非空值作为条件查询。
     * @param record
     * @return
     */
    List<Dictionary> selectBySelective(Dictionary record);

	List<Map<String, Object>> getBusiRange();
    
}