package com.sunyard.ars.system.dao.sc;

import com.sunyard.ars.system.bean.sc.FieldComp;
import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface FieldCompMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_FIELD_COMP_TB
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("outSourceId") BigDecimal outSourceId, @Param("outerField") String outerField);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_FIELD_COMP_TB
     *
     * @mbggenerated
     */
    int insert(FieldComp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_FIELD_COMP_TB
     *
     * @mbggenerated
     */
    int insertSelective(FieldComp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_FIELD_COMP_TB
     *
     * @mbggenerated
     */
    FieldComp selectByPrimaryKey(@Param("outSourceId") BigDecimal outSourceId, @Param("outerField") String outerField);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_FIELD_COMP_TB
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FieldComp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_FIELD_COMP_TB
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FieldComp record);
    
    /**
     * 根据对象中的非空属性查询
     * @param record
     * @return
     */
    List<FieldComp> selectBySelective(FieldComp record);
}