package com.sunyard.ars.system.dao.sc;

import java.util.List;

import com.sunyard.ars.system.bean.sc.FieldDef;

public interface FieldDefMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_FIELD_DEF_TB
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String fieldName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_FIELD_DEF_TB
     *
     * @mbggenerated
     */
    int insert(FieldDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_FIELD_DEF_TB
     *
     * @mbggenerated
     */
    int insertSelective(FieldDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_FIELD_DEF_TB
     *
     * @mbggenerated
     */
    FieldDef selectByPrimaryKey(String fieldName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_FIELD_DEF_TB
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FieldDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_FIELD_DEF_TB
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FieldDef record);
    
    /**
     * 根据对象中的非空属性查询。
     * @param record
     * @return
     */
    List<FieldDef> selectBySelective(FieldDef record);
}