package com.sunyard.ars.system.dao.sc;

import java.util.List;

import com.sunyard.ars.system.bean.sc.FormManPro;

public interface FormManProMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_FORM_MAN_PRO_TB
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String formName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_FORM_MAN_PRO_TB
     *
     * @mbggenerated
     */
    int insert(FormManPro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_FORM_MAN_PRO_TB
     *
     * @mbggenerated
     */
    int insertSelective(FormManPro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_FORM_MAN_PRO_TB
     *
     * @mbggenerated
     */
    FormManPro selectByPrimaryKey(String formName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_FORM_MAN_PRO_TB
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FormManPro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_FORM_MAN_PRO_TB
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FormManPro record);
    
    /**
     * 根据对象非空属性查询
     * @param record
     * @return
     */
    List<FormManPro> selectBySelective(FormManPro record);
}