package com.sunyard.ars.system.dao.sc;

import com.sunyard.ars.system.bean.sc.FormInfo;
import java.math.BigDecimal;
import java.util.List;

public interface FormInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_FORM_INFO_TB
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal formId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_FORM_INFO_TB
     *
     * @mbggenerated
     */
    int insert(FormInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_FORM_INFO_TB
     *
     * @mbggenerated
     */
    int insertSelective(FormInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_FORM_INFO_TB
     *
     * @mbggenerated
     */
    FormInfo selectByPrimaryKey(BigDecimal formId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_FORM_INFO_TB
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FormInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_FORM_INFO_TB
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FormInfo record);
    
    /**
     * 获取所有配置的表单
     * @return
     */
    List<FormInfo> getAllFormInfo();
    
    /**
     * 获取版面人工处理未配置的表单
     * @return
     */
    List<FormInfo> getLeftFormInfo();
}