package com.sunyard.ars.system.dao.sc;

import com.sunyard.ars.system.bean.sc.PageBase;
import java.math.BigDecimal;
import java.util.List;

public interface PageBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_PAGE_BASE_TB
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal pageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_PAGE_BASE_TB
     *
     * @mbggenerated
     */
    int insert(PageBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_PAGE_BASE_TB
     *
     * @mbggenerated
     */
    int insertSelective(PageBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_PAGE_BASE_TB
     *
     * @mbggenerated
     */
    PageBase selectByPrimaryKey(BigDecimal pageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_PAGE_BASE_TB
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PageBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_PAGE_BASE_TB
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PageBase record);
    
    /**
     * 根据表单名称获取子项列表
     * @param formName
     * @return
     */
    List<PageBase> getFormSubByFormName(String formName);
}