package com.sunyard.ars.system.dao.sc;

import java.math.BigDecimal;
import java.util.List;

import com.sunyard.ars.system.bean.sc.SCDatasource;

public interface SCDatasourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUNARS.SM_DATASOURCE_SET_TB
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String dataSourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUNARS.SM_DATASOURCE_SET_TB
     *
     * @mbggenerated
     */
    int insert(SCDatasource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUNARS.SM_DATASOURCE_SET_TB
     *
     * @mbggenerated
     */
    int insertSelective(SCDatasource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUNARS.SM_DATASOURCE_SET_TB
     *
     * @mbggenerated
     */
    SCDatasource selectByPrimaryKey(String dataSourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUNARS.SM_DATASOURCE_SET_TB
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SCDatasource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SUNARS.SM_DATASOURCE_SET_TB
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SCDatasource record);
    
    /**
     * 根据对象中非空属性为查询条件查询
     * @param record
     * @return
     */
    List<SCDatasource> selectBySelective(SCDatasource record);
    
    /**
     * 获取最大id
     * @return
     */
    BigDecimal getMaxSourceId();
}