package com.sunyard.ars.system.dao.sc;

import com.sunyard.ars.system.bean.sc.ServiceReg;
import java.math.BigDecimal;
import java.util.List;

public interface ServiceRegMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_SERVICE_REG_TB
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal serviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_SERVICE_REG_TB
     *
     * @mbggenerated
     */
    int insert(ServiceReg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_SERVICE_REG_TB
     *
     * @mbggenerated
     */
    int insertSelective(ServiceReg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_SERVICE_REG_TB
     *
     * @mbggenerated
     */
    ServiceReg selectByPrimaryKey(BigDecimal serviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_SERVICE_REG_TB
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ServiceReg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_SERVICE_REG_TB
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ServiceReg record);
    
    /**
     * 根据对象非空属性查询。
     * @param record
     * @return
     */
    List<ServiceReg> selectBySelective(ServiceReg record);
    
    /**
     * 获取表中最大serviceId
     * @return
     */
    BigDecimal getMaxServiceId();
    
    /**
     * 根据服务类型获取组列表。
     * @param serviceType
     * @return
     */
    List<BigDecimal> getGroupIdByType(String serviceType);
}