package com.sunyard.ars.system.dao.sc;

import com.sunyard.ars.system.bean.sc.TableDef;
import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TableDefMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_TABLE_DEF_TB
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal tableId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_TABLE_DEF_TB
     *
     * @mbggenerated
     */
    int insert(TableDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_TABLE_DEF_TB
     *
     * @mbggenerated
     */
    int insertSelective(TableDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_TABLE_DEF_TB
     *
     * @mbggenerated
     */
    TableDef selectByPrimaryKey(BigDecimal tableId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_TABLE_DEF_TB
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TableDef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_TABLE_DEF_TB
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TableDef record);
    
    /**
     * 根据对象的非空属性查询
     * @param record
     * @return
     */
    List<TableDef> selectBySelective(TableDef record);
    
    /**
     * 获取最大表ID
     * @return
     */
    BigDecimal getMaxTableId();
    
    int dataArchive(@Param("sql") String sql);
}