package com.sunyard.ars.system.dao.sc;


import com.sunyard.ars.system.bean.sc.VoucherInfo;
import java.math.BigDecimal;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component("scVoucherInfoMapper")
public interface VoucherInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_VOUCHER_INFO_TB
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal voucherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_VOUCHER_INFO_TB
     *
     * @mbggenerated
     */
    int insert(VoucherInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_VOUCHER_INFO_TB
     *
     * @mbggenerated
     */
    int insertSelective(VoucherInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_VOUCHER_INFO_TB
     *
     * @mbggenerated
     */
    VoucherInfo selectByPrimaryKey(BigDecimal voucherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_VOUCHER_INFO_TB
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(VoucherInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_VOUCHER_INFO_TB
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VoucherInfo record);
    
    /**
     * 根据对象中的非空属性查询
     * @param record
     * @return
     */
    List<VoucherInfo> selectBySelective(VoucherInfo record);

	int selectVoucherOnlyByName(@Param("voucherName")  String voucherName);

    /**
     * 获取最大凭证ID
     * @return
     */
    BigDecimal getMaxVoucherId();
    
    /**
	 * 获取所有版面的补录和限制信息
	 */
	public List<HashMap<String, Object>> selectAllForms();
	
	/**
	 * 版面参数获取 
	 */
	public List<HashMap<String, Object>> selectFormMap(HashMap<String, Object> map);
	
	 List<Map> selectByVocherName(@Param("voucherName") String voucherName);
	 int insertOrgan (@Param("voucherName")String voucherName,@Param("organNo")String organNo);
	 /**
	  * 查询凭证信息和机构个数
	  * @param record
	  * @return
	  */
	 List<Map> selectVoucherInfoAndCNT(VoucherInfo record);
	 
	 int deleteByVoucherName(@Param("voucherName") String voucherName);
	 
	 
     int updateTradeFormInfo(@Param("voucherName") String voucherName,@Param("voucherOldName") String voucherOldName);
	 //更新smocrprechecktb信息
	 int updateOcrpreCheckTb(@Param("voucherName") String voucherName,@Param("voucherOldName") String voucherOldName);
	 //更新SmFormManProTb信息
	 int updateSmFormManProInfo(@Param("voucherName") String voucherName,@Param("voucherOldName") String voucherOldName);
	 //更新 smformInfotb信息
	 int updateFormInfo(@Param("voucherName") String voucherName,@Param("voucherOldName") String voucherOldName);
}