package com.sunyard.ars.file.dao.ma;

import java.util.HashMap;
import java.util.List;

public interface VoucherInfoMapper {
 
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_VOUCHER_INFO_TB
     *
     * @mbg.generated
     */
	List<HashMap<String, Object>> selectByPrimaryKey(String voucherName);

	/**
	 * 获取页面上配置的存在附件标志的版面
	 */
	public List<HashMap<String, Object>> selectAttachmentForm();
	
	/**
	 * 获取所有版面的补录和限制信息
	 */
	public List<HashMap<String, Object>> selectAllFormInfo();
	
	/**
	 * 版面参数获取 
	 */
	public List<HashMap<String, Object>> selectFormNameMap(HashMap<String, Object> map);
}