package com.sunyard.ars.system.dao.log;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.sunyard.ars.system.bean.log.OperLog;

public interface OperLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_OPERLOG_TB
     *
     * @mbggenerated
     */
    int insert(OperLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SM_OPERLOG_TB
     *
     * @mbggenerated
     */
    int insertSelective(OperLog record);
    
    /**
     * 查询日志信息
     * @param condMap
     * @return
     */
    List<OperLog> queryBySelective(HashMap<String,Object> condMap);
    List<Map> queryByCondition(HashMap<String,Object> condMap);
    
    List reLogQuery(@Param("organNo")String[] organNo,@Param("operator")String operator,@Param("startDate")String startDate,@Param("endDate")String endDate);
    
}